== Generate Archetype

The `generate-archetype` mojo will generate a new archetype maven project based on an existing archetype project.  It is designed to facilitate the maintenance of several similar archetypes which differe only in some dependencies or default project source code.  It takes as input a template file which references the base archetype project and specifies what to customize.

**Example Usage**

    mvn cn1:generate-archetype -Dtemplate=/path/to/mytemplate.java

=== Parameters

template::
Required.  The path to a template file that should be used to generate the archetype project.

outputDir::
Optional. The output directory where the archetype project should be written to.  The project will be created at `outputDir`/`artifactId`, where the `artifactId` is as specified in the `[archetype]` section of the template.  By default this will be the current working directory.

[NOTE]
====
This goal does not require a project in order to run.  You can run it directly using the full goal coordinates:

    mvn com.codenameone:codenameone-maven-plugin:7.0-SNAPSHOT:generate-archetype \
        -Dtemplate=/path/to/mytemplate.java

====


=== Template Syntax

Here is a sample template file:

.A sample template, which is just a .java file.
[source,text]
-----
#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
package ${package};
/*
[archetype] <1>
----
extends=../helloworld-archetype <2>
groupId=com.codenameone.archetypes
artifactId=helloworld2-archetype
version=7.0-SNAPSHOT
----

[dependencies] <3>
----
<dependency>
<groupId>com.codenameone.libs</groupId>
<artifactId>filechooser-lib</artifactId>
<version>1.0-SNAPSHOT</version>
<type>pom</type>
</dependency>
----
 */
import static com.codename1.ui.CN.*;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class ${mainName} {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
        // prevent the event from propagating
        err.consume();
        if(err.getError() != null) {
            Log.e(err.getError());
        }
        Log.sendLogAsync();
        Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });
    }


    public void start() {
        if(current != null){
            current.show();
            return;
        }
        //WebSocket sock;
        Form hi = new Form("Hi World", BoxLayout.y());
        hi.add(new Label("Hello World"));

        hi.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }

    public void destroy() {
    }

}

-----
<1> The `[archetype]` section specifies details about the archetype project to be generated.  E.g. the `groupId`, `artifactId`, etc...
<2> The `extends` property in the `[archetype]` section is required, and points to the location of the archetype project that this template is based on.  Path is relative to the location of the template file.
<3> The `[dependencies]` section includes content that should be injected into the `<dependencies>` section of the pom.xml file.  Note that this is not the pom file for the archetype project itself.  It is the pom.xml file for the project that the archetype project is to generate.

Notice that the above template is velocity template for a java file. It will be used as the source code for the main class in the resulting project.  It is a velocity template because maven's `archetype:generate` goal will process it to replace properties such as package and the main class name.

==== Template Sections

archetype::
This is a required section and specifies both the location of the base archetype project from which this project is to be derived, and the the coordinates of the output archetype project, such as `groupId`, `archetypeId`, and `version`.
+
====
**Example**

[source,text]
-----
[archetype]
----
extends=../helloworld-archetype
groupId=com.codenameone.archetypes
artifactId=helloworld2-archetype
version=7.0-SNAPSHOT
----
-----

**Properties**

extends::
Required. The path to the archetype project that this is based on.  This should usually be the `helloworld-archetype` project as it includes the placeholders that this generator relies on for injecting content into the pom.xml file and its project structure was used as a basis for developing this mojo.

groupId::
The groupID of the resulting archetype project.  You can alternatively use the `id` property to specify `groupId`, `artifactId` and `version` in a single string.

artifactId::
The artifactId of the resulting archetype project. You can alternatively use the `id` property to specify `groupId`, `artifactId` and `version` in a single string.

version::
The version of the resulting archetype project. You can alternatively use the `id` property to specify `groupId`, `artifactId` and `version` in a single string.

id::
A colon-separated string in the format `groupId:artifactId:version` that can be used as an alternative to `groupId`, `artifactId`, and `version`.

parentGroupId::
If the output archetype project should be part of a multi-module project, then this will specify the parent `groupId` for the `<parent>` tag in the pom.xml file.

parentArtifactId::
If the output archetype project should be part of a multi-module project, then this will specify the parent `archetypeId` for the `<parent>` tag in the pom.xml file.

parentVersion::
If the output archetype project should be part of a multi-module project, then this will specify the parent `archetypeId` for the `<parent>` tag in the pom.xml file.

parent::
A colon-delimited string in the format `parentGroupId:parentArtifactId:parentVersion` that can be used as an alternative to the `parentGroupId`, `parentArtifactId`, and `parentVersion` properties separately.

====

dependencies::
Specify additional dependencies that should be injected into the `<dependencies>` section of the pom.xml file for the common module of the maven project that the archetype will generate.  The content of this section will be injected into the `src/main/resources/archetype-resources/common/pom.xml` of the archetype project.
+
====
**Example**

[source,text]
----
[dependencies]
---
<dependency>
    <groupId>com.codenameone.libs</groupId>
    <artifactId>filechooser-lib</artifactId>
    <version>1.0-SNAPSHOT</version>
    <type>pom</type>
</dependency>
---
----
====

css::
CSS content that should be injected into the theme.css file of the project.  This CSS will be injected into the `src/main/resources/archetype-resources/common/src/main/css/theme.css` file of the archetype project.
+
====
**Example**

[source,text]
----
[css]
---
#Constants {
    includeNativeBool: true;
}
Button {
    color:green;
    border:1px solid green;
    border-radius: 2mm;
    margin: 5mm;
}
---
----
====

properties::
Properties that should be appended to the `codenameone_settings.properties` file.  These will be added to the `src/main/resources/archetype_resources/common/codenameone_settings.properties` file of the archetype project.
+
====
**Example**

[source,text]
----
[properties]
---
codename1.arg.win.desktop-vm=zuluFx8-32bit
codename1.arg.win.desktopExtractDll=true
codename1.arg.win.launchOnStart=true
codename1.arg.win.runAfterInstall=true
---
----
====

files::
Files contains a list of files that should be created in the archetype project.  All file paths are relative to the "common" project root directory.  Each path should have a corresponding section with the heading `[file:path/to/file]`.
+
====
**Example**

[source,text]
-----
[files]
----
src/main/guibuilder/__mainName__MainForm.gui
src/main/java/__mainName__MainForm.java
----

[file:src/main/guibuilder/__mainName__MainForm.gui]
----
<?xml version="1.0" encoding="UTF-8"?>

<component type="Form" layout="LayeredLayout" layeredLayoutPreferredWidthMM="0.0" layeredLayoutPreferredHeightMM="0.0"  autolayout="true" title="${mainName}MainForm" scrollableY="true" name="${mainName}MainForm">
<component type="Button" text="Click Me" name="Button">
<layoutConstraint insets="auto auto auto auto" referenceComponents="-1 -1 -1 -1" referencePositions="0.0 0.0 0.0 0.0" />
</component>
</component>
----

[file:src/main/java/__mainName__MainForm.java]
----
package ${package};
public class ${mainName}MainForm extends com.codename1.ui.Form {
public ${mainName}MainForm() {
this(com.codename1.ui.util.Resources.getGlobalResources());
}

    public ${mainName}MainForm(com.codename1.ui.util.Resources resourceObjectInstance) {
        initGuiBuilderComponents(resourceObjectInstance);
    }

//-- DON'T EDIT BELOW THIS LINE!!!
    protected com.codename1.ui.Button gui_Button = new com.codename1.ui.Button();


// <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initGuiBuilderComponents(com.codename1.ui.util.Resources resourceObjectInstance) {
        setLayout(new com.codename1.ui.layouts.LayeredLayout());
        setInlineStylesTheme(resourceObjectInstance);
        setScrollableY(true);
                setInlineStylesTheme(resourceObjectInstance);
        setTitle("MyForm");
        setName("MyForm");
        gui_Button.setText("Click Me");
                gui_Button.setInlineStylesTheme(resourceObjectInstance);
        gui_Button.setName("Button");
        addComponent(gui_Button);
        ((com.codename1.ui.layouts.LayeredLayout)gui_Button.getParent().getLayout()).setInsets(gui_Button, "auto auto auto auto").setReferenceComponents(gui_Button, "-1 -1 -1 -1").setReferencePositions(gui_Button, "0.0 0.0 0.0 0.0");
    }// </editor-fold>

//-- DON'T EDIT ABOVE THIS LINE!!!
}
----
-----
====
