codename1.mainName=VideoBuilder
codename1.packageName=com.codename1.videobuilder
codename1.displayName=Codename One Video Builder
codename1.version=1.0
codename1.vendor=CodenameOne
codename1.cssTheme=true
codename1.arg.java.version=17
codename1.arg.desktop.width=1280
codename1.arg.desktop.height=720
codename1.arg.desktop.titleBar=native
codename1.kotlin=false
