= Archetype Generator

This directory contains the archetype generator project which will convert the archetype templates in link:../templates/README.adoc[templates directory]  into full maven archetype projects, in the <<../generated-archetypes, generated-archetypes directory>>.

== Why?

Because it is easier to maintain a set of archetypes that are similar if we factor out common elements into a single "parent" project, and just derive from that.  Most of the templates derive from the <<../helloworld-archetype,helloworld-archetype>>, which is just a basic Hello World project written in Java.

== How?

This uses the <<../../codenameone-maven-plugin/src/main/java/com/codename1/maven/GenerateArchetypeProjectsMojo.java#,generate-archetype-projects>> goal, which, in turn uses the <<../../codenameone-maven-plugin/src/main/java/com/codename1/maven/GenerateArchetypeFromTemplateMojo.java#,generate-archetype>> goal on each individual project.

TIP: See <<../../codenameone-maven-plugin/src/main/asciidoc/mojos/generate-archetype.adoc#,generate-archetype documentation>> for template syntax examples.

== Usage Instructions

Whenever you make any changes to one of the core archetypes (<<../helloworld-archetype#,helloworld-archetype>> or <<../cn1lib-archetype#,cn1lib-archetype>>), you should run this project.  If you enable the *generate-archetypes* profile when building the <<../maven-archetypes#, maven-archetypes>> project, it will generate the archetypes.  E.g.

[source,bash]
----
cd path/to/maven-archetypes
mvn install -Pgenerate-archetypes
----

This will delete the <<../generated-archetypes#,generated-archetypes>> directory and recreate it with updated projects based on the current state of the helloworld and cn1lib archetypes.

