package com.codename1.svg.transcoder.codegen;

import com.codename1.svg.transcoder.model.*;
import com.codename1.svg.transcoder.parser.*;

import java.io.IOException;
import java.io.Writer;
import java.util.List;
import java.util.Locale;

/**
 * Walks a parsed {@link SVGDocument} and emits a Java source file that
 * extends {@code com.codename1.ui.GeneratedSVGImage} and renders the SVG
 * using the Codename One {@code Graphics} shape API. SMIL animations on a
 * node become inline calls to the animation helpers on the runtime base
 * class so the emitted code stays self-contained.
 *
 * <p>The generator is intentionally direct -- one shape per inline block,
 * no method extraction -- both to keep the emitted code readable and to
 * avoid surprising the bytecode translator with large method counts.</p>
 */
public final class JavaCodeGenerator {

    private final SVGDocument doc;
    private final String packageName;
    private final String className;
    private final StringBuilder body = new StringBuilder();
    private int indent = 2;
    private int idSeq;

    public JavaCodeGenerator(SVGDocument doc, String packageName, String className) {
        this.doc = doc;
        this.packageName = packageName;
        this.className = className;
    }

    public void generate(Writer out) throws IOException {
        boolean animated = containsAnimation(doc);
        emitPaintBody(doc);

        StringBuilder src = new StringBuilder();
        if (packageName != null && !packageName.isEmpty()) {
            src.append("package ").append(packageName).append(";\n\n");
        }
        src.append("import com.codename1.ui.Font;\n");
        src.append("import com.codename1.ui.GeneratedSVGImage;\n");
        src.append("import com.codename1.ui.Graphics;\n");
        src.append("import com.codename1.ui.LinearGradientPaint;\n");
        src.append("import com.codename1.ui.MultipleGradientPaint;\n");
        src.append("import com.codename1.ui.Stroke;\n");
        src.append("import com.codename1.ui.Transform;\n");
        src.append("import com.codename1.ui.geom.GeneralPath;\n\n");
        src.append("/** Generated by codenameone-svg-transcoder. DO NOT EDIT. */\n");
        src.append("public final class ").append(className).append(" extends GeneratedSVGImage {\n\n");
        String dimensions = intLit((int) Math.ceil(doc.getWidth()))
                + ", " + intLit((int) Math.ceil(doc.getHeight()))
                + ", " + floatLit(doc.getViewBoxX())
                + ", " + floatLit(doc.getViewBoxY())
                + ", " + floatLit(doc.getViewBoxWidth())
                + ", " + floatLit(doc.getViewBoxHeight())
                + ", " + animated;
        src.append("    /** Construct with the default source density (DENSITY_MEDIUM). */\n");
        src.append("    public ").append(className).append("() {\n");
        src.append("        super(").append(dimensions).append(");\n");
        src.append("    }\n\n");
        src.append("    /** Construct with an explicit source density. Used by the\n");
        src.append("     *  auto-generated SVGRegistry to honor `cn1-source-dpi` hints from\n");
        src.append("     *  the CSS file referencing this SVG. */\n");
        src.append("    public ").append(className).append("(int sourceDensity) {\n");
        src.append("        super(").append(dimensions).append(", sourceDensity);\n");
        src.append("    }\n\n");
        src.append("    /** Construct with explicit dimensions in millimeters; converted to\n");
        src.append("     *  device pixels via Display.convertToPixels so the rendered size\n");
        src.append("     *  carries across DPIs. Used by the auto-generated SVGRegistry to\n");
        src.append("     *  honor `cn1-svg-width` / `cn1-svg-height` CSS hints. */\n");
        src.append("    public ").append(className).append("(float widthMm, float heightMm) {\n");
        src.append("        super(").append(dimensions).append(",\n");
        src.append("                GeneratedSVGImage.mmToPixels(widthMm),\n");
        src.append("                GeneratedSVGImage.mmToPixels(heightMm));\n");
        src.append("    }\n\n");
        src.append("    @Override\n");
        src.append("    protected void paintSVG(Graphics g, long __t) {\n");
        src.append(body);
        src.append("    }\n");
        src.append("}\n");

        out.write(src.toString());
    }

    private void emitPaintBody(SVGGroup root) {
        // Shared scratch slots -- reassigned per shape; not redeclared inside
        // nested blocks since Java forbids local-variable shadowing.
        line("GeneralPath __p = null;");
        line("Stroke __s = null;");
        line("if (__p != null || __s != null) { /* keep javac happy */ }");
        for (SVGNode child : root.getChildren()) {
            emitNode(child, null);
        }
    }

    private void emitNode(SVGNode n, SVGStyle parentStyle) {
        SVGStyle inherited = mergedStyle(n, parentStyle);
        SVGTransform tr = n.getTransform();
        List<SVGAnimation> anims = n.getAnimations();
        boolean hasTransformAnim = hasTransformAnimation(anims);
        boolean needsTransform = tr != null || hasTransformAnim;

        String savedVar = null;
        String newVar = null;
        if (needsTransform) {
            // Fresh names per block so sibling transformed elements compile
            // (Java does not allow shadowing of enclosing locals).
            int id = idSeq++;
            savedVar = "__tsave" + id;
            newVar = "__tnew" + id;
            line("{");
            indent++;
            line("Transform " + savedVar + " = g.getTransform();");
            line("Transform " + newVar + " = " + savedVar + ".copy();");
            if (tr != null) {
                emitApplyMatrix(newVar, tr);
            }
            for (SVGAnimation a : anims) {
                if (a.getKind() == SVGAnimation.Kind.ANIMATE_TRANSFORM) {
                    emitApplyAnimatedTransform(newVar, a);
                }
            }
            line("g.setTransform(" + newVar + ");");
            line("try {");
            indent++;
        }

        String clipRef = inherited.getClipPathRef();
        SVGClipPath clip = null;
        String clipVar = null;
        if (clipRef != null) {
            SVGNode def = doc.getDefinitions().get(clipRef);
            if (def instanceof SVGClipPath) {
                clip = (SVGClipPath) def;
                clipVar = "__clip" + (idSeq++);
                emitClipShape(clip, clipVar);
                line("g.pushClip();");
                line("try {");
                indent++;
                line("g.setClip(" + clipVar + ");");
            }
        }

        try {
            if (n instanceof SVGGroup) {
                SVGGroup g = (SVGGroup) n;
                for (SVGNode child : g.getChildren()) {
                    emitNode(child, inherited);
                }
            } else if (n instanceof SVGRect) {
                emitRect((SVGRect) n, inherited, anims);
            } else if (n instanceof SVGCircle) {
                emitCircle((SVGCircle) n, inherited, anims);
            } else if (n instanceof SVGEllipse) {
                emitEllipse((SVGEllipse) n, inherited, anims);
            } else if (n instanceof SVGLine) {
                emitLine((SVGLine) n, inherited, anims);
            } else if (n instanceof SVGPolyline) {
                emitPolyline((SVGPolyline) n, inherited, anims);
            } else if (n instanceof SVGPath) {
                emitPath((SVGPath) n, inherited, anims);
            } else if (n instanceof SVGText) {
                emitText((SVGText) n, inherited, anims);
            }
        } finally {
            if (clip != null) {
                indent--;
                line("} finally {");
                indent++;
                line("g.popClip();");
                indent--;
                line("}");
            }
            if (needsTransform) {
                indent--;
                line("} finally {");
                indent++;
                line("g.setTransform(" + savedVar + ");");
                indent--;
                line("}");
                indent--;
                line("}");
            }
        }
    }

    /// Build a GeneralPath that captures the outline of the first shape child
    /// of a `<clipPath>`. The supported subset matches what most icon
    /// authoring tools emit -- rect / circle / ellipse / polygon / polyline /
    /// path. Multi-shape clipPaths and nested clip refs inside the clipPath
    /// are flattened to the first child for simplicity.
    private void emitClipShape(SVGClipPath cp, String varName) {
        SVGShape shape = null;
        for (SVGNode c : cp.getChildren()) {
            if (c instanceof SVGShape) {
                shape = (SVGShape) c;
                break;
            }
            if (c instanceof SVGGroup) {
                for (SVGNode cc : ((SVGGroup) c).getChildren()) {
                    if (cc instanceof SVGShape) {
                        shape = (SVGShape) cc;
                        break;
                    }
                }
                if (shape != null) break;
            }
        }
        line("GeneralPath " + varName + " = new GeneralPath();");
        if (shape == null) {
            // Empty clipPath -- the spec says elements with a clip-path that
            // points at an empty clipPath are not rendered, but our caller
            // will still try to fillShape(...). Emit a degenerate path so the
            // resulting clip clips everything out.
            return;
        }
        if (shape instanceof SVGRect) {
            SVGRect r = (SVGRect) shape;
            float rx = r.getRx();
            float ry = r.getRy();
            if (rx == 0 && ry > 0) rx = ry;
            if (ry == 0 && rx > 0) ry = rx;
            if (rx <= 0f && ry <= 0f) {
                line(varName + ".moveTo(" + floatLit(r.getX()) + ", " + floatLit(r.getY()) + ");");
                line(varName + ".lineTo(" + floatLit(r.getX() + r.getWidth()) + ", " + floatLit(r.getY()) + ");");
                line(varName + ".lineTo(" + floatLit(r.getX() + r.getWidth()) + ", " + floatLit(r.getY() + r.getHeight()) + ");");
                line(varName + ".lineTo(" + floatLit(r.getX()) + ", " + floatLit(r.getY() + r.getHeight()) + ");");
                line(varName + ".closePath();");
            } else {
                // Rounded rect outline.
                String x = floatLit(r.getX());
                String y = floatLit(r.getY());
                String w = floatLit(r.getWidth());
                String h = floatLit(r.getHeight());
                String rxs = floatLit(rx);
                String rys = floatLit(ry);
                line(varName + ".moveTo(" + r.getX() + "f + " + rxs + ", " + y + ");");
                line(varName + ".lineTo(" + r.getX() + "f + " + w + " - " + rxs + ", " + y + ");");
                line(varName + ".quadTo(" + r.getX() + "f + " + w + ", " + y + ", " + r.getX() + "f + " + w + ", " + r.getY() + "f + " + rys + ");");
                line(varName + ".lineTo(" + r.getX() + "f + " + w + ", " + r.getY() + "f + " + h + " - " + rys + ");");
                line(varName + ".quadTo(" + r.getX() + "f + " + w + ", " + r.getY() + "f + " + h + ", " + r.getX() + "f + " + w + " - " + rxs + ", " + r.getY() + "f + " + h + ");");
                line(varName + ".lineTo(" + r.getX() + "f + " + rxs + ", " + r.getY() + "f + " + h + ");");
                line(varName + ".quadTo(" + x + ", " + r.getY() + "f + " + h + ", " + x + ", " + r.getY() + "f + " + h + " - " + rys + ");");
                line(varName + ".lineTo(" + x + ", " + r.getY() + "f + " + rys + ");");
                line(varName + ".quadTo(" + x + ", " + y + ", " + r.getX() + "f + " + rxs + ", " + y + ");");
                line(varName + ".closePath();");
            }
        } else if (shape instanceof SVGCircle) {
            SVGCircle c = (SVGCircle) shape;
            line(varName + ".arc(" + floatLit(c.getCx() - c.getR()) + ", "
                    + floatLit(c.getCy() - c.getR()) + ", "
                    + floatLit(2 * c.getR()) + ", " + floatLit(2 * c.getR())
                    + ", 0f, 6.2831855f);");
        } else if (shape instanceof SVGEllipse) {
            SVGEllipse e = (SVGEllipse) shape;
            line(varName + ".arc(" + floatLit(e.getCx() - e.getRx()) + ", "
                    + floatLit(e.getCy() - e.getRy()) + ", "
                    + floatLit(2 * e.getRx()) + ", " + floatLit(2 * e.getRy())
                    + ", 0f, 6.2831855f);");
        } else if (shape instanceof SVGPolyline) {
            float[] pts = ((SVGPolyline) shape).getPoints();
            if (pts.length >= 4) {
                line(varName + ".moveTo(" + floatLit(pts[0]) + ", " + floatLit(pts[1]) + ");");
                for (int i = 2; i + 1 < pts.length; i += 2) {
                    line(varName + ".lineTo(" + floatLit(pts[i]) + ", " + floatLit(pts[i + 1]) + ");");
                }
                if (((SVGPolyline) shape).isClosed()) {
                    line(varName + ".closePath();");
                }
            }
        } else if (shape instanceof SVGPath) {
            // Re-emit path commands into varName.
            for (PathCommand pc : ((SVGPath) shape).getCommands()) {
                float[] a = pc.getArgs();
                switch (pc.getType()) {
                    case MOVE:  line(varName + ".moveTo(" + floatLit(a[0]) + ", " + floatLit(a[1]) + ");"); break;
                    case LINE:  line(varName + ".lineTo(" + floatLit(a[0]) + ", " + floatLit(a[1]) + ");"); break;
                    case CUBIC: line(varName + ".curveTo(" + floatLit(a[0]) + ", " + floatLit(a[1]) + ", "
                            + floatLit(a[2]) + ", " + floatLit(a[3]) + ", "
                            + floatLit(a[4]) + ", " + floatLit(a[5]) + ");"); break;
                    case QUAD:  line(varName + ".quadTo(" + floatLit(a[0]) + ", " + floatLit(a[1]) + ", "
                            + floatLit(a[2]) + ", " + floatLit(a[3]) + ");"); break;
                    case ARC:   line("GeneratedSVGImage.svgArc(" + varName + ", "
                            + floatLit(a[0]) + ", " + floatLit(a[1]) + ", "
                            + floatLit(a[2]) + ", " + floatLit(a[3]) + ", "
                            + floatLit(a[4]) + ", " + (a[5] != 0f) + ", " + (a[6] != 0f) + ", "
                            + floatLit(a[7]) + ", " + floatLit(a[8]) + ");"); break;
                    case CLOSE: line(varName + ".closePath();"); break;
                    default: break;
                }
            }
        }
    }

    // ---- shape emitters ----------------------------------------------------

    private void emitRect(SVGRect r, SVGStyle style, List<SVGAnimation> anims) {
        AnimatedFloat x = animFloat("x", r.getX(), anims);
        AnimatedFloat y = animFloat("y", r.getY(), anims);
        AnimatedFloat w = animFloat("width", r.getWidth(), anims);
        AnimatedFloat h = animFloat("height", r.getHeight(), anims);
        float rx = r.getRx();
        float ry = r.getRy();
        if (rx == 0 && ry > 0) rx = ry;
        if (ry == 0 && rx > 0) ry = rx;

        line("__p = new GeneralPath();");
        if (rx <= 0f && ry <= 0f) {
            line("__p.moveTo(" + x.expr + ", " + y.expr + ");");
            line("__p.lineTo(" + plus(x.expr, w.expr) + ", " + y.expr + ");");
            line("__p.lineTo(" + plus(x.expr, w.expr) + ", " + plus(y.expr, h.expr) + ");");
            line("__p.lineTo(" + x.expr + ", " + plus(y.expr, h.expr) + ");");
            line("__p.closePath();");
        } else {
            String xs = x.expr, ys = y.expr, ws = w.expr, hs = h.expr;
            String rxs = floatLit(rx), rys = floatLit(ry);
            line("__p.moveTo(" + plus(xs, rxs) + ", " + ys + ");");
            line("__p.lineTo(" + plus(xs, w.expr) + " - " + rxs + ", " + ys + ");");
            line("__p.quadTo(" + plus(xs, ws) + ", " + ys + ", "
                    + plus(xs, ws) + ", " + plus(ys, rys) + ");");
            line("__p.lineTo(" + plus(xs, ws) + ", " + plus(ys, hs) + " - " + rys + ");");
            line("__p.quadTo(" + plus(xs, ws) + ", " + plus(ys, hs) + ", "
                    + plus(xs, ws) + " - " + rxs + ", " + plus(ys, hs) + ");");
            line("__p.lineTo(" + plus(xs, rxs) + ", " + plus(ys, hs) + ");");
            line("__p.quadTo(" + xs + ", " + plus(ys, hs) + ", "
                    + xs + ", " + plus(ys, hs) + " - " + rys + ");");
            line("__p.lineTo(" + xs + ", " + plus(ys, rys) + ");");
            line("__p.quadTo(" + xs + ", " + ys + ", " + plus(xs, rxs) + ", " + ys + ");");
            line("__p.closePath();");
        }
        emitFillAndStroke(style, anims);
    }

    private void emitCircle(SVGCircle c, SVGStyle style, List<SVGAnimation> anims) {
        AnimatedFloat cx = animFloat("cx", c.getCx(), anims);
        AnimatedFloat cy = animFloat("cy", c.getCy(), anims);
        AnimatedFloat rad = animFloat("r", c.getR(), anims);
        line("__p = new GeneralPath();");
        line("__p.arc(" + cx.expr + " - " + rad.expr + ", "
                + cy.expr + " - " + rad.expr + ", "
                + "2f * " + rad.expr + ", 2f * " + rad.expr
                + ", 0f, 6.2831855f);");
        emitFillAndStroke(style, anims);
    }

    private void emitEllipse(SVGEllipse e, SVGStyle style, List<SVGAnimation> anims) {
        AnimatedFloat cx = animFloat("cx", e.getCx(), anims);
        AnimatedFloat cy = animFloat("cy", e.getCy(), anims);
        AnimatedFloat rx = animFloat("rx", e.getRx(), anims);
        AnimatedFloat ry = animFloat("ry", e.getRy(), anims);
        line("__p = new GeneralPath();");
        line("__p.arc(" + cx.expr + " - " + rx.expr + ", "
                + cy.expr + " - " + ry.expr + ", "
                + "2f * " + rx.expr + ", 2f * " + ry.expr
                + ", 0f, 6.2831855f);");
        emitFillAndStroke(style, anims);
    }

    private void emitLine(SVGLine l, SVGStyle style, List<SVGAnimation> anims) {
        AnimatedFloat x1 = animFloat("x1", l.getX1(), anims);
        AnimatedFloat y1 = animFloat("y1", l.getY1(), anims);
        AnimatedFloat x2 = animFloat("x2", l.getX2(), anims);
        AnimatedFloat y2 = animFloat("y2", l.getY2(), anims);
        line("__p = new GeneralPath();");
        line("__p.moveTo(" + x1.expr + ", " + y1.expr + ");");
        line("__p.lineTo(" + x2.expr + ", " + y2.expr + ");");
        emitFillAndStroke(style, anims);
    }

    private void emitPolyline(SVGPolyline pl, SVGStyle style, List<SVGAnimation> anims) {
        float[] pts = pl.getPoints();
        if (pts.length < 4) return;
        line("__p = new GeneralPath();");
        line("__p.moveTo(" + floatLit(pts[0]) + ", " + floatLit(pts[1]) + ");");
        for (int i = 2; i + 1 < pts.length; i += 2) {
            line("__p.lineTo(" + floatLit(pts[i]) + ", " + floatLit(pts[i + 1]) + ");");
        }
        if (pl.isClosed()) line("__p.closePath();");
        emitFillAndStroke(style, anims);
    }

    private void emitPath(SVGPath path, SVGStyle style, List<SVGAnimation> anims) {
        if (path.getCommands() == null || path.getCommands().isEmpty()) return;
        line("__p = new GeneralPath();");
        float curX = 0, curY = 0;
        for (PathCommand pc : path.getCommands()) {
            float[] a = pc.getArgs();
            switch (pc.getType()) {
                case MOVE:
                    line("__p.moveTo(" + floatLit(a[0]) + ", " + floatLit(a[1]) + ");");
                    curX = a[0]; curY = a[1];
                    break;
                case LINE:
                    line("__p.lineTo(" + floatLit(a[0]) + ", " + floatLit(a[1]) + ");");
                    curX = a[0]; curY = a[1];
                    break;
                case CUBIC:
                    line("__p.curveTo(" + floatLit(a[0]) + ", " + floatLit(a[1]) + ", "
                            + floatLit(a[2]) + ", " + floatLit(a[3]) + ", "
                            + floatLit(a[4]) + ", " + floatLit(a[5]) + ");");
                    curX = a[4]; curY = a[5];
                    break;
                case QUAD:
                    line("__p.quadTo(" + floatLit(a[0]) + ", " + floatLit(a[1]) + ", "
                            + floatLit(a[2]) + ", " + floatLit(a[3]) + ");");
                    curX = a[2]; curY = a[3];
                    break;
                case ARC:
                    // args = curX, curY, rx, ry, xRot, largeArc, sweep, x, y
                    line("GeneratedSVGImage.svgArc(__p, "
                            + floatLit(a[0]) + ", " + floatLit(a[1]) + ", "
                            + floatLit(a[2]) + ", " + floatLit(a[3]) + ", "
                            + floatLit(a[4]) + ", " + (a[5] != 0f) + ", " + (a[6] != 0f) + ", "
                            + floatLit(a[7]) + ", " + floatLit(a[8]) + ");");
                    curX = a[7]; curY = a[8];
                    break;
                case CLOSE:
                    line("__p.closePath();");
                    break;
            }
        }
        emitFillAndStroke(style, anims);
    }

    private void emitText(SVGText text, SVGStyle style, List<SVGAnimation> anims) {
        if (text.getContent() == null || text.getContent().isEmpty()) {
            return;
        }
        SVGPaint fill = style.getFill() != null ? style.getFill() : SVGPaint.BLACK;
        if (fill.isNone()) {
            return;
        }
        AnimatedFloat fillOpacity = animFloat("fill-opacity",
                style.getFillOpacity() == null ? 1f : style.getFillOpacity(), anims);
        AnimatedFloat elementOpacity = animFloat("opacity",
                style.getOpacity() == null ? 1f : style.getOpacity(), anims);

        float size = text.getFontSize() > 0 ? text.getFontSize() : 12f;
        int styleConst = (text.isBold() ? 1 : 0) | (text.isItalic() ? 2 : 0);
        // Font.STYLE_PLAIN = 0, STYLE_BOLD = 1, STYLE_ITALIC = 2

        line("{");
        indent++;
        line("Font __font = Font.getDefaultFont().derive(" + floatLit(size) + ", " + styleConst + ");");
        line("Font __oldFont = g.getFont();");
        line("g.setFont(__font);");
        emitPaintSet(fill, fillOpacity, elementOpacity);
        String content = "\"" + escapeJavaString(text.getContent()) + "\"";
        switch (text.getAnchor()) {
            case MIDDLE:
                line("int __tx = (int)" + floatLit(text.getX()) + " - __font.stringWidth(" + content + ") / 2;");
                break;
            case END:
                line("int __tx = (int)" + floatLit(text.getX()) + " - __font.stringWidth(" + content + ");");
                break;
            case START:
            default:
                line("int __tx = (int)" + floatLit(text.getX()) + ";");
                break;
        }
        line("g.drawStringBaseline(" + content + ", __tx, (int)" + floatLit(text.getY()) + ");");
        line("g.setFont(__oldFont);");
        indent--;
        line("}");
    }

    private static String escapeJavaString(String s) {
        StringBuilder out = new StringBuilder(s.length() + 4);
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '\\': out.append("\\\\"); break;
                case '"':  out.append("\\\""); break;
                case '\n': out.append("\\n"); break;
                case '\r': out.append("\\r"); break;
                case '\t': out.append("\\t"); break;
                default:
                    if (c < 0x20 || c > 0x7E) {
                        out.append(String.format("\\u%04X", (int) c));
                    } else {
                        out.append(c);
                    }
            }
        }
        return out.toString();
    }

    // ---- fill / stroke -----------------------------------------------------

    private void emitFillAndStroke(SVGStyle style, List<SVGAnimation> anims) {
        SVGPaint fill = style.getFill();
        SVGPaint stroke = style.getStroke();
        // default: fill black unless explicitly set
        if (fill == null) fill = SVGPaint.BLACK;
        // Element opacity is animatable (`<animate attributeName="opacity"/>`)
        // and applies to both fill and stroke; resolve it once.
        AnimatedFloat elementOpacity = animFloat("opacity",
                style.getOpacity() == null ? 1f : style.getOpacity(), anims);

        if (!fill.isNone()) {
            AnimatedFloat fillOpacity = animFloat("fill-opacity",
                    style.getFillOpacity() == null ? 1f : style.getFillOpacity(), anims);
            if (fill.isReference()) {
                emitGradientFill(fill, fillOpacity, elementOpacity);
            } else {
                emitPaintSet(fill, fillOpacity, elementOpacity);
                line("g.fillShape(__p);");
            }
        }
        if (stroke != null && !stroke.isNone()) {
            Float sw = style.getStrokeWidth();
            float widthVal = sw == null ? 1f : sw;
            int cap = style.getStrokeLineCap() == null ? SVGStyle.LINECAP_BUTT : style.getStrokeLineCap();
            int join = style.getStrokeLineJoin() == null ? SVGStyle.LINEJOIN_MITER : style.getStrokeLineJoin();
            float miter = style.getStrokeMiterLimit() == null ? 4f : style.getStrokeMiterLimit();
            emitPaintSet(stroke, animFloat("stroke-opacity",
                    style.getStrokeOpacity() == null ? 1f : style.getStrokeOpacity(), anims),
                    elementOpacity);
            line("__s = new Stroke(" + floatLit(widthVal)
                    + ", " + capConst(cap) + ", " + joinConst(join)
                    + ", " + floatLit(miter) + ");");
            line("g.drawShape(__p, __s);");
        }
    }

    private void emitPaintSet(SVGPaint paint, AnimatedFloat opacity, AnimatedFloat elementOpacity) {
        // element opacity multiplies attribute opacity (both animatable)
        String alphaExpr = alphaExpression(opacity, elementOpacity, 0xFF);
        if (paint.isReference()) {
            // Gradient paths are handled by emitGradientFill; this is for the
            // solid-color stroke path or the radial-fallback case.
            SVGNode def = doc.getDefinitions().get(paint.getReference());
            int color = 0xFF000000;
            if (def instanceof SVGRadialGradient) {
                SVGRadialGradient g = (SVGRadialGradient) def;
                if (!g.getStops().isEmpty()) {
                    color = g.getStops().get(0).getColor();
                }
            }
            line("g.setColor(0x" + hex(color & 0xFFFFFF) + ");");
            line("g.setAlpha(" + alphaExpr + ");");
            return;
        }
        int argb = paint.getColor();
        line("g.setColor(0x" + hex(argb & 0xFFFFFF) + ");");
        int colorAlpha = (argb >>> 24) & 0xFF;
        line("g.setAlpha(" + alphaExpression(opacity, elementOpacity, colorAlpha) + ");");
    }

    private static String alphaExpression(AnimatedFloat opacity, AnimatedFloat elementOpacity, int baseAlpha) {
        String mult = "Math.max(0f, Math.min(1f, " + opacity.expr + " * " + elementOpacity.expr + "))";
        if (baseAlpha >= 0xFF) {
            return "(int)(255f * " + mult + ")";
        }
        return "(int)(" + baseAlpha + " * " + mult + " + 0.5f)";
    }

    /// Gradient fills require shape clipping: CN1's [LinearGradientPaint#paint]
    /// fills its bounding rectangle, not the path -- a `fillShape(p)` after
    /// `setColor(paint)` ends up painting the gradient through any space inside
    /// the shape's bounding box on some ports. Push the path as the clip *and*
    /// call setColor(paint)+fillShape so platforms that respect the paint on
    /// fillShape (which produces a higher-quality result than clip+paint.paint)
    /// still get the proper outline, while the clip is a safety net for the
    /// ports that don't.
    private void emitGradientFill(SVGPaint fill, AnimatedFloat opacity, AnimatedFloat elementOpacity) {
        SVGNode def = doc.getDefinitions().get(fill.getReference());
        if (!(def instanceof SVGLinearGradient)) {
            // Radial / unresolved: fall back to first stop or black via the
            // solid-color path so we always render something.
            emitPaintSet(fill, opacity, elementOpacity);
            line("g.fillShape(__p);");
            return;
        }
        SVGLinearGradient lg = (SVGLinearGradient) def;
        SVGLinearGradient effective = lg;
        if (lg.getStops().isEmpty() && lg.getHref() != null) {
            SVGNode ref = doc.getDefinitions().get(lg.getHref());
            if (ref instanceof SVGLinearGradient) {
                effective = (SVGLinearGradient) ref;
            }
        }
        List<SVGGradientStop> stops = effective.getStops();
        if (stops.isEmpty()) {
            emitPaintSet(SVGPaint.BLACK, opacity, elementOpacity);
            line("g.fillShape(__p);");
            return;
        }

        StringBuilder fracs = new StringBuilder("new float[]{");
        StringBuilder cols = new StringBuilder("new int[]{");
        for (int i = 0; i < stops.size(); i++) {
            if (i > 0) { fracs.append(", "); cols.append(", "); }
            float off = Math.max(0f, Math.min(1f, stops.get(i).getOffset()));
            int color = stops.get(i).getColor() & 0xFFFFFF;
            int sAlpha = Math.round(255f * stops.get(i).getOpacity());
            fracs.append(floatLit(off));
            cols.append("0x").append(Integer.toHexString((sAlpha << 24) | color).toUpperCase(Locale.ROOT));
        }
        fracs.append("}");
        cols.append("}");

        line("{");
        indent++;
        line("float[] __b = new float[4];");
        line("__p.getBounds2D(__b);");
        line("float __bx = __b[0], __by = __b[1];");
        line("float __bw = __b[2], __bh = __b[3];");
        String startX, startY, endX, endY;
        if (lg.isUserSpace()) {
            startX = floatLit(lg.getX1());
            startY = floatLit(lg.getY1());
            endX = floatLit(lg.getX2());
            endY = floatLit(lg.getY2());
        } else {
            startX = "__bx + " + floatLit(lg.getX1()) + " * __bw";
            startY = "__by + " + floatLit(lg.getY1()) + " * __bh";
            endX = "__bx + " + floatLit(lg.getX2()) + " * __bw";
            endY = "__by + " + floatLit(lg.getY2()) + " * __bh";
        }
        line("LinearGradientPaint __paint = new LinearGradientPaint("
                + startX + ", " + startY + ", " + endX + ", " + endY + ", "
                + fracs + ", " + cols + ", "
                + "MultipleGradientPaint.CycleMethod.NO_CYCLE, "
                + "MultipleGradientPaint.ColorSpaceType.SRGB, "
                + "Transform.makeIdentity());");
        line("g.setAlpha(" + alphaExpression(opacity, elementOpacity, 0xFF) + ");");
        line("g.pushClip();");
        line("try {");
        indent++;
        line("g.setClip(__p);");
        line("__paint.paint(g, __bx, __by, __bw, __bh);");
        indent--;
        line("} finally {");
        indent++;
        line("g.popClip();");
        indent--;
        line("}");
        indent--;
        line("}");
    }

    // ---- transforms --------------------------------------------------------

    private void emitApplyMatrix(String varName, SVGTransform t) {
        // Emit as a setAffine on a fresh transform then concatenate.
        // Simpler: emit translate + multiply by matrix using direct field writes.
        line(varName + ".concatenate(Transform.makeAffine("
                + floatLit(t.a) + ", " + floatLit(t.b) + ", "
                + floatLit(t.c) + ", " + floatLit(t.d) + ", "
                + floatLit(t.e) + ", " + floatLit(t.f) + "));");
    }

    private void emitApplyAnimatedTransform(String varName, SVGAnimation a) {
        SVGAnimation.TransformType type = a.getTransformType();
        String pExpr = "GeneratedSVGImage.progress(__t, " + a.getBeginMs() + "L, "
                + a.getDurMs() + "L, " + a.getRepeatCount() + ", " + a.isFreeze() + ")";
        // values | from/to
        float[] from = parseFloatList(a.getFrom());
        float[] to = parseFloatList(a.getTo());
        List<String> vals = a.getValues();
        if (vals != null && vals.size() >= 2) {
            from = parseFloatList(vals.get(0));
            to = parseFloatList(vals.get(vals.size() - 1));
        }
        if (from == null) from = new float[]{0f};
        if (to == null) to = from;

        switch (type) {
            case TRANSLATE: {
                float fx = from.length > 0 ? from[0] : 0f;
                float fy = from.length > 1 ? from[1] : 0f;
                float tx = to.length > 0 ? to[0] : 0f;
                float ty = to.length > 1 ? to[1] : 0f;
                line(varName + ".translate("
                        + "GeneratedSVGImage.lerp(" + floatLit(fx) + ", " + floatLit(tx) + ", " + pExpr + "), "
                        + "GeneratedSVGImage.lerp(" + floatLit(fy) + ", " + floatLit(ty) + ", " + pExpr + "));");
                break;
            }
            case SCALE: {
                float fx = from.length > 0 ? from[0] : 1f;
                float fy = from.length > 1 ? from[1] : fx;
                float tx = to.length > 0 ? to[0] : 1f;
                float ty = to.length > 1 ? to[1] : tx;
                line(varName + ".scale("
                        + "GeneratedSVGImage.lerp(" + floatLit(fx) + ", " + floatLit(tx) + ", " + pExpr + "), "
                        + "GeneratedSVGImage.lerp(" + floatLit(fy) + ", " + floatLit(ty) + ", " + pExpr + "));");
                break;
            }
            case ROTATE: {
                float fAng = from.length > 0 ? from[0] : 0f;
                float fCx  = from.length > 1 ? from[1] : 0f;
                float fCy  = from.length > 2 ? from[2] : 0f;
                float tAng = to.length > 0 ? to[0] : 0f;
                float tCx  = to.length > 1 ? to[1] : fCx;
                float tCy  = to.length > 2 ? to[2] : fCy;
                line(varName + ".rotate("
                        + "(float) Math.toRadians(GeneratedSVGImage.lerp("
                        + floatLit(fAng) + ", " + floatLit(tAng) + ", " + pExpr + ")), "
                        + "GeneratedSVGImage.lerp(" + floatLit(fCx) + ", " + floatLit(tCx) + ", " + pExpr + "), "
                        + "GeneratedSVGImage.lerp(" + floatLit(fCy) + ", " + floatLit(tCy) + ", " + pExpr + "));");
                break;
            }
            case SKEW_X:
            case SKEW_Y:
                // skewing via Transform isn't a primitive op; bake into matrix concatenation
                break;
        }
    }

    // ---- animated attribute resolution -------------------------------------

    /** Look for an `<animate>` on this attribute and return either a constant
     *  or an expression that interpolates the value at runtime. */
    private AnimatedFloat animFloat(String attr, float fallback, List<SVGAnimation> anims) {
        if (anims != null) {
            for (SVGAnimation a : anims) {
                if (a.getKind() == SVGAnimation.Kind.ANIMATE
                        && attr.equals(a.getAttributeName())) {
                    float from = parseSingleFloat(a.getFrom(), fallback);
                    float to = parseSingleFloat(a.getTo(), from);
                    List<String> vals = a.getValues();
                    if (vals != null && vals.size() >= 2) {
                        from = parseSingleFloat(vals.get(0), from);
                        to = parseSingleFloat(vals.get(vals.size() - 1), to);
                    }
                    String pExpr = "GeneratedSVGImage.progress(__t, " + a.getBeginMs() + "L, "
                            + a.getDurMs() + "L, " + a.getRepeatCount() + ", " + a.isFreeze() + ")";
                    return new AnimatedFloat("GeneratedSVGImage.lerp("
                            + floatLit(from) + ", " + floatLit(to) + ", " + pExpr + ")");
                }
                if (a.getKind() == SVGAnimation.Kind.SET
                        && attr.equals(a.getAttributeName())) {
                    float to = parseSingleFloat(a.getTo(), fallback);
                    String pExpr = "(__t >= " + a.getBeginMs() + "L)";
                    return new AnimatedFloat("(" + pExpr + " ? " + floatLit(to) + " : "
                            + floatLit(fallback) + ")");
                }
            }
        }
        return new AnimatedFloat(floatLit(fallback));
    }

    private boolean hasTransformAnimation(List<SVGAnimation> anims) {
        if (anims == null) return false;
        for (SVGAnimation a : anims) {
            if (a.getKind() == SVGAnimation.Kind.ANIMATE_TRANSFORM) return true;
        }
        return false;
    }

    private SVGStyle mergedStyle(SVGNode n, SVGStyle parent) {
        SVGStyle s = n.getStyle();
        if (s == null) {
            SVGStyle empty = new SVGStyle();
            return empty.inherit(parent);
        }
        return s.inherit(parent);
    }

    private boolean containsAnimation(SVGGroup g) {
        if (!g.getAnimations().isEmpty()) return true;
        for (SVGNode c : g.getChildren()) {
            if (!c.getAnimations().isEmpty()) return true;
            if (c instanceof SVGGroup && containsAnimation((SVGGroup) c)) return true;
        }
        return false;
    }

    // ---- helpers -----------------------------------------------------------

    private static final class AnimatedFloat {
        final String expr;
        AnimatedFloat(String expr) { this.expr = expr; }
    }

    private static float[] parseFloatList(String s) {
        if (s == null) return null;
        NumberParser np = new NumberParser(s);
        java.util.ArrayList<Float> list = new java.util.ArrayList<Float>();
        while (np.hasMore()) {
            try { list.add(np.nextFloat()); } catch (RuntimeException e) { break; }
        }
        if (list.isEmpty()) return null;
        float[] r = new float[list.size()];
        for (int i = 0; i < r.length; i++) r[i] = list.get(i);
        return r;
    }

    private static float parseSingleFloat(String s, float fallback) {
        if (s == null) return fallback;
        try { return NumberParser.parseFloat(s); } catch (RuntimeException e) { return fallback; }
    }

    private static String floatLit(float f) {
        if (Float.isNaN(f) || Float.isInfinite(f)) f = 0f;
        // f suffix to make Java treat it as float
        return f + "f";
    }

    private static String intLit(int i) { return Integer.toString(i); }

    private static String hex(int v) {
        return Integer.toHexString(v & 0xFFFFFF).toUpperCase(Locale.ROOT);
    }

    private static String plus(String a, String b) {
        return "(" + a + " + " + b + ")";
    }

    private static String capConst(int cap) {
        switch (cap) {
            case SVGStyle.LINECAP_ROUND: return "Stroke.CAP_ROUND";
            case SVGStyle.LINECAP_SQUARE: return "Stroke.CAP_SQUARE";
            default: return "Stroke.CAP_BUTT";
        }
    }

    private static String joinConst(int join) {
        switch (join) {
            case SVGStyle.LINEJOIN_ROUND: return "Stroke.JOIN_ROUND";
            case SVGStyle.LINEJOIN_BEVEL: return "Stroke.JOIN_BEVEL";
            default: return "Stroke.JOIN_MITER";
        }
    }

    private void line(String s) {
        for (int i = 0; i < indent; i++) body.append("    ");
        body.append(s).append("\n");
    }
}
