/*
 * Copyright (c) 2026, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 */

// Direct3D 11 backend for the portable 3D API (com.codename1.gpu) on the native
// Windows port. Implements the WindowsNative.gl3d* bridge declared in
// WindowsNative.java. The render model is offscreen: the context renders one
// frame into an off-screen render target and gl3dCaptureFrame reads it back as a
// PNG so the lightweight PeerComponent can draw it (the port's "peer image"
// model). Shaders arrive as HLSL strings generated by HlslShaderGenerator and
// are compiled here with D3DCompile and cached as pipelines.
#include "cn1_windows.h"

#include <d3d11.h>
#include <d3dcompiler.h>
#include <wincodec.h>
#include <stdlib.h>
#include <string.h>

#pragma comment(lib, "d3d11.lib")
#pragma comment(lib, "d3dcompiler.lib")
#pragma comment(lib, "dxgi.lib")
#pragma comment(lib, "windowscodecs.lib")

namespace {

struct CN1D3DTexture {
    ID3D11Texture2D* tex;
    ID3D11ShaderResourceView* srv;
};

struct CN1D3DPipeline {
    ID3D11VertexShader* vs;
    ID3D11PixelShader* ps;
    ID3D11InputLayout* layout;
    ID3D11BlendState* blend;
    ID3D11RasterizerState* raster;
    ID3D11DepthStencilState* depth;
};

struct CN1D3DContext {
    ID3D11Device* device;
    ID3D11DeviceContext* ctx;
    IWICImagingFactory* wic;
    ID3D11Texture2D* rtTex;
    ID3D11RenderTargetView* rtv;
    ID3D11Texture2D* dsTex;
    ID3D11DepthStencilView* dsv;
    int width;
    int height;
    ID3D11Buffer* cbuffer;
    // Cached samplers: [filterLinear][wrapRepeat].
    ID3D11SamplerState* samplers[2][2];
};

template <typename T> static void cn1Release(T*& p) {
    if (p) { p->Release(); p = NULL; }
}

static IWICImagingFactory* cn1D3DWicFactory(CN1D3DContext* c) {
    if (c->wic == NULL) {
        CoInitializeEx(NULL, COINIT_MULTITHREADED);
        CoCreateInstance(CLSID_WICImagingFactory, NULL, CLSCTX_INPROC_SERVER,
                IID_IWICImagingFactory, (void**) &c->wic);
    }
    return c->wic;
}

// Releases and clears the offscreen render target + depth buffer.
static void cn1D3DReleaseTargets(CN1D3DContext* c) {
    cn1Release(c->rtv);
    cn1Release(c->rtTex);
    cn1Release(c->dsv);
    cn1Release(c->dsTex);
}

static bool cn1D3DEnsureTargets(CN1D3DContext* c, int w, int h) {
    if (w <= 0 || h <= 0) {
        return false;
    }
    if (c->rtTex != NULL && c->width == w && c->height == h) {
        return true;
    }
    cn1D3DReleaseTargets(c);
    c->width = w;
    c->height = h;

    D3D11_TEXTURE2D_DESC rt;
    ZeroMemory(&rt, sizeof(rt));
    rt.Width = (UINT) w;
    rt.Height = (UINT) h;
    rt.MipLevels = 1;
    rt.ArraySize = 1;
    rt.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
    rt.SampleDesc.Count = 1;
    rt.Usage = D3D11_USAGE_DEFAULT;
    rt.BindFlags = D3D11_BIND_RENDER_TARGET | D3D11_BIND_SHADER_RESOURCE;
    if (FAILED(c->device->CreateTexture2D(&rt, NULL, &c->rtTex))) {
        return false;
    }
    if (FAILED(c->device->CreateRenderTargetView(c->rtTex, NULL, &c->rtv))) {
        return false;
    }

    D3D11_TEXTURE2D_DESC ds;
    ZeroMemory(&ds, sizeof(ds));
    ds.Width = (UINT) w;
    ds.Height = (UINT) h;
    ds.MipLevels = 1;
    ds.ArraySize = 1;
    ds.Format = DXGI_FORMAT_D24_UNORM_S8_UINT;
    ds.SampleDesc.Count = 1;
    ds.Usage = D3D11_USAGE_DEFAULT;
    ds.BindFlags = D3D11_BIND_DEPTH_STENCIL;
    if (FAILED(c->device->CreateTexture2D(&ds, NULL, &c->dsTex))) {
        return false;
    }
    if (FAILED(c->device->CreateDepthStencilView(c->dsTex, NULL, &c->dsv))) {
        return false;
    }
    c->ctx->OMSetRenderTargets(1, &c->rtv, c->dsv);
    return true;
}

static ID3D11SamplerState* cn1D3DSampler(CN1D3DContext* c, int filterLinear, int wrapRepeat) {
    int fi = filterLinear ? 1 : 0;
    int wi = wrapRepeat ? 1 : 0;
    if (c->samplers[fi][wi] != NULL) {
        return c->samplers[fi][wi];
    }
    D3D11_SAMPLER_DESC sd;
    ZeroMemory(&sd, sizeof(sd));
    sd.Filter = filterLinear ? D3D11_FILTER_MIN_MAG_MIP_LINEAR : D3D11_FILTER_MIN_MAG_MIP_POINT;
    D3D11_TEXTURE_ADDRESS_MODE mode = wrapRepeat ? D3D11_TEXTURE_ADDRESS_WRAP : D3D11_TEXTURE_ADDRESS_CLAMP;
    sd.AddressU = mode;
    sd.AddressV = mode;
    sd.AddressW = mode;
    sd.MaxLOD = D3D11_FLOAT32_MAX;
    c->device->CreateSamplerState(&sd, &c->samplers[fi][wi]);
    return c->samplers[fi][wi];
}

static const char* cn1D3DStringToUtf8(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT str) {
    // stringToUTF8 is the ParparVM helper used elsewhere in the port; it returns
    // a UTF-8 C string for the flagged Java string.
    return stringToUTF8(threadStateData, str);
}

// Copies the offscreen render target to a CPU-readable staging texture and wraps
// its BGRA pixels in a WIC bitmap (caller releases it). Returns NULL on failure.
static IWICBitmap* cn1D3DCaptureWicBitmap(CN1D3DContext* c) {
    if (!c || !c->rtTex || c->width <= 0 || c->height <= 0) {
        return NULL;
    }
    int w = c->width;
    int h = c->height;
    D3D11_TEXTURE2D_DESC sd;
    ZeroMemory(&sd, sizeof(sd));
    sd.Width = (UINT) w;
    sd.Height = (UINT) h;
    sd.MipLevels = 1;
    sd.ArraySize = 1;
    sd.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
    sd.SampleDesc.Count = 1;
    sd.Usage = D3D11_USAGE_STAGING;
    sd.CPUAccessFlags = D3D11_CPU_ACCESS_READ;
    ID3D11Texture2D* staging = NULL;
    if (FAILED(c->device->CreateTexture2D(&sd, NULL, &staging))) {
        return NULL;
    }
    c->ctx->CopyResource(staging, c->rtTex);
    D3D11_MAPPED_SUBRESOURCE mapped;
    if (FAILED(c->ctx->Map(staging, 0, D3D11_MAP_READ, 0, &mapped))) {
        staging->Release();
        return NULL;
    }
    size_t pixelsLen = (size_t) w * h * 4;
    unsigned char* pixels = (unsigned char*) malloc(pixelsLen);
    if (!pixels) {
        c->ctx->Unmap(staging, 0);
        staging->Release();
        return NULL;
    }
    for (int row = 0; row < h; row++) {
        memcpy(pixels + (size_t) row * w * 4,
                (unsigned char*) mapped.pData + (size_t) row * mapped.RowPitch,
                (size_t) w * 4);
    }
    c->ctx->Unmap(staging, 0);
    staging->Release();

    IWICImagingFactory* wic = cn1D3DWicFactory(c);
    if (!wic) {
        free(pixels);
        return NULL;
    }
    IWICBitmap* bitmap = NULL;
    // WIC copies the pixel buffer, so the local buffer can be freed right after.
    HRESULT hr = wic->CreateBitmapFromMemory((UINT) w, (UINT) h, GUID_WICPixelFormat32bppBGRA,
            (UINT) (w * 4), (UINT) pixelsLen, pixels, &bitmap);
    free(pixels);
    if (FAILED(hr)) {
        return NULL;
    }
    return bitmap;
}

} // namespace

// The buffer/texture creation natives do not receive the context handle (mirroring
// the iOS Metal bridge), so the device + immediate context are cached
// process-wide on context creation. A native Windows app drives a single
// RenderView/GPU context at a time.
static ID3D11Device* g_cn1D3DDevice = NULL;
static ID3D11DeviceContext* g_cn1D3DContext = NULL;
ID3D11Device* cn1D3DGlobalDevice() { return g_cn1D3DDevice; }
ID3D11DeviceContext* cn1D3DGlobalContext() { return g_cn1D3DContext; }

extern "C" {

JAVA_LONG com_codename1_impl_windows_WindowsNative_gl3dCreateContext___R_long(CODENAME_ONE_THREAD_STATE) {
    CN1D3DContext* c = new CN1D3DContext();
    ZeroMemory(c, sizeof(CN1D3DContext));
    D3D_FEATURE_LEVEL levels[] = { D3D_FEATURE_LEVEL_11_0, D3D_FEATURE_LEVEL_10_1, D3D_FEATURE_LEVEL_10_0 };
    UINT flags = 0;
    HRESULT hr = D3D11CreateDevice(NULL, D3D_DRIVER_TYPE_HARDWARE, NULL, flags,
            levels, 3, D3D11_SDK_VERSION, &c->device, NULL, &c->ctx);
    if (FAILED(hr)) {
        // Fall back to the software (WARP) rasterizer so headless / GPU-less hosts
        // still render rather than reporting unsupported.
        hr = D3D11CreateDevice(NULL, D3D_DRIVER_TYPE_WARP, NULL, flags,
                levels, 3, D3D11_SDK_VERSION, &c->device, NULL, &c->ctx);
    }
    if (FAILED(hr)) {
        delete c;
        return 0;
    }
    g_cn1D3DDevice = c->device;
    g_cn1D3DContext = c->ctx;
    return (JAVA_LONG) (intptr_t) c;
}

JAVA_VOID com_codename1_impl_windows_WindowsNative_gl3dDestroyContext___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG peer) {
    CN1D3DContext* c = (CN1D3DContext*) (intptr_t) peer;
    if (!c) return;
    cn1D3DReleaseTargets(c);
    for (int i = 0; i < 2; i++) {
        for (int j = 0; j < 2; j++) {
            cn1Release(c->samplers[i][j]);
        }
    }
    cn1Release(c->cbuffer);
    cn1Release(c->wic);
    if (g_cn1D3DContext == c->ctx) { g_cn1D3DContext = NULL; }
    if (g_cn1D3DDevice == c->device) { g_cn1D3DDevice = NULL; }
    cn1Release(c->ctx);
    cn1Release(c->device);
    delete c;
}

JAVA_VOID com_codename1_impl_windows_WindowsNative_gl3dBeginFrame___long_int_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG peer, JAVA_INT width, JAVA_INT height) {
    CN1D3DContext* c = (CN1D3DContext*) (intptr_t) peer;
    if (!c) return;
    if (cn1D3DEnsureTargets(c, width, height)) {
        c->ctx->OMSetRenderTargets(1, &c->rtv, c->dsv);
    }
}

JAVA_VOID com_codename1_impl_windows_WindowsNative_gl3dSetViewport___long_int_int_int_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG peer, JAVA_INT x, JAVA_INT y, JAVA_INT w, JAVA_INT h) {
    CN1D3DContext* c = (CN1D3DContext*) (intptr_t) peer;
    if (!c || !c->ctx) return;
    D3D11_VIEWPORT vp;
    vp.TopLeftX = (FLOAT) x;
    vp.TopLeftY = (FLOAT) y;
    vp.Width = (FLOAT) w;
    vp.Height = (FLOAT) h;
    vp.MinDepth = 0.0f;
    vp.MaxDepth = 1.0f;
    c->ctx->RSSetViewports(1, &vp);
}

JAVA_VOID com_codename1_impl_windows_WindowsNative_gl3dClear___long_int_boolean_boolean(CODENAME_ONE_THREAD_STATE, JAVA_LONG peer, JAVA_INT argb, JAVA_BOOLEAN clearColor, JAVA_BOOLEAN clearDepth) {
    CN1D3DContext* c = (CN1D3DContext*) (intptr_t) peer;
    if (!c || !c->ctx) return;
    if (clearColor && c->rtv) {
        float col[4];
        col[0] = ((argb >> 16) & 0xff) / 255.0f;
        col[1] = ((argb >> 8) & 0xff) / 255.0f;
        col[2] = (argb & 0xff) / 255.0f;
        col[3] = ((argb >> 24) & 0xff) / 255.0f;
        c->ctx->ClearRenderTargetView(c->rtv, col);
    }
    if (clearDepth && c->dsv) {
        c->ctx->ClearDepthStencilView(c->dsv, D3D11_CLEAR_DEPTH | D3D11_CLEAR_STENCIL, 1.0f, 0);
    }
}

JAVA_LONG com_codename1_impl_windows_WindowsNative_gl3dCreateFloatBuffer___float_1ARRAY_int_R_long(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT data, JAVA_INT floatCount) {
    ID3D11Device* dev = cn1D3DGlobalDevice();
    if (!dev || data == JAVA_NULL || floatCount <= 0) return 0;
    JAVA_ARRAY_FLOAT* src = (JAVA_ARRAY_FLOAT*) (*(JAVA_ARRAY) data).data;
    D3D11_BUFFER_DESC bd;
    ZeroMemory(&bd, sizeof(bd));
    bd.ByteWidth = (UINT) (floatCount * 4);
    bd.Usage = D3D11_USAGE_DEFAULT;
    bd.BindFlags = D3D11_BIND_VERTEX_BUFFER;
    D3D11_SUBRESOURCE_DATA init;
    ZeroMemory(&init, sizeof(init));
    init.pSysMem = src;
    ID3D11Buffer* buf = NULL;
    if (FAILED(dev->CreateBuffer(&bd, &init, &buf))) return 0;
    return (JAVA_LONG) (intptr_t) buf;
}

JAVA_VOID com_codename1_impl_windows_WindowsNative_gl3dUpdateFloatBuffer___long_float_1ARRAY_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG bufferPeer, JAVA_OBJECT data, JAVA_INT floatCount) {
    ID3D11Buffer* buf = (ID3D11Buffer*) (intptr_t) bufferPeer;
    ID3D11DeviceContext* ctx = cn1D3DGlobalContext();
    if (!buf || !ctx || data == JAVA_NULL) return;
    JAVA_ARRAY_FLOAT* src = (JAVA_ARRAY_FLOAT*) (*(JAVA_ARRAY) data).data;
    ctx->UpdateSubresource(buf, 0, NULL, src, 0, 0);
}

JAVA_LONG com_codename1_impl_windows_WindowsNative_gl3dCreateShortBuffer___short_1ARRAY_int_R_long(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT data, JAVA_INT indexCount) {
    ID3D11Device* dev = cn1D3DGlobalDevice();
    if (!dev || data == JAVA_NULL || indexCount <= 0) return 0;
    JAVA_ARRAY_SHORT* src = (JAVA_ARRAY_SHORT*) (*(JAVA_ARRAY) data).data;
    D3D11_BUFFER_DESC bd;
    ZeroMemory(&bd, sizeof(bd));
    bd.ByteWidth = (UINT) (indexCount * 2);
    bd.Usage = D3D11_USAGE_DEFAULT;
    bd.BindFlags = D3D11_BIND_INDEX_BUFFER;
    D3D11_SUBRESOURCE_DATA init;
    ZeroMemory(&init, sizeof(init));
    init.pSysMem = src;
    ID3D11Buffer* buf = NULL;
    if (FAILED(dev->CreateBuffer(&bd, &init, &buf))) return 0;
    return (JAVA_LONG) (intptr_t) buf;
}

JAVA_VOID com_codename1_impl_windows_WindowsNative_gl3dUpdateShortBuffer___long_short_1ARRAY_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG bufferPeer, JAVA_OBJECT data, JAVA_INT indexCount) {
    ID3D11Buffer* buf = (ID3D11Buffer*) (intptr_t) bufferPeer;
    ID3D11DeviceContext* ctx = cn1D3DGlobalContext();
    if (!buf || !ctx || data == JAVA_NULL) return;
    JAVA_ARRAY_SHORT* src = (JAVA_ARRAY_SHORT*) (*(JAVA_ARRAY) data).data;
    ctx->UpdateSubresource(buf, 0, NULL, src, 0, 0);
}

JAVA_LONG com_codename1_impl_windows_WindowsNative_gl3dCreateTexture___int_1ARRAY_int_int_R_long(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT argb, JAVA_INT width, JAVA_INT height) {
    ID3D11Device* dev = cn1D3DGlobalDevice();
    if (!dev || argb == JAVA_NULL || width <= 0 || height <= 0) return 0;
    JAVA_ARRAY_INT* px = (JAVA_ARRAY_INT*) (*(JAVA_ARRAY) argb).data;
    int count = width * height;
    // Convert packed ARGB (0xAARRGGBB) to RGBA byte order for DXGI_FORMAT_R8G8B8A8.
    unsigned char* rgba = (unsigned char*) malloc((size_t) count * 4);
    if (!rgba) return 0;
    for (int i = 0; i < count; i++) {
        int c = px[i];
        rgba[i * 4] = (unsigned char) ((c >> 16) & 0xff);
        rgba[i * 4 + 1] = (unsigned char) ((c >> 8) & 0xff);
        rgba[i * 4 + 2] = (unsigned char) (c & 0xff);
        rgba[i * 4 + 3] = (unsigned char) ((c >> 24) & 0xff);
    }
    D3D11_TEXTURE2D_DESC td;
    ZeroMemory(&td, sizeof(td));
    td.Width = (UINT) width;
    td.Height = (UINT) height;
    td.MipLevels = 1;
    td.ArraySize = 1;
    td.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
    td.SampleDesc.Count = 1;
    td.Usage = D3D11_USAGE_DEFAULT;
    td.BindFlags = D3D11_BIND_SHADER_RESOURCE;
    D3D11_SUBRESOURCE_DATA init;
    ZeroMemory(&init, sizeof(init));
    init.pSysMem = rgba;
    init.SysMemPitch = (UINT) (width * 4);
    ID3D11Texture2D* tex = NULL;
    HRESULT texHr = dev->CreateTexture2D(&td, &init, &tex);
    free(rgba);
    if (FAILED(texHr)) return 0;
    ID3D11ShaderResourceView* srv = NULL;
    if (FAILED(dev->CreateShaderResourceView(tex, NULL, &srv))) {
        tex->Release();
        return 0;
    }
    CN1D3DTexture* t = new CN1D3DTexture();
    t->tex = tex;
    t->srv = srv;
    return (JAVA_LONG) (intptr_t) t;
}

JAVA_VOID com_codename1_impl_windows_WindowsNative_gl3dDisposeBuffer___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG bufferPeer) {
    ID3D11Buffer* buf = (ID3D11Buffer*) (intptr_t) bufferPeer;
    if (buf) buf->Release();
}

JAVA_VOID com_codename1_impl_windows_WindowsNative_gl3dDisposeTexture___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG texturePeer) {
    CN1D3DTexture* t = (CN1D3DTexture*) (intptr_t) texturePeer;
    if (!t) return;
    cn1Release(t->srv);
    cn1Release(t->tex);
    delete t;
}

JAVA_VOID com_codename1_impl_windows_WindowsNative_gl3dDisposePipeline___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG pipelinePeer) {
    CN1D3DPipeline* p = (CN1D3DPipeline*) (intptr_t) pipelinePeer;
    if (!p) return;
    cn1Release(p->vs);
    cn1Release(p->ps);
    cn1Release(p->layout);
    cn1Release(p->blend);
    cn1Release(p->raster);
    cn1Release(p->depth);
    delete p;
}

JAVA_LONG com_codename1_impl_windows_WindowsNative_gl3dGetOrCreatePipeline___long_java_lang_String_java_lang_String_int_int_int_int_R_long(
        CODENAME_ONE_THREAD_STATE, JAVA_LONG peer, JAVA_OBJECT key, JAVA_OBJECT hlsl,
        JAVA_INT blendMode, JAVA_INT cullMode, JAVA_INT depthTest, JAVA_INT depthWrite) {
    CN1D3DContext* c = (CN1D3DContext*) (intptr_t) peer;
    if (!c || !c->device) return 0;
    const char* src = cn1D3DStringToUtf8(threadStateData, hlsl);
    if (!src) return 0;
    SIZE_T srcLen = strlen(src);

    ID3DBlob* vsBlob = NULL;
    ID3DBlob* psBlob = NULL;
    ID3DBlob* err = NULL;
    UINT cflags = D3DCOMPILE_OPTIMIZATION_LEVEL1;
    if (FAILED(D3DCompile(src, srcLen, "cn1", NULL, NULL, "cn1_vertex_main", "vs_4_0", cflags, 0, &vsBlob, &err))) {
        cn1Release(err);
        return 0;
    }
    cn1Release(err);
    if (FAILED(D3DCompile(src, srcLen, "cn1", NULL, NULL, "cn1_fragment_main", "ps_4_0", cflags, 0, &psBlob, &err))) {
        cn1Release(err);
        cn1Release(vsBlob);
        return 0;
    }
    cn1Release(err);

    CN1D3DPipeline* p = new CN1D3DPipeline();
    ZeroMemory(p, sizeof(CN1D3DPipeline));
    if (FAILED(c->device->CreateVertexShader(vsBlob->GetBufferPointer(), vsBlob->GetBufferSize(), NULL, &p->vs)) ||
            FAILED(c->device->CreatePixelShader(psBlob->GetBufferPointer(), psBlob->GetBufferSize(), NULL, &p->ps))) {
        cn1Release(vsBlob); cn1Release(psBlob); delete p; return 0;
    }

    // Build the input layout by reflecting the vertex shader's input signature.
    // The generated VSInput uses POSITION (vec3), NORMAL (vec3) and TEXCOORD0
    // (vec2) in declaration order; tightly packed offsets accumulate.
    ID3D11ShaderReflection* refl = NULL;
    if (SUCCEEDED(D3DReflect(vsBlob->GetBufferPointer(), vsBlob->GetBufferSize(),
            __uuidof(ID3D11ShaderReflection), (void**) &refl))) {
        D3D11_SHADER_DESC sd;
        refl->GetDesc(&sd);
        // The generated VSInput has at most a handful of attributes (POSITION,
        // NORMAL, TEXCOORD0). A small fixed array avoids any C++ STL dependency
        // (the cross-compile toolchain's MSVC STL headers reject older clang).
        // pd.SemanticName points into the reflection object's string table, which
        // stays valid until refl->Release() below -- after CreateInputLayout -- so
        // the descriptors can reference it directly without copying.
        enum { MAX_INPUT_ELEMS = 16 };
        D3D11_INPUT_ELEMENT_DESC elems[MAX_INPUT_ELEMS];
        UINT elemCount = 0;
        UINT offset = 0;
        for (UINT i = 0; i < sd.InputParameters && elemCount < MAX_INPUT_ELEMS; i++) {
            D3D11_SIGNATURE_PARAMETER_DESC pd;
            refl->GetInputParameterDesc(i, &pd);
            D3D11_INPUT_ELEMENT_DESC e;
            ZeroMemory(&e, sizeof(e));
            e.SemanticName = pd.SemanticName;
            e.SemanticIndex = pd.SemanticIndex;
            e.InputSlot = 0;
            e.AlignedByteOffset = offset;
            e.InputSlotClass = D3D11_INPUT_PER_VERTEX_DATA;
            bool isTexcoord = pd.SemanticName != NULL && strcmp(pd.SemanticName, "TEXCOORD") == 0;
            if (isTexcoord) {
                e.Format = DXGI_FORMAT_R32G32_FLOAT;
                offset += 8;
            } else {
                e.Format = DXGI_FORMAT_R32G32B32_FLOAT;
                offset += 12;
            }
            elems[elemCount++] = e;
        }
        if (elemCount > 0) {
            c->device->CreateInputLayout(elems, elemCount,
                    vsBlob->GetBufferPointer(), vsBlob->GetBufferSize(), &p->layout);
        }
        refl->Release();
    }
    cn1Release(vsBlob);
    cn1Release(psBlob);

    // Blend state.
    D3D11_BLEND_DESC bd;
    ZeroMemory(&bd, sizeof(bd));
    D3D11_RENDER_TARGET_BLEND_DESC& rb = bd.RenderTarget[0];
    rb.RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
    if (blendMode == 0) {
        rb.BlendEnable = FALSE;
    } else {
        rb.BlendEnable = TRUE;
        rb.SrcBlend = D3D11_BLEND_SRC_ALPHA;
        rb.DestBlend = (blendMode == 2) ? D3D11_BLEND_ONE : D3D11_BLEND_INV_SRC_ALPHA;
        rb.BlendOp = D3D11_BLEND_OP_ADD;
        rb.SrcBlendAlpha = D3D11_BLEND_ONE;
        rb.DestBlendAlpha = D3D11_BLEND_INV_SRC_ALPHA;
        rb.BlendOpAlpha = D3D11_BLEND_OP_ADD;
    }
    c->device->CreateBlendState(&bd, &p->blend);

    // Rasterizer state. The HLSL flips Y, which reverses on-screen winding, so
    // front faces become clockwise (FrontCounterClockwise = FALSE) to match the
    // portable CCW-front convention of the other backends.
    D3D11_RASTERIZER_DESC rd;
    ZeroMemory(&rd, sizeof(rd));
    rd.FillMode = D3D11_FILL_SOLID;
    rd.FrontCounterClockwise = FALSE;
    if (cullMode == 0) {
        rd.CullMode = D3D11_CULL_NONE;
    } else if (cullMode == 2) {
        rd.CullMode = D3D11_CULL_FRONT;
    } else {
        rd.CullMode = D3D11_CULL_BACK;
    }
    rd.DepthClipEnable = TRUE;
    c->device->CreateRasterizerState(&rd, &p->raster);

    // Depth-stencil state.
    D3D11_DEPTH_STENCIL_DESC dd;
    ZeroMemory(&dd, sizeof(dd));
    dd.DepthEnable = depthTest ? TRUE : FALSE;
    dd.DepthWriteMask = depthWrite ? D3D11_DEPTH_WRITE_MASK_ALL : D3D11_DEPTH_WRITE_MASK_ZERO;
    dd.DepthFunc = D3D11_COMPARISON_LESS_EQUAL;
    c->device->CreateDepthStencilState(&dd, &p->depth);

    return (JAVA_LONG) (intptr_t) p;
}

static D3D11_PRIMITIVE_TOPOLOGY cn1D3DTopology(int primitive) {
    switch (primitive) {
        case 0: return D3D11_PRIMITIVE_TOPOLOGY_POINTLIST;
        case 1: return D3D11_PRIMITIVE_TOPOLOGY_LINELIST;
        case 2: return D3D11_PRIMITIVE_TOPOLOGY_LINESTRIP;
        case 4: return D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP;
        case 3:
        default: return D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST;
    }
}

// Binds the shared pipeline + per-draw state ahead of a draw call.
static void cn1D3DBind(CN1D3DContext* c, CN1D3DPipeline* p, ID3D11Buffer* vbo, int strideBytes,
        int primitive, JAVA_OBJECT uniforms, int uniformFloats,
        JAVA_LONG texturePeer, int texFilter, int texWrap) {
    ID3D11DeviceContext* ctx = c->ctx;

    // Upload uniforms into the constant buffer (recreate if size grows).
    UINT cbBytes = (UINT) (((uniformFloats * 4) + 15) & ~15);
    if (c->cbuffer == NULL) {
        D3D11_BUFFER_DESC cbd;
        ZeroMemory(&cbd, sizeof(cbd));
        cbd.ByteWidth = cbBytes;
        cbd.Usage = D3D11_USAGE_DYNAMIC;
        cbd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
        cbd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
        c->device->CreateBuffer(&cbd, NULL, &c->cbuffer);
    }
    if (c->cbuffer && uniforms != JAVA_NULL) {
        D3D11_MAPPED_SUBRESOURCE mapped;
        if (SUCCEEDED(ctx->Map(c->cbuffer, 0, D3D11_MAP_WRITE_DISCARD, 0, &mapped))) {
            JAVA_ARRAY_FLOAT* u = (JAVA_ARRAY_FLOAT*) (*(JAVA_ARRAY) uniforms).data;
            memcpy(mapped.pData, u, (size_t) uniformFloats * 4);
            ctx->Unmap(c->cbuffer, 0);
        }
    }

    UINT stride = (UINT) strideBytes;
    UINT offset = 0;
    ctx->IASetVertexBuffers(0, 1, &vbo, &stride, &offset);
    ctx->IASetInputLayout(p->layout);
    ctx->IASetPrimitiveTopology(cn1D3DTopology(primitive));
    ctx->VSSetShader(p->vs, NULL, 0);
    ctx->PSSetShader(p->ps, NULL, 0);
    ctx->VSSetConstantBuffers(0, 1, &c->cbuffer);
    ctx->PSSetConstantBuffers(0, 1, &c->cbuffer);

    CN1D3DTexture* tex = (CN1D3DTexture*) (intptr_t) texturePeer;
    if (tex && tex->srv) {
        ID3D11SamplerState* samp = cn1D3DSampler(c, texFilter, texWrap);
        ctx->PSSetShaderResources(0, 1, &tex->srv);
        ctx->PSSetSamplers(0, 1, &samp);
    }

    float blendFactor[4] = { 0, 0, 0, 0 };
    ctx->OMSetBlendState(p->blend, blendFactor, 0xffffffff);
    ctx->RSSetState(p->raster);
    ctx->OMSetDepthStencilState(p->depth, 0);
}

JAVA_VOID com_codename1_impl_windows_WindowsNative_gl3dDrawIndexed___long_long_long_int_long_int_int_float_1ARRAY_int_long_int_int(
        CODENAME_ONE_THREAD_STATE, JAVA_LONG peer, JAVA_LONG pipelinePeer, JAVA_LONG vboPeer, JAVA_INT strideBytes,
        JAVA_LONG iboPeer, JAVA_INT indexCount, JAVA_INT primitive, JAVA_OBJECT uniforms, JAVA_INT uniformFloats,
        JAVA_LONG texturePeer, JAVA_INT texFilter, JAVA_INT texWrap) {
    CN1D3DContext* c = (CN1D3DContext*) (intptr_t) peer;
    CN1D3DPipeline* p = (CN1D3DPipeline*) (intptr_t) pipelinePeer;
    ID3D11Buffer* vbo = (ID3D11Buffer*) (intptr_t) vboPeer;
    ID3D11Buffer* ibo = (ID3D11Buffer*) (intptr_t) iboPeer;
    if (!c || !c->ctx || !p || !vbo || !ibo) return;
    cn1D3DBind(c, p, vbo, strideBytes, primitive, uniforms, uniformFloats, texturePeer, texFilter, texWrap);
    c->ctx->IASetIndexBuffer(ibo, DXGI_FORMAT_R16_UINT, 0);
    c->ctx->DrawIndexed((UINT) indexCount, 0, 0);
}

JAVA_VOID com_codename1_impl_windows_WindowsNative_gl3dDrawArrays___long_long_long_int_int_int_float_1ARRAY_int_long_int_int(
        CODENAME_ONE_THREAD_STATE, JAVA_LONG peer, JAVA_LONG pipelinePeer, JAVA_LONG vboPeer, JAVA_INT strideBytes,
        JAVA_INT vertexCount, JAVA_INT primitive, JAVA_OBJECT uniforms, JAVA_INT uniformFloats,
        JAVA_LONG texturePeer, JAVA_INT texFilter, JAVA_INT texWrap) {
    CN1D3DContext* c = (CN1D3DContext*) (intptr_t) peer;
    CN1D3DPipeline* p = (CN1D3DPipeline*) (intptr_t) pipelinePeer;
    ID3D11Buffer* vbo = (ID3D11Buffer*) (intptr_t) vboPeer;
    if (!c || !c->ctx || !p || !vbo) return;
    cn1D3DBind(c, p, vbo, strideBytes, primitive, uniforms, uniformFloats, texturePeer, texFilter, texWrap);
    c->ctx->Draw((UINT) vertexCount, 0);
}

JAVA_OBJECT com_codename1_impl_windows_WindowsNative_gl3dCaptureFrame___long_R_byte_1ARRAY(CODENAME_ONE_THREAD_STATE, JAVA_LONG peer) {
    CN1D3DContext* c = (CN1D3DContext*) (intptr_t) peer;
    IWICImagingFactory* wic = cn1D3DWicFactory(c);
    IWICBitmap* bitmap = cn1D3DCaptureWicBitmap(c);
    if (!wic || !bitmap) {
        return JAVA_NULL;
    }

    JAVA_OBJECT result = JAVA_NULL;
    IStream* stream = NULL;
    IWICBitmapEncoder* encoder = NULL;
    IWICBitmapFrameEncode* frame = NULL;
    if (SUCCEEDED(CreateStreamOnHGlobal(NULL, TRUE, &stream)) &&
            SUCCEEDED(wic->CreateEncoder(GUID_ContainerFormatPng, NULL, &encoder)) &&
            SUCCEEDED(encoder->Initialize(stream, WICBitmapEncoderNoCache)) &&
            SUCCEEDED(encoder->CreateNewFrame(&frame, NULL)) &&
            SUCCEEDED(frame->Initialize(NULL)) &&
            SUCCEEDED(frame->WriteSource((IWICBitmapSource*) bitmap, NULL)) &&
            SUCCEEDED(frame->Commit()) &&
            SUCCEEDED(encoder->Commit())) {
        STATSTG stat;
        ZeroMemory(&stat, sizeof(stat));
        HGLOBAL hg = NULL;
        if (SUCCEEDED(stream->Stat(&stat, STATFLAG_NONAME)) &&
                SUCCEEDED(GetHGlobalFromStream(stream, &hg)) && hg != NULL) {
            SIZE_T size = (SIZE_T) stat.cbSize.QuadPart;
            void* mem = GlobalLock(hg);
            if (mem != NULL && size > 0) {
                result = allocArray(threadStateData, (int) size,
                        &class_array1__JAVA_BYTE, sizeof(JAVA_ARRAY_BYTE), 1);
                if (result != JAVA_NULL) {
                    memcpy((*(JAVA_ARRAY) result).data, mem, size);
                }
            }
            if (mem != NULL) {
                GlobalUnlock(hg);
            }
        }
    }
    if (frame) frame->Release();
    if (encoder) encoder->Release();
    if (stream) stream->Release();
    bitmap->Release();
    return result;
}

// Captures the current frame and writes it as a PNG file. A headless-screenshot
// convenience (and the hook the Direct3D render test uses to dump a frame).
JAVA_BOOLEAN com_codename1_impl_windows_WindowsNative_gl3dCaptureToFile___long_java_lang_String_R_boolean(
        CODENAME_ONE_THREAD_STATE, JAVA_LONG peer, JAVA_OBJECT path) {
    CN1D3DContext* c = (CN1D3DContext*) (intptr_t) peer;
    IWICImagingFactory* wic = cn1D3DWicFactory(c);
    IWICBitmap* bitmap = cn1D3DCaptureWicBitmap(c);
    if (!wic || !bitmap || path == JAVA_NULL) {
        if (bitmap) bitmap->Release();
        return JAVA_FALSE;
    }
    WCHAR* wpath = cn1WinJavaStringToWide(threadStateData, path, NULL);
    JAVA_BOOLEAN ok = JAVA_FALSE;
    IWICStream* stream = NULL;
    IWICBitmapEncoder* encoder = NULL;
    IWICBitmapFrameEncode* frame = NULL;
    if (wpath != NULL &&
            SUCCEEDED(wic->CreateStream(&stream)) &&
            SUCCEEDED(stream->InitializeFromFilename(wpath, GENERIC_WRITE)) &&
            SUCCEEDED(wic->CreateEncoder(GUID_ContainerFormatPng, NULL, &encoder)) &&
            SUCCEEDED(encoder->Initialize(stream, WICBitmapEncoderNoCache)) &&
            SUCCEEDED(encoder->CreateNewFrame(&frame, NULL)) &&
            SUCCEEDED(frame->Initialize(NULL)) &&
            SUCCEEDED(frame->WriteSource((IWICBitmapSource*) bitmap, NULL)) &&
            SUCCEEDED(frame->Commit()) &&
            SUCCEEDED(encoder->Commit())) {
        ok = JAVA_TRUE;
    }
    if (frame) frame->Release();
    if (encoder) encoder->Release();
    if (stream) stream->Release();
    bitmap->Release();
    if (wpath) free(wpath);
    return ok;
}

} // extern "C"
