#!/usr/bin/env bash
# Helpers for the Gradle integration tests (gradle-*.sh).
#
# The Gradle plugin under test is the one installed in the local Maven
# repository by `mvn install` -- the same place the Maven tests resolve the
# Maven plugin from. Set MAVEN_REPO_LOCAL when the reactor was installed with
# -Dmaven.repo.local; it defaults to ~/.m2/repository.
#
# Gradle runs on the project's own wrapper (generated by the plugin's template,
# pinned to the current Gradle), which needs JDK 17 or newer. GRADLE_JAVA_HOME,
# then JAVA17_HOME, then JAVA_HOME is used. CN1_TEST_GRADLE_VERSION swaps the
# wrapper's Gradle for another release.
#
# Usage:
#   source "$SCRIPTPATH/inc/gradle.sh"
#   use_local_plugin <project-dir>   # point the project at the local repository
#   run_gradle <project-dir> <gradle args...>
#   mvn_local <mvn args...>          # mvn with the same local repository

CN1_REPO="${MAVEN_REPO_LOCAL:-$HOME/.m2/repository}"
GRADLE_JDK="${GRADLE_JAVA_HOME:-${JAVA17_HOME:-$JAVA_HOME}}"

# Gradle itself needs JDK 17+. all.sh also runs on JDK 8-only machines (ant.yml),
# where these scripts have nothing to run on: they skip there, and
# gradle-smoke.yml, which provides the JDK, sets CN1_GRADLE_REQUIRED=1 so a
# missing one fails instead of reading as a pass.
GRADLE_JDK_MAJOR=$("$GRADLE_JDK/bin/java" -version 2>&1 | sed -n 's/.*version "\([0-9]*\)[."].*/\1/p' | head -1)
[ "$GRADLE_JDK_MAJOR" = "1" ] && GRADLE_JDK_MAJOR=8   # "1.8.0_..." is Java 8
if [ -z "$GRADLE_JDK_MAJOR" ] || [ "$GRADLE_JDK_MAJOR" -lt 17 ]; then
  if [ "${CN1_GRADLE_REQUIRED:-}" = "1" ]; then
    echo "FAIL: Gradle needs JDK 17 or newer; $GRADLE_JDK is ${GRADLE_JDK_MAJOR:-unknown}. Set GRADLE_JAVA_HOME." >&2
    exit 1
  fi
  echo "$(basename "$0"): skipped, no JDK 17 or newer (set GRADLE_JAVA_HOME or JAVA17_HOME)"
  exit 0
fi

mvn_local() {
  if [ -n "${MAVEN_REPO_LOCAL:-}" ]; then
    mvn -B -ntp "-Dmaven.repo.local=$MAVEN_REPO_LOCAL" "$@"
  else
    mvn -B -ntp "$@"
  fi
}

# Resolve the plugin, and the framework it builds against, from the local
# repository instead of repo.codenameone.com, which does not have this build.
use_local_plugin() {
  local dir="$1"
  python3 - "$dir/settings.gradle.kts" "$CN1_REPO" "$CN1_VERSION" <<'EOF'
import re, sys
path, repo, version = sys.argv[1], sys.argv[2], sys.argv[3]
text = open(path).read()
text = text.replace('maven("https://repo.codenameone.com/maven2")', 'maven(url = uri("%s"))' % repo)
text = re.sub(r'(id\("com\.codenameone"\) version ")[^"]*(")', r'\g<1>%s\g<2>' % version, text)
open(path, 'w').write(text)
EOF
  # CN1_TEST_GRADLE_VERSION runs the project on another Gradle than the one the
  # template's wrapper pins -- CI uses it to hold the plugin to its documented
  # minimum (CodenameOnePlugin.MINIMUM_GRADLE).
  if [ -n "${CN1_TEST_GRADLE_VERSION:-}" ] && [ -f "$dir/gradle/wrapper/gradle-wrapper.properties" ]; then
    sed -i.bak "s#^distributionUrl=.*#distributionUrl=https\\://services.gradle.org/distributions/gradle-$CN1_TEST_GRADLE_VERSION-bin.zip#" \
      "$dir/gradle/wrapper/gradle-wrapper.properties"
    rm -f "$dir/gradle/wrapper/gradle-wrapper.properties.bak"
  fi
  if ! grep -q "codename1.repository=" "$dir/gradle.properties" 2>/dev/null; then
    printf '\ncodename1.repository=%s\n' "$CN1_REPO" >> "$dir/gradle.properties"
  fi
}

run_gradle() {
  local dir="$1"
  shift
  # No build cache: the scripts assert on what the build did (a processor's
  # "generated 2 @RestController router" line, for one), and a re-run whose
  # inputs match the last one would restore those outputs without doing it.
  (cd "$dir" && JAVA_HOME="$GRADLE_JDK" ./gradlew --no-daemon --no-build-cache --stacktrace "$@")
}

# Fails the test, naming what was expected.
fail() {
  echo "FAIL: $*" >&2
  exit 1
}

# Asserts a zip holds an entry matching the extended regex.
assert_zip_has() {
  local zip="$1" pattern="$2"
  unzip -Z1 "$zip" | grep -Eq "$pattern" || fail "$zip has no entry matching $pattern"
}

# Asserts a zip holds no entry matching the extended regex.
assert_zip_lacks() {
  local zip="$1" pattern="$2"
  if unzip -Z1 "$zip" | grep -Eq "$pattern"; then
    fail "$zip unexpectedly has an entry matching $pattern: $(unzip -Z1 "$zip" | grep -E "$pattern" | head -3)"
  fi
}

# Generates a Maven application from the archetype and converts it to Gradle.
# The conversion is itself under test here (cn1:convert-to-gradle), and it is
# the one way to produce a Gradle project from the command line.
#   generate_gradle_app <name> <package>
generate_gradle_app() {
  local name="$1" pkg="$2"
  rm -rf "$name" "$name-gradle"
  mvn_local archetype:generate \
    -DarchetypeArtifactId=cn1app-archetype \
    -DarchetypeGroupId=com.codenameone \
    -DarchetypeVersion="$CN1_VERSION" \
    -DartifactId="$name" \
    -DgroupId="$pkg" \
    -Dpackage="$pkg" \
    -Dversion=1.0-SNAPSHOT \
    -DmainName="$name" \
    -DjavaVersion=17 \
    -DinteractiveMode=false
  (cd "$name" && mvn_local "com.codenameone:codenameone-maven-plugin:$CN1_VERSION:convert-to-gradle")
  use_local_plugin "$name-gradle"
}

# Starts a backend with the given task, waits for /healthz to answer, checks
# the template's /greet route answers through its injected Greeter service, then
# stops it, on the dev profile the template documents (in-memory SQLite).
# PORT overrides cn1.server.port, so parallel runs do not collide.
#   check_backend_healthz <project-dir> <task> <log>
check_backend_healthz() {
  local dir="$1" task="$2" log="$3"
  local port=$((18000 + RANDOM % 2000))
  (cd "$dir" && CN1_PROFILE=dev PORT=$port JAVA_HOME="$GRADLE_JDK" exec ./gradlew --no-daemon "$task") > "$log" 2>&1 &
  local pid=$!
  local body="" i
  for i in $(seq 1 180); do
    body=$(curl -fsS "http://127.0.0.1:$port/healthz" 2>/dev/null) && break
    kill -0 $pid 2>/dev/null || break
    sleep 1
  done
  local greeting=""
  [ -n "$body" ] && greeting=$(curl -fsS "http://127.0.0.1:$port/greet/gradle" 2>/dev/null || true)
  stop_tree $pid
  [ -n "$body" ] || { cat "$log"; fail "$task never answered /healthz on port $port"; }
  echo "   $task /healthz: $body"
  [ "$greeting" = "Hello, gradle" ] || { cat "$log"; fail "$task did not answer /greet through its injected service (got '$greeting')"; }
}

# Checks a packaged backend binary answers /healthz, and /greet through the
# Greeter service the build wired into it.
#   check_binary_healthz <binary> <working-dir> <log>
check_binary_healthz() {
  local bin="$1" dir="$2" log="$3"
  local port=$((20000 + RANDOM % 2000))
  (cd "$dir" && CN1_PROFILE=dev PORT=$port exec "$bin") > "$log" 2>&1 &
  local pid=$!
  local body="" i
  for i in $(seq 1 60); do
    body=$(curl -fsS "http://127.0.0.1:$port/healthz" 2>/dev/null) && break
    kill -0 $pid 2>/dev/null || break
    sleep 1
  done
  local greeting=""
  [ -n "$body" ] && greeting=$(curl -fsS "http://127.0.0.1:$port/greet/gradle" 2>/dev/null || true)
  stop_tree $pid
  [ -n "$body" ] || { cat "$log"; fail "$bin never answered /healthz on port $port"; }
  echo "   $(basename "$bin") /healthz: $body"
  [ "$greeting" = "Hello, gradle" ] || { cat "$log"; fail "$bin did not answer /greet through its injected service (got '$greeting')"; }
}

# Kills a process and its children (gradlew forks the backend JVM).
stop_tree() {
  local pid="$1" child
  for child in $(pgrep -P "$pid" 2>/dev/null); do
    stop_tree "$child"
  done
  kill "$pid" 2>/dev/null || true
  wait "$pid" 2>/dev/null || true
}
