codename1.android.keystore=
codename1.android.keystoreAlias=
codename1.android.keystorePassword=
codename1.arg.android.useAndroidX=true
codename1.arg.ios.newStorageLocation=true
codename1.arg.ios.uiscene=true
codename1.arg.java.version=17
codename1.cssTheme=false
codename1.displayName=CN1InputValidation
codename1.icon=icon.png
codename1.ios.appid=
codename1.ios.certificate=
codename1.ios.certificatePassword=
codename1.ios.debug.certificate=
codename1.ios.debug.certificatePassword=
codename1.ios.debug.provision=
codename1.ios.provision=
codename1.ios.release.certificate=
codename1.ios.release.certificatePassword=
codename1.ios.release.provision=
codename1.kotlin=false
codename1.languageLevel=5
codename1.mainName=InputValidationApp
codename1.packageName=com.codenameone.inputvalidation
codename1.secondaryTitle=CN1 Input Validation
codename1.vendor=CodenameOne
codename1.version=1.0
