/*
 * Copyright (c) 2026, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Codename One through http://www.codenameone.com/ if you
 * need additional information or have any questions.
 */

package com.codenameone.examples.hellocodenameone.tests;

/**
 * Cross-platform conformance for {@code java.lang.String.format} (issue #5482).
 *
 * <p>On JavaSE and Android this runs the platform's own {@code java.util.Formatter}. On
 * iOS, tvOS, watchOS, the native desktop targets and JavaScript it runs Codename One's
 * replacement {@code java.lang.String}, whose {@code format} used to be a native method
 * that aborted the process on iOS. Those are different code paths reached through
 * different toolchains -- the iOS app translates the core out of the bundled iOSPort.jar
 * rather than out of the reactor -- so the only way to know they agree is to assert the
 * same expectations on every device.</p>
 *
 * <p>Every expected value below was produced by a real Java SE
 * {@code java.util.Formatter} rather than written by hand, and the generator is checked
 * in at {@code scripts/hellocodenameone/tools/generate-string-format-cases.java}. The
 * table is byte-identical when generated on JDK 8, 11, 17, 21 and 25, so it pins
 * behaviour that does not drift with the JDK the suite happens to build against.</p>
 *
 * <p>Deliberately excluded, because they are not consistent across the runtimes this
 * suite covers: {@code %a} and {@code %t} (unimplemented on ParparVM), {@code %0$s}
 * (accepted before JDK 16, rejected from 16 on) and a pinned value for {@code %n} (the
 * JDK emits the platform line separator).</p>
 */
public class StringFormatTest extends BaseTest {

    /** Typed so {@code String.format(fmt, NULL_ARRAY)} passes a null varargs array. */
    private static final Object[] NULL_ARRAY = null;

    private interface FormatCall {
        String run();
    }

    private char decimalSeparator = '.';
    private char groupingSeparator = ',';
    private int checked;

    @Override
    public boolean runTest() {
        try {
            probeLocale();

// Generated by scripts/hellocodenameone/tools/generate-string-format-cases.java
// on Azul Systems, Inc. JDK 25 -- do not edit by hand.
            // ---- strings and characters ----
            check("s.plain", "hello", String.format("%s", "hello"));
            check("s.null", "[null]", String.format("[%s]", (Object) null));
            check("s.width", "[       abc]", String.format("[%10s]", "abc"));
            check("s.left", "[abc       ]", String.format("[%-10s]", "abc"));
            check("s.precision", "[abc]", String.format("[%.3s]", "abcdef"));
            check("s.widthPrecision", "[     abc]", String.format("[%8.3s]", "abcdef"));
            check("s.upper", "ABC", String.format("%S", "abc"));
            check("s.boxedInt", "42", String.format("%s", Integer.valueOf(42)));
            check("s.boxedLongMin", "-9223372036854775808", String.format("%s", Long.valueOf(-9223372036854775808L)));
            check("b.true", "true", String.format("%b", Boolean.valueOf(true)));
            check("b.false", "false", String.format("%b", Boolean.valueOf(false)));
            check("b.null", "false", String.format("%b", (Object) null));
            check("b.nonBoolean", "true", String.format("%b", "text"));
            check("b.upper", "TRUE", String.format("%B", Boolean.valueOf(true)));
            check("h.string", "17862", String.format("%h", "abc"));
            check("h.null", "null", String.format("%h", (Object) null));
            check("c.char", "x", String.format("%c", Character.valueOf('x')));
            check("c.upper", "X", String.format("%C", Character.valueOf('x')));
            check("c.codePoint", "A", String.format("%c", Integer.valueOf(65)));
            check("c.width", "[    x]", String.format("[%5c]", Character.valueOf('x')));
            check("c.null", "null", String.format("%c", (Object) null));
            check("literal.percent", "100%", String.format("100%%"));
            check("literal.mixed", "cn1-7-A%", String.format("%s-%d-%c%%", "cn1", Integer.valueOf(7), Character.valueOf('A')));
            check("index.explicit", "two one two", String.format("%2$s %1$s %2$s", "one", "two"));
            check("index.previous", "echo echo echo", String.format("%s %<s %<s", "echo"));

            // ---- integers ----
            check("d.zero", "0", String.format("%d", Integer.valueOf(0)));
            check("d.positive", "42", String.format("%d", Integer.valueOf(42)));
            check("d.negative", "-42", String.format("%d", Integer.valueOf(-42)));
            check("d.intMin", "-2147483648", String.format("%d", Integer.valueOf(-2147483648)));
            check("d.longMax", "9223372036854775807", String.format("%d", Long.valueOf(9223372036854775807L)));
            check("d.longMin", "-9223372036854775808", String.format("%d", Long.valueOf(-9223372036854775808L)));
            check("d.byte", "-7", String.format("%d", Byte.valueOf((byte) -7)));
            check("d.short", "-7", String.format("%d", Short.valueOf((short) -7)));
            check("d.width", "[      42]", String.format("[%8d]", Integer.valueOf(42)));
            check("d.left", "[42      ]", String.format("[%-8d]", Integer.valueOf(42)));
            check("d.zeroPad", "[00000042]", String.format("[%08d]", Integer.valueOf(42)));
            check("d.zeroPadNegative", "[-0000042]", String.format("[%08d]", Integer.valueOf(-42)));
            check("d.plus", "[+42]", String.format("[%+d]", Integer.valueOf(42)));
            check("d.plusNegative", "[-42]", String.format("[%+d]", Integer.valueOf(-42)));
            check("d.space", "[ 42]", String.format("[% d]", Integer.valueOf(42)));
            check("d.paren", "[(42)]", String.format("[%(d]", Integer.valueOf(-42)));
            check("d.grouped", "1,234,567", String.format("%,d", Integer.valueOf(1234567)));
            check("d.groupedExact", "1,000", String.format("%,d", Integer.valueOf(1000)));
            check("d.groupedNegative", "-1,234,567", String.format("%,d", Integer.valueOf(-1234567)));
            check("d.groupedParen", "(1,234,567)", String.format("%,(d", Integer.valueOf(-1234567)));
            check("d.groupedZeroPad", "[00000001,234]", String.format("[%,012d]", Integer.valueOf(1234)));
            check("x.small", "ff", String.format("%x", Integer.valueOf(255)));
            check("x.negativeInt", "ffffffff", String.format("%x", Integer.valueOf(-1)));
            check("x.negativeLong", "ffffffffffffffff", String.format("%x", Long.valueOf(-1L)));
            check("x.byte", "ff", String.format("%x", Byte.valueOf((byte) -1)));
            check("x.short", "ffff", String.format("%x", Short.valueOf((short) -1)));
            check("x.upper", "BEEF", String.format("%X", Integer.valueOf(48879)));
            check("x.alt", "0xff", String.format("%#x", Integer.valueOf(255)));
            check("x.altUpper", "0XFF", String.format("%#X", Integer.valueOf(255)));
            check("x.zeroPad", "[000000ff]", String.format("[%08x]", Integer.valueOf(255)));
            check("o.small", "10", String.format("%o", Integer.valueOf(8)));
            check("o.negativeInt", "37777777777", String.format("%o", Integer.valueOf(-1)));
            check("o.alt", "010", String.format("%#o", Integer.valueOf(8)));

            // ---- floating point ----
            check("f.zero", "0.000000", String.format("%f", Double.valueOf(0.0)));
            check("f.negativeZero", "-0.000000", String.format("%f", Double.valueOf(-0.0)));
            check("f.simple", "1.500000", String.format("%f", Double.valueOf(1.5)));
            check("f.negative", "-1.500000", String.format("%f", Double.valueOf(-1.5)));
            check("f.third", "0.333333", String.format("%f", Double.valueOf(0.3333333333333333)));
            check("f.large", "1000000000000000000000000000000.000000", String.format("%f", Double.valueOf(1.0E30)));
            check("f.tiny", "0.000000", String.format("%f", Double.valueOf(1.0E-10)));
            check("f.float", "1.500000", String.format("%f", Float.valueOf(1.5f)));
            check("f.floatImprecise", "1.100000", String.format("%f", Float.valueOf(1.1f)));
            check("f.nan", "NaN", String.format("%f", Double.valueOf(Double.NaN)));
            check("f.infinity", "Infinity", String.format("%f", Double.valueOf(Double.POSITIVE_INFINITY)));
            check("f.negativeInfinity", "-Infinity", String.format("%f", Double.valueOf(Double.NEGATIVE_INFINITY)));
            check("f.stats", "size=12 avg=0.667", String.format("size=%d avg=%.3f", Integer.valueOf(12), Double.valueOf(0.6666666666666666)));
            check("f.halfUp.zeroPointFive", "1", String.format("%.0f", Double.valueOf(0.5)));
            check("f.halfUp.twoPointFive", "3", String.format("%.0f", Double.valueOf(2.5)));
            check("f.halfUp.threePointFive", "4", String.format("%.0f", Double.valueOf(3.5)));
            check("f.halfUp.belowHalf", "0", String.format("%.0f", Double.valueOf(0.4)));
            check("f.halfUp.fifteenHundredths", "0.2", String.format("%.1f", Double.valueOf(0.15)));
            check("f.halfUp.oneOhOhFive", "1.01", String.format("%.2f", Double.valueOf(1.005)));
            check("f.carryToTen", "10.00", String.format("%.2f", Double.valueOf(9.999)));
            check("f.smallCarry", "0.01", String.format("%.2f", Double.valueOf(0.005)));
            check("f.belowPrecision", "0.00", String.format("%.2f", Double.valueOf(6.0E-4)));
            check("f.padBeyondShortest", "0.10000000000000000000", String.format("%.20f", Double.valueOf(0.1)));
            check("f.tenDecimalsOfThird", "0.3333333333", String.format("%.10f", Double.valueOf(0.3333333333333333)));
            check("f.fifteenDecimalsOfSeventh", "0.142857142857143", String.format("%.15f", Double.valueOf(0.14285714285714285)));
            check("f.width", "[      3.14]", String.format("[%10.2f]", Double.valueOf(3.14159)));
            check("f.left", "[3.14      ]", String.format("[%-10.2f]", Double.valueOf(3.14159)));
            check("f.zeroPad", "[0000003.14]", String.format("[%010.2f]", Double.valueOf(3.14159)));
            check("f.zeroPadNegative", "[-000003.14]", String.format("[%010.2f]", Double.valueOf(-3.14159)));
            check("f.plus", "[+3.14]", String.format("[%+.2f]", Double.valueOf(3.14159)));
            check("f.grouped", "1,234,567.89", String.format("%,.2f", Double.valueOf(1234567.891)));
            check("f.groupedNegative", "-1,234,567.89", String.format("%,.2f", Double.valueOf(-1234567.891)));
            check("f.alt", "3.", String.format("%#.0f", Double.valueOf(3.0)));
            check("e.zero", "0.000000e+00", String.format("%e", Double.valueOf(0.0)));
            check("e.simple", "1.234568e+04", String.format("%e", Double.valueOf(12345.6789)));
            check("e.negative", "-1.234568e+04", String.format("%e", Double.valueOf(-12345.6789)));
            check("e.tiny", "1.000000e-05", String.format("%e", Double.valueOf(1.0E-5)));
            check("e.huge", "1.230000e+300", String.format("%e", Double.valueOf(1.23E300)));
            check("e.precision2", "1.23e+04", String.format("%.2e", Double.valueOf(12345.6789)));
            check("e.precision0", "1e+04", String.format("%.0e", Double.valueOf(12345.6789)));
            check("e.upper", "1.234568E+04", String.format("%E", Double.valueOf(12345.6789)));
            check("e.carry", "1.00e+01", String.format("%.2e", Double.valueOf(9.999)));
            check("g.zero", "0.00000", String.format("%g", Double.valueOf(0.0)));
            check("g.lowBoundary", "0.000100000", String.format("%g", Double.valueOf(1.0E-4)));
            check("g.belowBoundary", "1.00000e-05", String.format("%g", Double.valueOf(1.0E-5)));
            check("g.highBoundary", "100000", String.format("%g", Double.valueOf(100000.0)));
            check("g.aboveBoundary", "1.23457e+08", String.format("%g", Double.valueOf(1.23456789E8)));
            check("g.precision3", "1.23e+03", String.format("%.3g", Double.valueOf(1234.5678)));
            check("g.upper", "1.00000E-05", String.format("%G", Double.valueOf(1.0E-5)));

            // ---- a null varargs array supplies a null per specifier ----
            check("nullArray.s", "[null]", String.format("[%s]", NULL_ARRAY));
            check("nullArray.twoArgs", "[null null]", String.format("[%s %s]", NULL_ARRAY));
            check("nullArray.d", "[null]", String.format("[%d]", NULL_ARRAY));
            check("nullArray.floatWidth", "[   nu]", String.format("[%5.2f]", NULL_ARRAY));
            check("nullArray.upper", "[NULL]", String.format("[%S]", NULL_ARRAY));

            // ---- malformed formats must raise the same exception everywhere ----
            checkThrows("bad.unknownConversion", "java.util.UnknownFormatConversionException", () -> String.format("%q", "x"));
            checkThrows("bad.trailingPercent", "java.util.UnknownFormatConversionException", () -> String.format("abc%"));
            checkThrows("bad.missingArgument", "java.util.MissingFormatArgumentException", () -> String.format("%s %s", "only"));
            checkThrows("bad.noArguments", "java.util.MissingFormatArgumentException", () -> String.format("%s"));
            checkThrows("bad.wrongTypeForD", "java.util.IllegalFormatConversionException", () -> String.format("%d", "text"));
            checkThrows("bad.wrongTypeForF", "java.util.IllegalFormatConversionException", () -> String.format("%f", "text"));
            checkThrows("bad.precisionOnD", "java.util.IllegalFormatPrecisionException", () -> String.format("%.2d", Integer.valueOf(1)));
            checkThrows("bad.emptyPrecision", "java.util.UnknownFormatConversionException", () -> String.format("%.s", "x"));
            checkThrows("bad.repeatedPrevious", "java.util.DuplicateFormatFlagsException", () -> String.format("%s %<<s", "a"));
            checkThrows("bad.repeatedMinus", "java.util.DuplicateFormatFlagsException", () -> String.format("%--5s", "a"));
            checkThrows("bad.groupingOnHex", "java.util.FormatFlagsConversionMismatchException", () -> String.format("%,x", Integer.valueOf(1)));
            checkThrows("bad.zeroPadOnString", "java.util.FormatFlagsConversionMismatchException", () -> String.format("%08s", "a"));

            checkLineSeparator();
            assertTrue(checked > 100, "expected the full conformance table to run, only " + checked + " cases did");
        } catch (Throwable t) {
            fail("String.format conformance failed: " + t);
            return false;
        }
        done();
        return true;
    }

    /**
     * JavaSE and Android format through the default locale, so a runner in a locale that
     * uses ',' as the decimal separator would disagree with the table for reasons that
     * have nothing to do with this test. Discover the separators instead of assuming, and
     * fail loudly rather than confusingly if the platform also localises the digits.
     */
    private void probeLocale() {
        String decimalProbe = String.format("%.1f", Double.valueOf(1.5));
        assertTrue(decimalProbe.length() == 3,
                "expected a d.d rendering from %.1f, got [" + decimalProbe + "]");
        decimalSeparator = decimalProbe.charAt(1);

        String groupingProbe = String.format("%,d", Integer.valueOf(1000));
        assertTrue(groupingProbe.length() == 5,
                "expected a d,ddd rendering from %,d, got [" + groupingProbe + "]");
        groupingSeparator = groupingProbe.charAt(1);

        assertEqual("1234567890", String.format("%d", Integer.valueOf(1234567890)),
                "platform formats integers with non-ASCII digits; the table cannot apply");
    }

    /**
     * {@code %n} is the platform line separator by specification, so it is "\r\n" on a
     * Windows JVM and "\n" everywhere else. Pin that it is a line separator rather than
     * pinning which one.
     */
    private void checkLineSeparator() {
        String value = String.format("a%nb");
        assertTrue("a\nb".equals(value) || "a\r\nb".equals(value),
                "%n should emit a line separator, got " + describe(value));
    }

    private void check(String label, String expected, String actual) {
        checked++;
        String localised = localise(expected);
        assertEqual(localised, actual,
                "String.format case '" + label + "' expected " + describe(localised)
                        + " but was " + describe(actual));
    }

    private void checkThrows(String label, String expectedType, FormatCall call) {
        checked++;
        String result;
        try {
            result = call.run();
        } catch (Throwable t) {
            // Every java.util format exception extends IllegalArgumentException. The
            // package is not pinned because a port may mangle class names; the specific
            // exception is, because picking the wrong one is the bug this catches.
            assertTrue(t instanceof IllegalArgumentException,
                    "String.format case '" + label + "' should raise an IllegalArgumentException, raised "
                            + t.getClass().getName());
            String simple = simpleName(expectedType);
            assertTrue(simpleName(t.getClass().getName()).equals(simple),
                    "String.format case '" + label + "' should raise " + simple
                            + ", raised " + t.getClass().getName());
            return;
        }
        fail("String.format case '" + label + "' should have raised " + simpleName(expectedType)
                + " but returned " + describe(result));
    }

    private static String simpleName(String className) {
        int dot = className.lastIndexOf('.');
        return dot < 0 ? className : className.substring(dot + 1);
    }

    /** Rewrites a canonical expectation into the separators this platform actually uses. */
    private String localise(String expected) {
        if (decimalSeparator == '.' && groupingSeparator == ',') {
            return expected;
        }
        StringBuilder sb = new StringBuilder(expected.length());
        for (int i = 0; i < expected.length(); i++) {
            char c = expected.charAt(i);
            if (c == '.') {
                sb.append(decimalSeparator);
            } else if (c == ',') {
                sb.append(groupingSeparator);
            } else {
                sb.append(c);
            }
        }
        return sb.toString();
    }

    private static String describe(String value) {
        if (value == null) {
            return "null";
        }
        StringBuilder sb = new StringBuilder("[");
        for (int i = 0; i < value.length(); i++) {
            char c = value.charAt(i);
            if (c == '\n') {
                sb.append("\\n");
            } else if (c == '\r') {
                sb.append("\\r");
            } else {
                sb.append(c);
            }
        }
        return sb.append("] len=").append(value.length()).toString();
    }

    @Override
    public boolean shouldTakeScreenshot() {
        return false;
    }
}
