/*
 * Copyright (c) 2012, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Codename One through http://www.codenameone.com/ if you
 * need additional information or have any questions.
 */
package com.codename1.flutter.widgets;

/**
 * Scroll physics that let the content be dragged past its edges against a rubber band, and
 * spring back when released — Flutter's {@code BouncingScrollPhysics}, and the iOS default.
 *
 * <p>The rubber band is the whole feel of an overscroll, and it is not a constant: the
 * further past the edge you already are, the less each pixel of finger moves the content,
 * so the list gets progressively harder to pull. Codename One's own tensile drag is a
 * different model, which is why an overscroll here used to feel unlike the same gesture in
 * Flutter even though everything else about the scroll matched.</p>
 *
 * <p>Every number below is pinned by the {@code flutter_scroll_physics} behavioral case,
 * whose expectations are generated by running the same Dart on the Flutter SDK — so this
 * is measured against Flutter rather than tuned by eye.</p>
 */
public class BouncingScrollPhysics extends ScrollPhysics {

    @Override
    public ScrollPhysics applyTo(ScrollPhysics ancestor) {
        BouncingScrollPhysics p = new BouncingScrollPhysics();
        p.parent(buildParent(ancestor));
        return p;
    }

    /**
     * How much of a drag survives at a given overscroll, as a fraction of the viewport.
     * Quadratic, so resistance builds smoothly rather than at a threshold.
     */
    public double frictionFactor(double overscrollFraction) {
        return 0.52 * Math.pow(1 - overscrollFraction, 2);
    }

    @Override
    public double applyPhysicsToUserOffset(ScrollMetrics position, double offset) {
        if (!position.outOfRange()) {
            // In range there is no rubber band at all - resistance here would just feel
            // like a list that does not track the finger.
            return offset;
        }
        double overscrollPastStart =
                Math.max(position.minScrollExtent() - position.pixels(), 0.0);
        double overscrollPastEnd =
                Math.max(position.pixels() - position.maxScrollExtent(), 0.0);
        double overscrollPast = Math.max(overscrollPastStart, overscrollPastEnd);
        // A drag that carries the content back towards the range is measured from where it
        // ENDS rather than where it starts, so returning resists less than leaving. That
        // asymmetry is why a Flutter overscroll lets go easily instead of feeling sticky.
        boolean easing = (overscrollPastStart > 0.0 && offset < 0.0)
                || (overscrollPastEnd > 0.0 && offset > 0.0);
        double friction = easing
                ? frictionFactor((overscrollPast - Math.abs(offset))
                        / position.viewportDimension())
                : frictionFactor(overscrollPast / position.viewportDimension());
        double direction = offset < 0 ? -1.0 : (offset > 0 ? 1.0 : 0.0);
        return direction * applyFriction(overscrollPast, Math.abs(offset), friction);
    }

    /**
     * Applies {@code gamma} to the part of the drag spent outside the content, and none to
     * whatever is left over. A drag long enough to cross back inside is only damped for the
     * stretch where it was actually overscrolled.
     */
    private static double applyFriction(double extentOutside, double absDelta, double gamma) {
        double total = 0.0;
        if (extentOutside > 0) {
            double deltaToLimit = extentOutside / gamma;
            if (absDelta < deltaToLimit) {
                return absDelta * gamma;
            }
            total += extentOutside;
            absDelta -= deltaToLimit;
        }
        return total + absDelta;
    }

    /** A bouncing scrollable always accepts a drag: it can always overscroll. */
    @Override
    public boolean shouldAcceptUserOffset(ScrollMetrics position) {
        return true;
    }
}
