#!/bin/bash
# Runs a project built by build-unity-project.sh through ParparVM with no
# display, and writes the same trace headless.HeadlessMain prints on a JVM:
#
#   parparvm-trace.sh <out dir of build-unity-project.sh> <native|javascript> <trace file> \
#       [--seed n] [--frames n] [--size WxH] [--rate fps] [--input file] \
#       [--dump f1,f2,...] [--commands n] [--count-every n] [--count Prefix]... \
#       [--host class --host-source dir]
#
# --host names the project's headless.HeadlessTrace.Host, and --host-source the
# directory its Java source is under.
#
# A translated program has no command line and no file to read, so the
# settings -- the input script among them -- are written into a generated
# main class as constants. The runtime is compiled again here, against
# ParparVM's class library and not the JDK's: what compiles is what a device
# can link. The two traces are meant to be compared with diff.
#
# Needs what unity-compat-test.sh --parparvm needs: vm/JavaAPI and
# vm/ByteCodeTranslator packaged, and cmake, a C compiler and python3, or node.
#
# PARPARVM_TRACE_LTO=1 builds the native program with link-time optimization
# (-flto when compiling and when linking). It is off otherwise, as it is in a
# ParparVM build that does not ask for it; it is there to measure with.
set -e
HERE="$( cd "$(dirname "$0")" ; pwd -P )"
ROOT="$( cd "$HERE/../../.." ; pwd -P )"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

[ $# -ge 3 ] || { sed -n '2,12p' "$0" >&2; exit 2; }
OUT="$( cd "$1" ; pwd -P )"
TARGET="$2"
TRACE="$3"
shift 3
[ -d "$OUT/app" ] && [ -d "$OUT/gen" ] || fail "$OUT was not built by build-unity-project.sh"
case "$TARGET" in native|javascript) ;; *) fail "the target is native or javascript, not $TARGET" ;; esac

API="$ROOT/vm/JavaAPI/target/classes"
BCT_JAR="$ROOT/vm/ByteCodeTranslator/target/ByteCodeTranslator-1.0-SNAPSHOT.jar"
CORE="$ROOT/maven/core/target/classes"
RUNTIME_SRC="$ROOT/maven/unity-compat/src/main/java"
VM_BUILD="mvn -f vm/JavaAPI/pom.xml package -DskipTests && mvn -f vm/ByteCodeTranslator/pom.xml package -DskipTests"
[ -e "$API/java/lang/Object.class" ] || fail "ParparVM's class library is missing. Build it first: $VM_BUILD"
[ -e "$BCT_JAR" ] || fail "the ParparVM translator is missing. Build it first: $VM_BUILD"

DIR="$OUT/parparvm-$TARGET"
rm -rf "$DIR"
mkdir -p "$DIR/src/headless" "$DIR/classes" "$DIR/box/com/codename1/gaming/physics"

python3 - "$DIR/src/headless/GeneratedMain.java" "$DIR/host-source" "$@" <<'PY'
import sys
out, host_source, args = sys.argv[1], sys.argv[2], sys.argv[3:]
lines, counted = [], []
def quote(s):
    r = '"'
    for ch in s:
        if ch in '"\\':
            r += '\\' + ch
        elif ch == '\n':
            r += '\\n'
        elif ' ' <= ch < '\x7f':
            r += ch
        else:
            r += '\\u%04x' % ord(ch)
    return r + '"'
i = 0
while i < len(args):
    a, v = args[i], args[i + 1] if i + 1 < len(args) else None
    if v is None:
        sys.exit('parparvm-trace: ' + a + ' needs a value')
    if a == '--seed': lines.append('t.seed = %d;' % int(v))
    elif a == '--frames': lines.append('t.frames = %d;' % int(v))
    elif a == '--rate': lines.append('t.rate = %d;' % int(v))
    elif a == '--commands': lines.append('t.commands = %d;' % int(v))
    elif a == '--count-every': lines.append('t.countEvery = %d;' % int(v))
    elif a == '--size':
        w, h = v.split('x')
        lines.append('t.width = %d;' % int(w))
        lines.append('t.height = %d;' % int(h))
    elif a == '--dump':
        lines.append('t.dumps = new int[] {%s};' % ', '.join(str(int(f)) for f in v.split(',')))
    elif a == '--input':
        # One literal for each line, so that no line of source is long.
        text = open(v, encoding='utf-8').read().split('\n')
        lines.append('t.script = ' + '\n                + '.join(quote(l + '\n') for l in text) + ';')
    elif a == '--count': counted.append(v)
    elif a == '--host': lines.append('t.host = new %s();' % v)
    elif a == '--host-source': open(host_source, 'w').write(v)
    else: sys.exit('parparvm-trace: unknown option ' + a)
    i += 2
lines.append('t.counted = new String[] {%s};' % ', '.join(quote(c) for c in counted))
open(out, 'w').write('''// Generated by parparvm-trace.sh. Do not edit.
package headless;

public final class GeneratedMain {
    private GeneratedMain() {
    }

    public static void main(String[] args) {
        HeadlessTrace t = new HeadlessTrace();
        %s
        t.run();
    }
}
''' % '\n        '.join(lines))
PY

# Of the core, only the physics engine: it is plain Java, and the rest of the
# core needs a port under it, which is why the classes that reach it -- the
# view and the other UnityGame* classes beside it, and the application shell --
# stay out.
cp -R "$CORE/com/codename1/gaming/physics/box2d" "$DIR/box/com/codename1/gaming/physics/"
HOST_SOURCE=()
[ ! -f "$DIR/host-source" ] || HOST_SOURCE=("$(cat "$DIR/host-source")")
find "$RUNTIME_SRC" "$OUT/gen" "$DIR/src" "${HOST_SOURCE[@]}" -name '*.java' -not -name 'UnityGame*.java' \
  -not -path '*/com/codename1/unitycompat/app/*' > "$DIR/sources"
echo "$HERE/java/headless/HeadlessTrace.java" >> "$DIR/sources"
javac -nowarn -source 8 -target 8 -bootclasspath "$API" -Xlint:-options -cp "$OUT/app:$DIR/box" -d "$DIR/classes" \
  "@$DIR/sources" > "$DIR/javac.log" 2>&1 || { tail -40 "$DIR/javac.log" >&2; fail "javac against vm/JavaAPI"; }
cp -R "$OUT/app/." "$DIR/classes/"
cp -R "$DIR/box/." "$DIR/classes/"
cp -R "$API/." "$DIR/classes/"

if [ "$TARGET" = native ]; then
  java -cp "$BCT_JAR" com.codename1.tools.translator.ByteCodeTranslator clean "$DIR/classes" "$DIR/out" \
    HeadlessTrace headless HeadlessTrace 1.0 ios none > "$DIR/translate.log" 2>&1 \
    || { tail -40 "$DIR/translate.log" >&2; fail "ParparVM translation to C"; }
  DIST="$DIR/out/dist"
  # The clean target emits a library; this is a program.
  python3 - "$DIST/CMakeLists.txt" <<'PY'
import sys
p = sys.argv[1]
c = open(p).read()
at = c.index('add_library(${PROJECT_NAME}')
end = c.index(')', at)
c = (c[:at] + 'add_executable(' + c[at + len('add_library('):end + 1]
     + '\ntarget_link_libraries(${PROJECT_NAME} m)' + c[end + 1:])
open(p, 'w').write(c)
PY
  COMPILERS=()
  if command -v clang > /dev/null; then
    COMPILERS=(-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_OBJC_COMPILER=clang)
  fi
  LTO=()
  if [ "${PARPARVM_TRACE_LTO:-}" = 1 ]; then
    LTO=(-DCMAKE_C_FLAGS=-flto -DCMAKE_EXE_LINKER_FLAGS=-flto)
  fi
  cmake -S "$DIST" -B "$DIST/build" -DCMAKE_BUILD_TYPE=Release "${COMPILERS[@]}" "${LTO[@]}" > "$DIR/cmake.log" 2>&1 \
    || { tail -40 "$DIR/cmake.log" >&2; fail "cmake"; }
  cmake --build "$DIST/build" -j "$(getconf _NPROCESSORS_ONLN 2> /dev/null || echo 4)" > "$DIR/build.log" 2>&1 \
    || { tail -40 "$DIR/build.log" >&2; fail "the native build"; }
  "$DIST/build/HeadlessTrace" > "$TRACE" 2> "$TRACE.err" || { tail -20 "$TRACE.err" >&2; fail "the native executable failed"; }
else
  java -cp "$BCT_JAR" com.codename1.tools.translator.ByteCodeTranslator javascript "$DIR/classes" "$DIR/out" \
    headless_GeneratedMain com.example.unity headless_GeneratedMain 1.0 ios none > "$DIR/translate.log" 2>&1 \
    || { tail -40 "$DIR/translate.log" >&2; fail "ParparVM translation to JavaScript"; }
  node "$ROOT/vm/selfhost/js/run-program.js" "$DIR/out/dist/headless_GeneratedMain-js" > "$TRACE.raw" 2> "$TRACE.err" \
    || { tail -20 "$TRACE.err" >&2; fail "the JavaScript program failed under node"; }
  # The runtime's own lifecycle markers share stdout with the program.
  grep -v '^PARPAR-LIFECYCLE:' "$TRACE.raw" > "$TRACE" || true
fi
echo "wrote $TRACE ($(wc -l < "$TRACE" | tr -d ' ') lines)"
