== Introduction

Starting in version 8.0, Codename One will be migrating to Maven as its primary build tool. This guide aims to be the definitive source of information for this new project structure.

=== Conventions

This document includes instructions for command-line, NetBeans, and IntelliJ IDEA.  Eclipse documentation is forthcoming.   To improve the flow of the document, it provides toggle buttons to choose which instructions you prefer to follow, as shown below:

==== CLI
++++
<env cli></env>
++++

These are Command-line instructions.  Click on the small gray buttons above and to the right to see these instructions for IntelliJ or NetBeans.

Your selection will be remembered throughout the rest of the document.

==== IntelliJ
++++
<env intellij></env>
++++

These are IntelliJ IDEA instructions.  Click on the small gray buttons above and to the right to see these instructions for Command-line, Eclipse, or NetBeans.

Your selection will be remembered throughout the rest of the document.

==== NetBeans
++++
<env netbeans></env>
++++

These are NetBeans instructions.  Click on the small gray buttons above and to the right to see these instructions for IntelliJ, Eclipse, or Command-line.

Your selection will be remembered throughout the rest of the document.

==== Eclipse
++++
<env eclipse></env>
++++

These are Eclipse instructions.  Click on the small gray buttons above and to the right to see these instructions for IntelliJ, NetBeans or Command-line.

Your selection will be remembered throughout the rest of the document.