/*
 * Test stub of com.codename1.router.Router. The codename1-maven-plugin
 * doesn't depend on the cn1 runtime, so this test-only class stands in for
 * the real Router and records every call so RouteAnnotationProcessorTest
 * can verify the bytecode it generated dispatches correctly.
 *
 * Lives under src/test/java in the plugin, which is on the test classpath.
 * The generated bytecode is loaded by a child classloader at test time and
 * resolves `Router.getInstance().route(String, RouteBuilder)` against this
 * stub.
 *
 * Keep the public signatures identical to the real class.
 */
package com.codename1.router;

import java.util.ArrayList;
import java.util.List;

public final class Router {
    private static final Router INSTANCE = new Router();
    public static Router getInstance() { return INSTANCE; }

    /** What the generated bytecode invoked. Cleared on #reset. */
    public final List<Recorded> recorded = new ArrayList<Recorded>();

    public Router route(String pattern, RouteBuilder builder) {
        recorded.add(new Recorded(pattern, builder));
        return this;
    }

    public void reset() { recorded.clear(); }

    public static final class Recorded {
        public final String pattern;
        public final RouteBuilder builder;
        Recorded(String p, RouteBuilder b) { this.pattern = p; this.builder = b; }
    }
}
