/*
 * Copyright (c) 2008, 2010, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 */
package com.codename1.maven.annotations;

import java.util.Set;

/// SPI for build-time annotation processors that consume the compiled bytecode
/// of a Codename One project.
///
/// Processors are discovered by Java's `ServiceLoader` mechanism: each
/// implementation must be registered in
/// `META-INF/services/com.codename1.maven.annotations.AnnotationProcessor`.
///
/// Lifecycle (driven by `ProcessAnnotationsMojo` in PROCESS_CLASSES, and
/// `GenerateAnnotationStubsMojo` in GENERATE_SOURCES):
///
/// 1. `#getAnnotationDescriptors` — collected once.
/// 2. `#emitStubs` — invoked during GENERATE_SOURCES (before any class
///    exists yet). Processors that need a compile-time stub so application
///    code can reference a yet-to-be-generated symbol emit it here.
/// 3. `#start` — invoked once per processor at the beginning of
///    PROCESS_CLASSES, after the class index has been built.
/// 4. `#processClass` — invoked for every class in the project that has at
///    least one annotation matching `getAnnotationDescriptors`.
/// 5. `#finish` — invoked after all classes have been processed. Processors
///    typically emit their generated bytecode here.
///
/// All callbacks run on the Maven build thread. Processors should not retain
/// state across builds — `start` is the place to (re)initialize.
///
/// **Fail-fast contract:** processors that detect malformed input should
/// accumulate errors via `ProcessorContext#error` so a single build run shows
/// every offending class. Throw `ProcessingException` only for non-recoverable
/// problems (corrupt class files, IO failures, etc.).
public interface AnnotationProcessor {

    /// The set of annotation descriptors this processor cares about, in JVM
    /// internal form (e.g. `Lcom/codename1/annotations/Route;`). Must be
    /// non-null and non-empty; an empty set would mean "scan everything" and
    /// is not supported (it would defeat the dispatch optimization).
    Set<String> getAnnotationDescriptors();

    /// GENERATE_SOURCES hook. Default implementation does nothing.
    /// Processors that need a compile-time stub emit it here via
    /// `ProcessorContext#emitStubSource`.
    ///
    /// (Plugin compiles at Java 7 source level — interfaces here use explicit
    /// no-op classes rather than default methods.)
    void emitStubs(ProcessorContext ctx) throws ProcessingException;

    /// Invoked once before any `#processClass` call.
    void start(ProcessorContext ctx) throws ProcessingException;

    /// Invoked once per matching class.
    void processClass(AnnotatedClass cls, ProcessorContext ctx) throws ProcessingException;

    /// Invoked after every `processClass` has returned. The processor emits
    /// its generated bytecode via `ProcessorContext#emitClass` here.
    void finish(ProcessorContext ctx) throws ProcessingException;
}
