/*
 * Copyright (c) 2008, 2010, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 */
package com.codename1.maven.annotations;

import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.objectweb.asm.AnnotationVisitor;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.FieldVisitor;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

/// Walks a directory of compiled `.class` files and produces the
/// `AnnotatedClass` index passed to processors.
///
/// Uses ASM's `ClassReader.SKIP_CODE | ClassReader.SKIP_DEBUG |
/// ClassReader.SKIP_FRAMES` flags — we only care about declarations
/// (annotations, signatures), never method bodies. This keeps scanning fast
/// even on large projects.
///
/// **Fail-fast policy**: a corrupt or unreadable `.class` aborts the whole
/// scan via `ProcessingException`. Synthetic classes (e.g. anonymous inner
/// `$1.class` generated by javac) are still included — processors decide
/// whether to filter them by checking `AnnotatedClass#isSynthetic`.
public final class ClassScanner {

    /// ASM API level. Match BytecodeComplianceMojo's choice (Opcodes.ASM9) so
    /// the two passes stay consistent.
    private static final int API = Opcodes.ASM9;

    private ClassScanner() { }

    /// Scans every `.class` file under `root` recursively. Returns the index
    /// keyed by JVM internal name.
    public static Map<String, AnnotatedClass> scan(File root) throws ProcessingException {
        Map<String, AnnotatedClass> out = new LinkedHashMap<String, AnnotatedClass>();
        if (root == null || !root.isDirectory()) return out;
        scan(root, out);
        return out;
    }

    private static void scan(File dir, Map<String, AnnotatedClass> out) throws ProcessingException {
        File[] children = dir.listFiles();
        if (children == null) return;
        for (int i = 0; i < children.length; i++) {
            File f = children[i];
            if (f.isDirectory()) {
                scan(f, out);
            } else if (f.isFile() && f.getName().endsWith(".class")) {
                AnnotatedClass cls = readClass(f);
                if (cls != null) out.put(cls.getInternalName(), cls);
            }
        }
    }

    /// Reads a single `.class` file. Exposed for unit tests.
    public static AnnotatedClass readClass(File file) throws ProcessingException {
        FileInputStream fin = null;
        BufferedInputStream bin = null;
        try {
            fin = new FileInputStream(file);
            bin = new BufferedInputStream(fin);
            return readClass(bin, file);
        } catch (IOException e) {
            throw new ProcessingException("Could not read " + file + ": " + e.getMessage(), e);
        } finally {
            // Best-effort close. We've already either returned the parsed class
            // or raised ProcessingException for the read failure; a close-side
            // IOException at this point can't change the outcome, so swallow it
            // with a debug-only trace rather than masking the original error.
            closeQuietly(bin);
            if (bin == null) closeQuietly(fin);
        }
    }

    private static void closeQuietly(java.io.Closeable c) {
        if (c == null) return;
        try {
            c.close();
        } catch (IOException ignored) {
            // Intentional: see readClass(File) finally block.
        }
    }

    /// Reads a class from an arbitrary input stream. `source` is used only for
    /// error messages; pass null when unavailable.
    public static AnnotatedClass readClass(InputStream in, File source) throws ProcessingException {
        try {
            ClassReader reader = new ClassReader(in);
            Collector c = new Collector(source);
            reader.accept(c, ClassReader.SKIP_CODE | ClassReader.SKIP_DEBUG | ClassReader.SKIP_FRAMES);
            return c.build();
        } catch (IOException e) {
            throw new ProcessingException("Could not read class from " + source + ": " + e.getMessage(), e);
        } catch (RuntimeException e) {
            throw new ProcessingException("ASM failed parsing " + source + ": " + e.getMessage(), e);
        }
    }

    // ------------------------------------------------------------------------
    // Internals
    // ------------------------------------------------------------------------

    private static final class Collector extends ClassVisitor {
        private final File source;
        private String internalName;
        private String superInternalName;
        private List<String> interfaces;
        private int access;
        private final Map<String, AnnotationValues> classAnnotations = new LinkedHashMap<String, AnnotationValues>();
        private final List<MethodInfo> methods = new ArrayList<MethodInfo>();
        private final List<FieldInfo> fields = new ArrayList<FieldInfo>();

        Collector(File source) {
            super(API);
            this.source = source;
        }

        AnnotatedClass build() {
            return new AnnotatedClass(
                    internalName, superInternalName, interfaces, access,
                    classAnnotations, methods, fields, source);
        }

        @Override
        public void visit(int version, int access, String name, String signature,
                          String superName, String[] interfacesArr) {
            this.access = access;
            this.internalName = name;
            this.superInternalName = superName;
            if (interfacesArr != null) {
                this.interfaces = new ArrayList<String>(interfacesArr.length);
                Collections.addAll(this.interfaces, interfacesArr);
            }
        }

        @Override
        public AnnotationVisitor visitAnnotation(String descriptor, boolean visible) {
            Map<String, Object> values = new LinkedHashMap<String, Object>();
            classAnnotations.put(descriptor, new AnnotationValues(descriptor, values));
            return new AnnotationCollector(API, values);
        }

        @Override
        public MethodVisitor visitMethod(int access, String name, String descriptor,
                                          String signature, String[] exceptions) {
            final int mAccess = access;
            final String mName = name;
            final String mDesc = descriptor;
            final Map<String, AnnotationValues> mAnnotations =
                    new LinkedHashMap<String, AnnotationValues>();
            return new MethodVisitor(API) {
                @Override
                public AnnotationVisitor visitAnnotation(String d, boolean v) {
                    Map<String, Object> values = new LinkedHashMap<String, Object>();
                    mAnnotations.put(d, new AnnotationValues(d, values));
                    return new AnnotationCollector(API, values);
                }

                @Override
                public void visitEnd() {
                    methods.add(new MethodInfo(mName, mDesc, mAccess, mAnnotations));
                }
            };
        }

        @Override
        public FieldVisitor visitField(int access, String name, String descriptor,
                                        String signature, Object value) {
            final int fAccess = access;
            final String fName = name;
            final String fDesc = descriptor;
            final Map<String, AnnotationValues> fAnnotations =
                    new LinkedHashMap<String, AnnotationValues>();
            return new FieldVisitor(API) {
                @Override
                public AnnotationVisitor visitAnnotation(String d, boolean v) {
                    Map<String, Object> values = new LinkedHashMap<String, Object>();
                    fAnnotations.put(d, new AnnotationValues(d, values));
                    return new AnnotationCollector(API, values);
                }

                @Override
                public void visitEnd() {
                    fields.add(new FieldInfo(fName, fDesc, fAccess, fAnnotations));
                }
            };
        }
    }

    /// Captures annotation element values into a `Map<String,Object>`. Handles
    /// nested annotations and arrays recursively, matching ASM's contracts.
    private static final class AnnotationCollector extends AnnotationVisitor {
        private final Map<String, Object> values;

        AnnotationCollector(int api, Map<String, Object> values) {
            super(api);
            this.values = values;
        }

        @Override
        public void visit(String name, Object value) {
            values.put(name, value);
        }

        @Override
        public void visitEnum(String name, String descriptor, String value) {
            values.put(name, new String[] { descriptor, value });
        }

        @Override
        public AnnotationVisitor visitAnnotation(String name, String descriptor) {
            Map<String, Object> nested = new LinkedHashMap<String, Object>();
            values.put(name, new AnnotationValues(descriptor, nested));
            return new AnnotationCollector(api, nested);
        }

        @Override
        public AnnotationVisitor visitArray(String name) {
            final List<Object> items = new ArrayList<Object>();
            values.put(name, items);
            return new AnnotationVisitor(api) {
                @Override
                public void visit(String n, Object value) { items.add(value); }

                @Override
                public void visitEnum(String n, String descriptor, String value) {
                    items.add(new String[] { descriptor, value });
                }

                @Override
                public AnnotationVisitor visitAnnotation(String n, String descriptor) {
                    Map<String, Object> nested = new LinkedHashMap<String, Object>();
                    items.add(new AnnotationValues(descriptor, nested));
                    return new AnnotationCollector(api, nested);
                }

                @Override
                public AnnotationVisitor visitArray(String n) {
                    // Nested arrays are extremely rare in annotations; recurse.
                    final List<Object> nested = new ArrayList<Object>();
                    items.add(nested);
                    return collectInto(api, nested);
                }
            };
        }
    }

    private static AnnotationVisitor collectInto(int api, final List<Object> sink) {
        return new AnnotationVisitor(api) {
            @Override
            public void visit(String n, Object value) { sink.add(value); }
        };
    }
}
