import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

/// A static linter for Codename One screens. It reads a form model (from
/// `tools/DumpForm.java`) and flags the bug patterns that are invisible in a
/// screenshot but bite at runtime or on other form factors:
///
///   - nested scrolling (a scrollable container inside another scrollable one)
///   - opaque text labels (a Label/SpanLabel with a solid background -- invisible
///     on a matching surface, a coloured box on a different one; the classic CN1
///     dark-mode "white box behind white text" trap)
///   - opaque structural containers (a plain white layout container with no border
///     that should almost certainly be transparent so the parent shows through)
///   - image borders generated by CSS (a 9-piece raster border where a vector one
///     was intended -- blurry when scaled, bloats the theme)
///   - a restyled base `Container` UIID (background/border on the load-bearing
///     default style -- causes cascading surprises)
///   - zero-size components that still carry text (a collapsed/clipped element)
///
/// Usage:
///     java tools/DumpForm.java com.example.MyApp --out target/form-model.tsv
///     java tools/GuiLint.java target/form-model.tsv
///
/// Self-contained; no Codename One jars needed.
/// Exit codes: 0 clean, 1 issues found, 2 usage error.
public class GuiLint {

    static final class N {
        int depth; String cls, uiid, layout, bg, border, name, text;
        int x, y, w, h, bgAlpha;
        boolean sx, sy, svis, opaque, imgBorder;
        N parent;
        String label() {
            return (!uiid.equals("-") ? uiid : cls) + (text.isEmpty() ? "" : " '" + trunc(text, 28) + "'");
        }
    }

    public static void main(String[] args) throws Exception {
        if (args.length != 1) { System.err.println("Usage: java GuiLint.java <form-model.tsv>"); System.exit(2); }
        List<N> nodes = new ArrayList<>();
        N[] stack = new N[64];
        for (String line : Files.readAllLines(Paths.get(args[0]))) {
            if (!line.startsWith("C\t")) continue;
            String[] f = line.split("\t", -1);
            if (f.length < 18) continue;
            N n = new N();
            n.depth = pi(f[1]); n.cls = f[2]; n.uiid = f[3];
            n.x = pi(f[4]); n.y = pi(f[5]); n.w = pi(f[6]); n.h = pi(f[7]);
            n.sx = f[8].equals("1"); n.sy = f[9].equals("1"); n.svis = f[10].equals("1");
            n.opaque = f[11].equals("1"); n.bg = f[12]; n.bgAlpha = pi(f[13]);
            n.border = f[14]; n.imgBorder = f[15].equals("1"); n.layout = f[16]; n.name = f[17];
            n.text = f.length > 18 ? f[18] : "";
            n.parent = n.depth > 0 ? stack[n.depth - 1] : null;
            if (n.depth < stack.length) stack[n.depth] = n;
            nodes.add(n);
        }

        List<String> issues = new ArrayList<>();

        for (N n : nodes) {
            // 1) nested scrolling (same axis). The Form/ContentPane is the natural
            //    scroll root, so only flag a scrollable inside ANOTHER scrollable.
            if (n.sy) {
                N a = scrollableAncestor(n, true);
                if (a != null) issue(issues, "NESTED-SCROLL", n.label()
                        + " scrolls vertically inside " + a.label() + " which also scrolls vertically"
                        + " -- the inner one usually wins and the outer cannot scroll. Make one of them non-scrollable.");
            }
            if (n.sx) {
                N a = scrollableAncestor(n, false);
                if (a != null) issue(issues, "NESTED-SCROLL", n.label()
                        + " scrolls horizontally inside " + a.label() + " which also scrolls horizontally.");
            }

            boolean sized = n.w > 1 && n.h > 1;

            // 2) opaque text label (with no border -- a bordered one is an
            //    intentional styled box / chip, not the white-box trap).
            boolean noBorder = n.border.equals("none") || n.border.equals("empty");
            if (sized && (n.cls.equals("Label") || n.cls.equals("SpanLabel")) && n.opaque && noBorder) {
                issue(issues, "OPAQUE-LABEL", n.label() + " has a solid background (#" + n.bg
                        + "). Text labels should normally be 'background-color: transparent' so the surface shows through"
                        + " (otherwise it is a coloured box behind the text, e.g. white-on-white in dark mode).");
            }

            // 3) opaque structural white container with no border.
            if (sized && n.cls.equals("Container") && n.opaque && n.bg.equals("ffffff")
                    && (n.border.equals("none") || n.border.equals("empty"))
                    && !n.layout.equals("-")) {
                issue(issues, "OPAQUE-CONTAINER", n.label() + " is an opaque white " + n.layout
                        + " with no border. A plain layout container should usually be transparent so the parent background"
                        + " shows through; an opaque one paints a white box (and breaks dark mode).");
            }

            // 4) image border generated by CSS.
            if (n.imgBorder) {
                issue(issues, "IMAGE-BORDER", n.label() + " uses a raster (9-piece) image border. The CN1 CSS compiler"
                        + " falls back to one for combinations it cannot draw as a vector; prefer a plain border /"
                        + " border-radius so it stays sharp when scaled and does not bloat the theme.");
            }

            // 5) restyled base Container UIID.
            if (n.uiid.equals("Container") && (n.opaque || (!n.border.equals("none") && !n.border.equals("empty")))) {
                issue(issues, "RESTYLED-CONTAINER", "A component keeps the base \"Container\" UIID but is styled"
                        + " (opaque=" + n.opaque + ", border=" + n.border + "). Styling the load-bearing default Container"
                        + " style cascades into unrelated screens; give it its own UIID instead.");
            }

            // 6) zero-size component that still carries text.
            if (!n.text.isEmpty() && (n.w <= 0 || n.h <= 0)) {
                issue(issues, "ZERO-SIZE", n.label() + " has text but is " + n.w + "x" + n.h
                        + " -- it is collapsed/clipped and will not be visible. Check its layout constraint or parent size.");
            }
        }

        if (issues.isEmpty()) {
            System.out.println("CLEAN - no lint issues found in " + nodes.size() + " components.");
            System.exit(0);
        }
        System.out.println(issues.size() + " issue(s) found:\n");
        for (String s : issues) System.out.println(s);
        System.exit(1);
    }

    private static N scrollableAncestor(N n, boolean vertical) {
        for (N a = n.parent; a != null; a = a.parent) {
            // the form's own content pane is the expected scroll root - not "nested"
            if (a.uiid.equals("ContentPane") || a.cls.equals("Form")) continue;
            if (vertical ? a.sy : a.sx) return a;
        }
        return null;
    }

    private static void issue(List<String> out, String code, String msg) {
        out.add("[" + code + "] " + msg);
    }

    private static int pi(String s) { try { return Integer.parseInt(s); } catch (Exception e) { return 0; } }
    private static String trunc(String s, int n) { return s.length() <= n ? s : s.substring(0, n - 1) + "..."; }
}
