/*
 * Copyright (c) 2026, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Codename One through http://www.codenameone.com/ if you
 * need additional information or have any questions.
 */

// Auto-generated by Codename One from the com.codename1.surfaces framework.
// Compiled ONLY into the CN1Widgets extension target (iOS 16.1+). Shared entry view +
// configuration factory used by the generated per-kind widget structs.
//
// Note on the composition strategy: the Widget protocol requires init(), so one
// parameterized struct cannot serve every kind. The generated CN1WidgetBundle.swift
// therefore emits a tiny concrete struct per kind (CN1Widget_<kindid>) whose body
// delegates to cn1MakeWidgetConfiguration below with its hardcoded kind metadata.

import Foundation
import SwiftUI
import WidgetKit

/// Renders the layout matching the active widget family, resolving to the "default"
/// layout when no per-family override was published.
struct CN1WidgetEntryView: View {
    let entry: CN1WidgetEntry
    @Environment(\.widgetFamily) var family

    var body: some View {
        let layout = cn1LayoutForFamily(entry.layouts, family: family)
        return Group {
            if let layout = layout {
                cn1RenderNode(layout, CN1RenderContext(
                        state: entry.state,
                        imagesDir: entry.imagesDir,
                        source: entry.kind,
                        allowLinks: cn1FamilyAllowsLinks(family),
                        parentAxis: nil))
            } else {
                // Placeholder shown before the app publishes its first timeline.
                Text("No data yet")
                        .font(.system(size: 12))
                        .foregroundColor(.secondary)
            }
        }
        // The root action fires on families where per-node Links are unsupported
        // (small widgets, lock screen accessories) and as the default tap elsewhere.
        .widgetURL(cn1RootActionURL(layout, source: entry.kind))
        .cn1WidgetContainerBackground()
    }
}

/// Maps a WidgetKit family onto the Codename One size families, most specific first.
///
/// The accessory families are shared between the iOS lock screen and the watch face, so
/// accessoryRectangular resolves to the watch layout when one was published and falls back to the
/// lock-screen layout otherwise -- an app that only publishes "lockscreen" still gets a
/// complication, and one that publishes both gets the layout it designed for each surface.
func cn1LayoutForFamily(_ layouts: [String: Any], family: WidgetFamily) -> [String: Any]? {
    // The four system families are @available(watchOS, unavailable) -- not merely absent at
    // runtime, but unnameable -- so the whole switch has to go behind the platform guard
    // rather than relying on `default`.
#if os(watchOS)
    var keys: [String] = []
#else
    var keys: [String]
    switch family {
    case .systemSmall:
        keys = ["small"]
    case .systemMedium:
        keys = ["medium"]
    case .systemLarge, .systemExtraLarge:
        keys = ["large"]
    default:
        keys = []
    }
#endif
    if #available(iOS 16.0, watchOS 9.0, *) {
        switch family {
        case .accessoryCircular:
            keys = ["watchCircular"]
        case .accessoryRectangular:
            // The same family serves the iPhone lock screen and the watch face, so each surface
            // has to prefer the layout that was designed for it.
#if os(watchOS)
            keys = ["watchRectangular", "lockscreen"]
#else
            keys = ["lockscreen", "watchRectangular"]
#endif
        case .accessoryInline:
            keys = ["watchInline"]
        default:
            break
        }
#if os(watchOS)
        if family == .accessoryCorner {
            // No corner slot outside watchOS; the circular layout is the closest shape.
            keys = ["watchCorner", "watchCircular"]
        }
#endif
    }
    for key in keys {
        if let layout = layouts[key] as? [String: Any] {
            return layout
        }
    }
    return layouts["default"] as? [String: Any]
}

/// Per-node Link actions only work on medium and larger home-screen families; everywhere
/// else the tap target is the whole widget via widgetURL.
func cn1FamilyAllowsLinks(_ family: WidgetFamily) -> Bool {
    // Same reason as above: the system families cannot be named on watchOS. The answer is
    // false there in any case -- every watch family is an accessory family, and none of them
    // supports a per-node Link.
#if os(watchOS)
    return false
#else
    switch family {
    case .systemMedium, .systemLarge, .systemExtraLarge:
        return true
    default:
        return false
    }
#endif
}

extension View {
    /// iOS 17 requires widgets to declare a container background (or show a scolding
    /// placeholder). The surfaces node tree draws its own backgrounds, so declare a
    /// clear one; earlier versions pass through unchanged.
    @ViewBuilder func cn1WidgetContainerBackground() -> some View {
        // watchOS 10.0 is spelled out rather than left to `*`: the watch extension's floor is
        // exactly 10.0, so an unqualified `*` would compile today and silently stop guarding
        // if that floor were ever lowered.
        if #available(iOS 17.0, watchOS 10.0, *) {
            self.containerBackground(for: .widget) {
                Color.clear
            }
        } else {
            self
        }
    }
}

/// Shared factory behind every generated CN1Widget_<kindid> struct.
func cn1MakeWidgetConfiguration(kind: String, displayName: String, description desc: String,
        families: [WidgetFamily]) -> some WidgetConfiguration {
    return StaticConfiguration(kind: kind, provider: CN1WidgetProvider(kind: kind)) { entry in
        CN1WidgetEntryView(entry: entry)
    }
    .configurationDisplayName(displayName)
    .description(desc)
    .supportedFamilies(families)
}
