=== Generate native interfaces (`generate-native-interfaces`)

Generates stub implementations for all native interfaces defined in the project. This won't overwrite any existing implementations that may exist.

You should run this goal explicitly after you create a native interface in your class.

See the Codename One Developer guide section on <<_native_interfaces,native interfaces>> for more information on creating native interfaces.

==== Usage example

Suppose you've created a native interface as the Java interface `com.mycompany.myapp.MyNative`, as described in the example in <<_native_interfaces,native interfaces>>.

After creating this (and possibly other) native interfaces in your project, run the `generate-native-interfaces` Maven goal as follows:

[source, bash]
----
include::../demos/common/src/main/snippets/developer-guide/appendix-goal-generate-native-interfaces.sh[tag=appendix-goal-generate-native-interfaces-bash-001,indent=0]
----

By default this generates Java/Objective-C stubs. You can optionally include Swift and Kotlin stubs (both off by default):

[source,bash]
----
include::../demos/common/src/main/snippets/developer-guide/appendix-goal-generate-native-interfaces.sh[tag=appendix-goal-generate-native-interfaces-bash-002,indent=0]
----

This will generate the following files (if they don't exist yet).

Java SE::
`javase/src/main/java/com/mycompany/myapp/MyNativeImpl.java`
iOS::
. `ios/src/main/objectivec/com_mycompany_myapp_MyNativeImpl.h`
. `ios/src/main/objectivec/com_mycompany_myapp_MyNativeImpl.m`
Android::
`android/src/main/java/com/mycompany/myapp/MyNativeImpl.java`
Android (optional Kotlin)::
`android/src/main/java/com/mycompany/myapp/MyNativeImpl.kt`
JavaScript::
`javascript/src/main/javascript/com_mycompany_myapp_MyNative.js`
iOS (optional Swift)::
`ios/src/main/objectivec/com_mycompany_myapp_MyNativeImpl.swift`
Native Windows::
`win/src/main/c/com/mycompany/myapp/MyNativeImplCodenameOne.c`
Native Linux::
`linux/src/main/c/com/mycompany/myapp/MyNativeImplCodenameOne.c`

Open and edit these files to implement your native interface methods as desired.

A Gradle project runs the same generator as `./gradlew generateNativeInterfaces`, and writes the stubs under `src/<platform>/<lang>` instead; see <<gradle-native-interfaces>>.

