=== Generate archetype (`generate-archetype`)

NOTE: This goal isn't used. It was originally developed to simplifying the maintenance of multiple application archetypes, but this approach was later abandoned in favor of <<creating-project-templates, application project templates>>.

The `generate-archetype` mojo will generate a new archetype maven project based on an existing archetype project. It's designed to ease the maintenance of several similar archetypes which differ in some dependencies or default project source code. It takes as input a template file which references the base archetype project and specifies what to customize.

**Example Usage**

 mvn cn1:generate-archetype -Dtemplate=/path/to/mytemplate.java

==== Parameters

template::
Required. The path to a template file that should be used to generate the archetype project.

outputDir::
Optional. The output directory where the archetype project should be written to. The project will be created at `outputDir`/`artifactId`, where the `artifactId` is as specified in the `[archetype]` section of the template. By default this will be the current working directory.

[NOTE]
====
This goal doesn't require a project to run. You can run it directly using the full goal coordinates:

 mvn com.codenameone:codenameone-maven-plugin:7.0-SNAPSHOT:generate-archetype \
 -Dtemplate=/path/to/mytemplate.java

====


==== Template syntax

Here is a sample template file:

.A sample template, which is a.Java file:

[source,text]
-----
include::../demos/common/src/main/snippets/developer-guide/appendix-goal-generate-archetype.txt[tag=appendix-goal-generate-archetype-text-001,indent=0]
-----
<1> The `[archetype]` section specifies details about the archetype project to be generated. For example, the `groupId`, `artifactId`, etc.
<2> The `extends` property in the `[archetype]` section is required, and points to the location of the archetype project that this template is based on. Path is relative to the location of the template file.
<3> The `[dependencies]` section includes content that should be injected into the `<dependencies>` section of the pom.xml file. Note that this isn't the pom file for the archetype project itself. It's the pom.xml file for the project that the archetype project is to generate.

Notice that the above template is velocity template for a Java file. It will be used as the source code for the main class in the resulting project. It's a velocity template because maven's `archetype:generate` goal will process it to replace properties such as package and the main class name.

===== Template sections

archetype::
This is a required section and specifies both the location of the base archetype project from which this project is to be derived, and the coordinates of the output archetype project, such as `groupId`, `archetypeId`, and `version`.
+
====
**Example**

[source,text]
-----
include::../demos/common/src/main/snippets/developer-guide/appendix-goal-generate-archetype.txt[tag=appendix-goal-generate-archetype-text-002,indent=0]
-----

**Properties**

extends::
Required. The path to the archetype project that this is based on. This should usually be the `cn1app-archetype` project as it includes the placeholders that this generator relies on for injecting content into the pom.xml file and its project structure was used as a basis for developing this mojo.

groupId::
The groupID of the resulting archetype project. You can or use the `id` property to specify `groupId`, `artifactId` and `version` in a single string.

artifactId::
The artifactId of the resulting archetype project. You can or use the `id` property to specify `groupId`, `artifactId` and `version` in a single string.

version::
The version of the resulting archetype project. You can or use the `id` property to specify `groupId`, `artifactId` and `version` in a single string.

id::
A colon-separated string in the format `groupId:artifactId:version` that can be used as an alternative to `groupId`, `artifactId`, and `version`.

parentGroupId::
If the output archetype project should be part of a multi-module project, then this will specify the parent `groupId` for the `<parent>` tag in the pom.xml file.

parentArtifactId::
If the output archetype project should be part of a multi-module project, then this will specify the parent `archetypeId` for the `<parent>` tag in the pom.xml file.

parentVersion::
If the output archetype project should be part of a multi-module project, then this will specify the parent `archetypeId` for the `<parent>` tag in the pom.xml file.

parent::
A colon-delimited string in the format `parentGroupId:parentArtifactId:parentVersion` that can be used as an alternative to the `parentGroupId`, `parentArtifactId`, and `parentVersion` properties.

====

dependencies::
Specify more dependencies that should be injected into the `<dependencies>` section of the pom.xml file for the common module of the maven project that the archetype will generate. The content of this section will be injected into the `src/main/resources/archetype-resources/common/pom.xml` of the archetype project.
+
====
**Example**

[source,text]
----
include::../demos/common/src/main/snippets/developer-guide/appendix-goal-generate-archetype.txt[tag=appendix-goal-generate-archetype-text-003,indent=0]
----
====

css::
CSS content that should be injected into the theme.css file of the project. This CSS will be injected into the `src/main/resources/archetype-resources/common/src/main/css/theme.css` file of the archetype project.
+
====
**Example**

[source,text]
----
include::../demos/common/src/main/snippets/developer-guide/appendix-goal-generate-archetype.txt[tag=appendix-goal-generate-archetype-text-004,indent=0]
----
====

properties::
Properties that should be appended to the `codenameone_settings.properties` file. These will be added to the `src/main/resources/archetype_resources/common/codenameone_settings.properties` file of the archetype project.
+
====
**Example**

[source,text]
----
include::../demos/common/src/main/snippets/developer-guide/appendix-goal-generate-archetype.txt[tag=appendix-goal-generate-archetype-text-005,indent=0]
----
====

files::
Files contains a list of files that should be created in the archetype project. All file paths are relative to the "common" project root directory. Each path should have a corresponding section with the heading `[file:path/to/file]`.
+
====
**Example**

[source,text]
-----
include::../demos/common/src/main/snippets/developer-guide/appendix-goal-generate-archetype.txt[tag=appendix-goal-generate-archetype-text-006,indent=0]
-----
====
