== Security

Security is a "big word." It implies many things and that's also true for the mobile app development so before you get started lets try to define the scope of security.

You will deal with application security and its communication mechanisms while ignoring everything beyond that scope. Let's start with a simple fact:

____
Codename One applications are secure on the devices by the nature of the mobile OS security.
____

For most intents and purposes this will be enough, unless you're specifically concerned about security this section isn't for you. Mobile OS's isolate applications from one another so it's hard for an application to damage the OS or even damage/spy on a different app.

The restrictions laid on apps are here to make them extra secure and on top of that Codename One lays a few big advantages in security:

- Codename One code is compiled (unlike for example, PhoneGap/Cordova)
- Codename One obfuscates by default which makes the binaries harder to reverse engineer
- Codename One compiles the UI to native code too which means typical reverse engineering code will have a harder time following
- Codename One disables debug flags so a hacker won't be able to debug your production app on the device

Despite that you still need to keep in mind that the binary could still be reverse engineered and so it's important to avoid storing keys in the client side code. For example, if you've an API key to access a service (for example, Google Cloud key) it needs to be stored in your server and not as a constant in your app!

Each section below discusses some attack vectors against applications and how they can be stopped. Pretty much all these attacks require a sophisticated attacker which will exist for high value targets (for example, bank apps, government etc.).

=== Constant obfuscation

One of the first things a hacker will do when compromising an app is look at it. For example, if I want to exploit a bank's login UI I would look at the label next to the login and then search for it in the decompiled code. if the UI has the String "enter user name and password" I can search for that.

It won't lead directly to a hack or exploit, but it will narrow down the area of the code where you should look and it makes the first step that much easier. Obfuscation helps as it removes descriptive method names but it can't hide the Strings you use in constants. If an app has a secret key within obfuscating it can make a difference (albeit a slight difference).

Notice that this is a temporary roadblock as any savvy hacker would compile the app and connect a debugger eventually (although this is blocked in release builds) and would be able to inspect values of variables/flow. But the road to reverse engineering the app would be harder even with a simple xor obfuscation.

NOTE: This isn't encoding or encryption — it's a simple obfuscation of the data.

two simple methods in the `Util` class:

[source,java]
----
public static String xorDecode(String s);
public static String xorEncode(String s);
----

They use a simple xor based obfuscation to make a String less readable. For example, if you've code like this:

[source,java]
----
private static final String SECRET = "Don't let anyone see this....";
----

You might be concerned about the secret, then this would make it slightly harder to find out:

[source,java]
----
// Don't let anyone see this....
private static final String SECRET = Util.xorDecode("RW1tI3Ema219KmpidGFhdTFhdnE1Yn9xajQ1MjM=");
----

Notice that this is **not secure**, if you've a crucial value that must not be found you need to store it in the server. There is no alternative because everything that's sent to the client can be compromised by a determined hacker.

TIP: Use the comment to help you find the string in the code

Codename One's built-in user-specific constants are obfuscated with this method. For example, an app built with Codename One carries some internal data such as the user who built the app, which is now obfuscated. The following small app encodes strings so you can copy and paste them into your app easily:

[source,java]
----
Form hi = new Form("Encoder", BoxLayout.y());
TextField bla = new TextField("", "Type Text Here", 20, TextArea.ANY);
TextArea encoded = new TextArea();
SpanLabel decoded = new SpanLabel();
hi.addAll(bla, encoded, decoded);
bla.addDataChangedListener((a, b) -> {
    String s = bla.getText();
    String e = Util.xorEncode(s);
    encoded.setText(e);
    decoded.setText(Util.xorDecode(e));
    hi.getContentPane().animateLayout(100);
});

hi.show();
----

This allows you to type in the first text field and the second text area shows the encoded result. A text area is used so copy/paste is easy.

For your convenience this app can be accessed here: https://www.codenameone.com/demos/StringEncoder/index.html


=== Storage encryption

Codename One had support for bouncy castle encryption for quite a while but it isn't as intuitive as you'd like it to be. This makes
securing/encrypting your app more painful than it should.

Codename One supports full encryption of the `Storage` (notice the distinction, `Storage` isn't `FileSystemStorage`).
This is available by installing the bouncy castle cn1lib from the extensions menu then using one line of code

[source,java]
----
EncryptedStorage.install("your-pass-encryption-key");
----

TIP: You would want that code within your `init(Object)` method

Notice that you can't use storage or preferences to store this data as it would be encrypted (`Preferences` uses
`Storage` internally). You can use a password for this key and it would make it way more secure **but** if a user
changes his password you might have a problem. In that case you might need the old password to migrate to
a new password.

This works thru a new mechanism in storage where you can replace the storage instance with another instance using:

[source,java]
----
Storage.setStorageInstance(new MyCustomStorageSubclass());
----

You can leverage that knowledge to change the encryption password on the encryption storage using pseudo code like this:

[source,java]
----
EncryptedStorage.install(oldKey);
InputStream is = Storage.getInstance().createInputStream(storageFileName);
byte[] data = Util.readInputStream(is);
EncryptedStorage.install(newKey);
OutputStream o = Storage.getInstance().createOutputStream("TestEncryption");
o.write(data);
o.close();
----

NOTE: It isn't a good idea to replace storage objects when an app is running so this is purely for this special case...

If you use preferences it might be a good idea to set their built-in location to a different path using something like `Preferences.setPreferencesLocation("EncryptedPreferences");`.

This is useful as it prevents the encrypted preferences from colliding with the regular preferences.

=== Disabling screenshots

One of the common security features some apps expect is the ability to block a screenshot. In the past apps like snapchat required that you touch the screen to view a photo to block the ability to grab a screenshot (on iOS). This no longer works...

Blocking screenshots is implemented by classifying the app window as secure on Android. You can enable this via the build hint `android.disableScreenshots=true`. Once that's added screenshots should no longer work for the app, this might impact other things as well such as the task view which will no longer show the screenshot either.

On iOS, you can't prevent a user from taking a static screenshot, but you can block screen capture/recording while it's active. This uses `UIScreen.isCaptured` and its change notification to hide the app contents while a capture session is active. Enable this behavior with the build hint `ios.disableScreenshots=true`.

=== Blocking copy & paste

Blocking copy & paste is useful for cases where a device might have spyware installed that monitors the clipboard. This also prevents a user from using a password manager (which rely on the clipboard), those managers could be compromised and thus if you're building a secure app this might be necessary.

You can block copy & paste on Android & iOS. Blocking of copy & paste can be implemented globally or on a specific field.

To block copy & paste globally use:

[source,java]
----
Display.getInstance().setProperty("blockCopyPaste", "true");
----

To block copy & paste on a specific field do:

[source,java]
----
textCmp.putClientProperty("blockCopyPaste", Boolean.TRUE);
----

NOTE: Notice that the inverse of using `false` might not work as expected

=== Blocking jailbreak

iOS & Android are walled gardens which is both a blessing and a curse. Looking at the bright side the walled garden aspect of locked down devices means the devices are more secure by nature. For example, on a PC that was compromised you can detect the banking details of a user logging into a bank. But on a phone it would be much harder due to the deep process isolation.

This isn't true for jailbroken or rooted devices. In these devices security has been compromised often with good intentions (opening up the ecosystem) but it can also be used as a step in a serious attack on an application!

For obvious reasons it's hard to accurately detect a jailbroken or rooted device but when possible if you've a high security app you might want to block the functionality or even raise a "silent alarm" in such a case. To detect this you can use the `isJailbrokenDevice` method as such:

[source,java]
----
if(Display.getInstance().isJailbrokenDevice()) {
    // probably jailbroken or rooted
} else {
   // probably not
}
----

Notice that this isn't right, you can't be 100% sure as there are no official ways to detect jailbreak. that's why it's crucial to encrypt everything and assume the device was compromised to begin with when dealing with sensitive data. Still it's worthwhile to use these API's to make the life of an attacker a little bit harder.

=== Strong Android certificates

When Android launched RSA1024 with SHA1 was considered strong enough for the foreseeable future, this hasn't changed completely but the recommendation today is to use stronger cyphers for signing & encrypting as those can be compromised.

APK's are signed as part of the build process when you upload an app to the Google Play Store. This process seems redundant as you generate the signature/certificate ourselves (unlike Apple which generates it for you). But, this is a crucial step as it allows the device to verify upgrades and make sure a new update is from the same original author!

This means that if a hacker takes over your account on Google Play, he still won't be able to ship fake updates to your apps without your certificate. that's important since if a hacker would have access to your certificate he could create an app update that would send him all the users private information for example, if you're a bank this could be a disaster.

Android launched with RSA1024/SHA1 as the signing certificates. This was good enough at the time and is still pretty secure. But, these algorithms are eroding and it's conceivable that within the 10-15 year lifetime of an app they might be compromised using powerful hardware. that's why Google introduced support for stronger cryptographic signing into newer versions of Android and you can use that.

==== The bad news

There is a downside...

Google introduced that capability in Android 4.3 so using these new keys will break compatibility with older devices. If you're building a highly secure app this is probably a tradeoff you should accept. If not this might not be worth it for some theoretical benefit.

Furthermore, if your app is already shipping you're out of luck. Due to the obvious security implications once you shipped an app the certificate is final. Google doesn't provide a way to update the certificate of a shipping app. Thus this feature applies to apps that aren't yet in the play store.

==== The good

If you're building a new app this is pretty easy to integrate and requires no changes on your part. Just a new certificate. You can generate the new secure key using instructions in articles like https://guardianproject.info/2015/12/29/how-to-migrate-your-android-apps-signing-key/[this one].

If you're using #Codename One Setting# you can check the box to generate an SHA512 key which will harden the security for the APK.

=== Certificate pinning

When you connect to HTTPS servers your networking code checks the certificate on the server. If the certificate was issued by a trusted certificate authority then the connection goes through, otherwise it fails. Imagine you're sitting in a coffee shop connected to the local wifi, and you try to connect to Gmail to check your email. Since you use HTTPS to Google you trust the connection is secure.

TIP: What if the coffee shop was hacked and the router is listening in on everything?

HTTPS is encrypted and the way encryption works is thru the certificate. The server sends you a certificate and you can use that to send encrypted data to it.

TIP: What if the router grabs the server's certificate and communicates with Google on your behalf?

This won't work since the data you send to the server is encrypted with the certificate from the server.

TIP: So what if the router sends its own "fake certificate"?

That won't work either. All certificates are signed by a "certificate authority" indicating that a google.com certificate is valid.

TIP: What if I was able to get your fake certificate authorized by a real certificate authority?

**that's a problem!**

it's obviously hard to do but if someone was able to do this he could execute a "man in the middle" attack as described above. People were able to fool certificate authorities in the past and gain fake certificates using various methods so this is possible and probably doable for any government level attacker.

==== Certificate pinning

This is the attack certificate pinning (or SSL pinning) aims to prevent. You code into your app the "fingerprint" of the certificate that's "good" and thus prevent the app from working when the certificate is changed. This might break the app if you replace the certificate at some point but that might be reasonable in such a case.

To do this you've a https://github.com/codenameone/SSLCertificateFingerprint/[cn1lib]. that fetches the certificate fingerprint from the server, you can check this fingerprint against a list of "authorized" keys to decide whether it's valid. You can install the `SSLCertificateFingerprint` from the extensions section in #Codename One Settings# and use something like this to verify your server:

[source,java]
----
if(CheckCert.isCertCheckingSupported()) {
    String f = CheckCert.getFingerprint(myHttpsURL);
    if(validKeysList.contains(f)) {
        // OK it's a good certificate proceed
    } else {
       if(Dialog.show("Security Warning", "WARNING: it is possible your commmunications are being tampered! We suggest quitting the app at once!", "Quit", "Continue")) {
          Display.getInstance().exitApplication();
       }
    }
} else {
    // certificate fingerprint checking isn't supported on this platform... It's your decision whether to proceed or not
}
----

Notice that once connection is established you don't need to verify again for the current application run.
