/*
 * Copyright (c) 2026, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Codename One through http://www.codenameone.com/ if you
 * need additional information or have any questions.
 */
package com.codename1.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/// Designates the primary-key field of an `@Entity`. Exactly one field per
/// entity must carry `@Id`. The field type may be `long`, `int`, `String`, or
/// a `Property` wrapper of one of those (`short` is also accepted on the
/// backend).
@Retention(RetentionPolicy.CLASS)
@Target(ElementType.FIELD)
@com.codename1.impl.SharedWithBackend
public @interface Id {
    /// When true (the default) the database assigns the key and the generated
    /// dao reads it back into the field after an insert. Set false when the
    /// application assigns its own keys (UUIDs, server-issued ids, ...).
    ///
    /// How the column is declared and how the key comes back is the engine's
    /// business: SQLite gets `INTEGER PRIMARY KEY AUTOINCREMENT` and
    /// `last_insert_rowid()`, MySQL gets `AUTO_INCREMENT` and `LAST_INSERT_ID()`,
    /// PostgreSQL gets a `GENERATED BY DEFAULT AS IDENTITY` column and an
    /// `INSERT ... RETURNING`.
    boolean autoIncrement() default true;
}
