/*
 * Copyright (c) 2026, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Codename One through http://www.codenameone.com/ if you
 * need additional information or have any questions.
 */
package com.codename1.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/// Marks a `@Bind` field whose component must hold a non-empty value. The
/// binder generated by the Codename One Maven plugin installs a
/// `com.codename1.ui.validation.LengthConstraint(1)` on the matching component
/// and wires it into the `Validator` returned by `Binding#getValidator()`.
///
/// ```java
/// @Bindable
/// public class SignupModel {
///     @Bind(name="userField") @Required
///     private String user;
/// }
/// ```
///
/// Stack with other validation annotations -- the constraints are combined
/// (AND) via `Validator.addConstraint(Component, Constraint...)`. The first
/// failing constraint's message is shown.
@Retention(RetentionPolicy.CLASS)
@Target(ElementType.FIELD)
public @interface Required {
    /// Override the default error message ("A value is required").
    String message() default "";
}
