/*
 * Copyright (c) 2008-2026, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Codename One through http://www.codenameone.com/ if you
 * need additional information or have any questions.
 */
package com.codename1.security;

import com.codename1.io.Util;

/// Generates fresh cryptographic key material. AES keys are pulled directly
/// from [SecureRandom]; RSA key pairs are generated by the platform's native
/// crypto provider.
///
/// #### Example
///
/// ```java
/// SecretKey aes = KeyGenerator.aes(256);   // AES-256
/// KeyPair   rsa = KeyGenerator.rsa(2048);  // RSA-2048
/// ```
public final class KeyGenerator {
    private KeyGenerator() {}

    /// Generates a fresh AES key of the given bit length. Valid lengths are
    /// 128, 192 and 256 bits.
    public static SecretKey aes(int bits) {
        if (bits != 128 && bits != 192 && bits != 256) {
            throw new CryptoException("invalid AES key size: " + bits + " (must be 128, 192 or 256)");
        }
        byte[] key = Util.generateSymmetricKey(bits / 8);
        return new SecretKey("AES", key);
    }

    /// Generates a fresh HMAC key of the given bit length. By convention,
    /// HMAC keys should be at least as long as the hash output.
    public static SecretKey hmac(int bits) {
        if (bits <= 0 || (bits & 7) != 0) {
            throw new CryptoException("HMAC key size must be a positive multiple of 8");
        }
        byte[] key = Util.generateSymmetricKey(bits / 8);
        return new SecretKey("HMAC", key);
    }

    /// Generates a fresh RSA key pair of the given size in bits. 2048 is the
    /// modern minimum; 3072 / 4096 for higher security margins. Generating a
    /// 4096-bit RSA key can take several seconds -- call from a background
    /// thread.
    public static KeyPair rsa(int bits) {
        if (bits < 1024 || (bits & 7) != 0) {
            throw new CryptoException("invalid RSA key size: " + bits);
        }
        try {
            byte[][] pair = Util.generateRsaKeyPair(bits);
            PublicKey pub = PublicKey.fromX509(PublicKey.RSA, pair[0]);
            PrivateKey priv = PrivateKey.fromPkcs8(PublicKey.RSA, pair[1]);
            return new KeyPair(pub, priv);
        } catch (RuntimeException re) {
            throw new CryptoException(re.getMessage(), re);
        }
    }
}
