codename1.packageName=com.codename1.settings
codename1.mainName=CodenameOneSettings
codename1.displayName=Codename One Settings
codename1.version=1.0
codename1.vendor=Codename One
codename1.icon=icon.png
codename1.cssTheme=true
codename1.arg.java.version=17
codename1.arg.nativeTheme=modern
codename1.arg.ios.themeMode=modern
codename1.arg.and.themeMode=modern
codename1.arg.desktop.width=1260
codename1.arg.desktop.height=820
codename1.arg.desktop.titleBar=native
codename1.arg.desktop.interactiveScrollbars=true
