= Codename One Project

This is a multi-module maven project for building a Codename One application. Codename One applications written in Java and/or Kotlin, and are built as native apps and can be built and deployed to iOS, Android, Mac, Windows, Linux, and also to the Web.

== Getting Started

Use a project JDK that supports the Java version in `common/pom.xml` (17 for a
Java 17 project). Configure both the IDE project SDK and its Maven runner; a bundled
IDE runtime does not necessarily configure terminal Java. Set `JAVA_HOME` and check
`.\mvnw.cmd -v` on Windows or `./mvnw -v` on macOS/Linux.

Extract the entire project, then open its root `pom.xml` as Maven. Run launchers from
a terminal so errors remain visible. Windows PowerShell and Command Prompt use
`.\build.bat javascript_cloud`; macOS/Linux use `./build.sh javascript_cloud` to submit
a hosted JavaScript build. Complete browser login when prompted. The first build
may take several minutes to download dependencies. Correct connection/proxy errors
and retry the same command.

`javascript` builds locally; `javascript_cloud` submits to the build server.
The no-argument `build` default makes a local JAR and `run` starts the local simulator.
These local operations do not create a cloud build.

=== Java

If you plan to use Java as your primary language, https://shannah.github.io/cn1-maven-archetypes/cn1app-archetype-tutorial/getting-started.html[start here].

=== Kotlin

If you plan to use Kotlin as your primary language, https://shannah.github.io/cn1app-archetype-kotlin-template/getting-started.html[start here].


== Eclipse Users

IMPORTANT: If you use Eclipse as your IDE, **read this first**

The _tools/eclipse_ directory contains eclipse ".launch" files that will add common Maven goals as menu items inside Eclipse.

After the Maven import, choose *File > Import > Run/Debug > Launch Configurations*,
select `tools/eclipse`, and import the launch files before using *Run > Run Configurations*.

=== Additional Steps for CodeRAD projects

CodeRAD includes an annotation processor that needs to be activated. There are a few additional steps required to enable this in Eclipse.

. Add `org.eclipse.m2e.apt.mode=jdt_apt` to the `./common/.settings/org.eclipse.m2e.apt.prefs`
. Add `target/generated-sources/rad-views` to the .classpath.

See https://github.com/codenameone/CodenameOne/issues/3724[this issue] for more details.

== NetBeans Users

This project is a multi-module Maven project that was generated from a Maven archetype.

== IntelliJ Users

The project should work in IntelliJ out of the box.  No need to copy any files.

== Signing

Use the Certificate Wizard to configure Apple signing assets, Android keystores, and desktop signing settings:

----
mvn cn1:certificatewizard
----

Generated IDE projects include a Certificate Wizard action under their tools/favorites area.

== Help and Support

See the https://www.codenameone.com[Codename One Web Site].
