= Codename One Project

This is a multi-module maven project for building a Codename One application. Codename One applications written in Java and/or Kotlin, and are built as native apps and can be built and deployed to iOS, Android, Mac, Windows, Linux, and also to the Web.

== Getting Started

=== Java

If you plan to use Java as your primary language, https://shannah.github.io/cn1-maven-archetypes/cn1app-archetype-tutorial/getting-started.html[start here].

=== Kotlin

If you plan to use Kotlin as your primary language, https://shannah.github.io/cn1app-archetype-kotlin-template/getting-started.html[start here].


== Eclipse Users

IMPORTANT: If you use Eclipse as your IDE, **read this first**

The _tools/eclipse_ directory contains eclipse ".launch" files that will add common Maven goals as menu items inside Eclipse.

**After importing this project into Eclipse, you should import the launch files.**

=== Additional Steps for CodeRAD projects

CodeRAD includes an annotation processor that needs to be activated. There are a few additional steps required to enable this in Eclipse.

. Add `org.eclipse.m2e.apt.mode=jdt_apt` to the `./common/.settings/org.eclipse.m2e.apt.prefs`
. Add `target/generated-sources/rad-views` to the .classpath.

See https://github.com/codenameone/CodenameOne/issues/3724[this issue] for more details.

== NetBeans Users

This project is a multi-module Maven project that was generated from a Maven archetype.

== IntelliJ Users

The project should work in IntelliJ out of the box.  No need to copy any files.

== Help and Support

See the https://www.codenameone.com[Codename One Web Site].