codename1.mainName=CertificateWizard
codename1.packageName=com.codename1.certificatewizard
codename1.displayName=Codename One Certificate Wizard
codename1.version=1.0
codename1.vendor=CodenameOne
codename1.secondaryTitle=Certificate Wizard
codename1.icon=icon.png
codename1.cssTheme=true
codename1.arg.java.version=17
codename1.arg.nativeTheme=modern
codename1.arg.ios.themeMode=modern
codename1.arg.and.themeMode=modern
codename1.arg.desktop.width=1260
codename1.arg.desktop.height=820
codename1.arg.desktop.titleBar=native
codename1.kotlin=false
