// Generated by cn1:generate-graphql.
package com.example.starwars;

import com.codename1.annotations.JsonProperty;
import com.codename1.annotations.Mapped;

@Mapped
public record AddReviewData(
    AddReviewData_CreateReview createReview
) {}
