/*
 * Copyright (c) 2026, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Codename One through http://www.codenameone.com/ if you
 * need additional information or have any questions.
 */
package com.codename1.android.rescompiler;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.Charset;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/// Emits the Java half of the compiler's output: the R classes and the
/// generated `AndroidApp` subclass.
final class JavaWriter {

    static final String RUNTIME = "com.codename1.androidcompat.runtime";

    private final SymbolTable symbols;
    private final String local;

    JavaWriter(SymbolTable symbols, String local) {
        this.symbols = symbols;
        this.local = local;
    }

    /// Writes `pkg.R`. Application R fields are `final` so `switch (v.getId())`
    /// compiles, exactly as in an Android application module.
    File writeR(File outDir, String pkg, boolean app) throws IOException {
        Map<String, Map<String, Integer>> byType = new TreeMap<String, Map<String, Integer>>();
        for (Map.Entry<String, Integer> e : symbols.entries(local).entrySet()) {
            String[] tn = e.getKey().split("/", 2);
            Map<String, Integer> m = byType.get(tn[0]);
            if (m == null) {
                m = new TreeMap<String, Integer>();
                byType.put(tn[0], m);
            }
            m.put(fieldName(tn[1]), e.getValue());
        }
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by the Codename One Android resource compiler. Do not edit.\n");
        sb.append("package ").append(pkg).append(";\n\n");
        sb.append("public final class R {\n");
        sb.append("    private R() {\n    }\n");
        for (Map.Entry<String, Map<String, Integer>> t : byType.entrySet()) {
            sb.append("\n    public static final class ").append(t.getKey()).append(" {\n");
            sb.append("        private ").append(t.getKey()).append("() {\n        }\n");
            for (Map.Entry<String, Integer> f : t.getValue().entrySet()) {
                sb.append("        public static final int ").append(f.getKey()).append(" = 0x")
                        .append(hex8(f.getValue())).append(";\n");
            }
            sb.append("    }\n");
        }
        Map<String, List<String>> styleables = symbols.styleables(local);
        if (!styleables.isEmpty()) {
            sb.append("\n    public static final class styleable {\n");
            sb.append("        private styleable() {\n        }\n");
            for (Map.Entry<String, List<String>> s : styleables.entrySet()) {
                // Android orders a styleable's attrs by id, and
                // obtainStyledAttributes relies on that order.
                List<String> attrs = new ArrayList<String>(s.getValue());
                Collections.sort(attrs, new Comparator<String>() {
                    @Override
                    public int compare(String a, String b) {
                        long x = symbols.attrId(a) & 0xffffffffL;
                        long y = symbols.attrId(b) & 0xffffffffL;
                        return x < y ? -1 : (x == y ? 0 : 1);
                    }
                });
                String field = fieldName(s.getKey());
                sb.append("        public static final int[] ").append(field).append(" = {");
                for (int i = 0; i < attrs.size(); i++) {
                    sb.append(i == 0 ? "" : ", ").append("0x").append(hex8(symbols.attrId(attrs.get(i))));
                }
                sb.append("};\n");
                for (int i = 0; i < attrs.size(); i++) {
                    String a = attrs.get(i);
                    int colon = a.indexOf(':');
                    String an = a.substring(colon + 1);
                    String prefix = a.startsWith(SymbolTable.FRAMEWORK + ":") && !local.equals(SymbolTable.FRAMEWORK)
                            ? "android_" : "";
                    if (local.equals(SymbolTable.FRAMEWORK)) {
                        prefix = "";
                    }
                    sb.append("        public static final int ").append(field).append('_').append(prefix)
                            .append(fieldName(an)).append(" = ").append(i).append(";\n");
                }
            }
            sb.append("    }\n");
        }
        sb.append("}\n");
        return write(outDir, pkg, "R", sb.toString());
    }

    File writeAppImpl(File outDir, String pkg, String cls, String table, ManifestInfo m,
                      Map<String, String> tagToClass) throws IOException {
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by the Codename One Android resource compiler. Do not edit.\n");
        sb.append("package ").append(pkg).append(";\n\n");
        sb.append("/// The application-specific half of the Android compatibility runtime:\n");
        sb.append("/// `new` for every view class the layouts name and every activity the\n");
        sb.append("/// manifest declares, so nothing is instantiated by reflection.\n");
        sb.append("public final class ").append(cls).append(" extends ").append(RUNTIME).append(".AndroidApp {\n\n");
        List<String> tags = new ArrayList<String>(tagToClass.keySet());
        sb.append("    private static final String[] VIEW_TAGS = {");
        for (int i = 0; i < tags.size(); i++) {
            sb.append(i == 0 ? "" : ", ").append(quote(tags.get(i)));
        }
        sb.append("};\n\n");
        String appPkg = m == null ? "" : m.packageName;
        sb.append("    public ").append(cls).append("() {\n");
        sb.append("        super(").append(quote(table)).append(", ").append(quote(appPkg)).append(");\n");
        if (m != null) {
            sb.append("        application(").append(refOrZero(m.appTheme)).append(", ").append(refOrZero(m.appLabel))
                    .append(", ").append(literalOrNull(m.appLabel)).append(", ").append(refOrZero(m.appIcon)).append(");\n");
            if (m.versionName != null) {
                sb.append("        version(").append(quote(m.versionName)).append(", ").append(m.versionCode).append(");\n");
            }
            for (ManifestInfo.Activity a : m.activities) {
                sb.append("        activity(").append(a.className).append(".class, ").append(quote(a.className))
                        .append(", ").append(refOrZero(a.theme)).append(", ").append(refOrZero(a.label))
                        .append(", ").append(literalOrNull(a.label)).append(", ")
                        .append(a.screenOrientation == null ? "null" : quote(a.screenOrientation)).append(", ")
                        .append(a.windowSoftInputMode == null ? "null" : quote(a.windowSoftInputMode)).append(", ")
                        .append(a == m.launcher()).append(");\n");
                if (a.configChanges != 0) {
                    sb.append("        configChanges(").append(a.className).append(".class, 0x")
                            .append(hex8(a.configChanges)).append(");\n");
                }
                if (a.launchMode != 0) {
                    sb.append("        launchMode(").append(a.className).append(".class, ")
                            .append(a.launchMode).append(");\n");
                }
                if (a.noHistory) {
                    sb.append("        noHistory(").append(a.className).append(".class);\n");
                }
                for (ManifestInfo.IntentFilter f : a.filters) {
                    writeIntentFilter(sb, a.className, f);
                }
            }
        }
        sb.append("    }\n\n");

        sb.append("    @Override\n    public String[] viewTags() {\n        return VIEW_TAGS;\n    }\n\n");

        sb.append("    @Override\n    public android.view.View createView(int index, android.content.Context context,\n");
        sb.append("            android.util.AttributeSet attrs) {\n");
        sb.append("        switch (index) {\n");
        for (int i = 0; i < tags.size(); i++) {
            sb.append("            case ").append(i).append(":\n");
            sb.append("                return new ").append(tagToClass.get(tags.get(i))).append("(context, attrs);\n");
        }
        sb.append("            default:\n                return null;\n        }\n    }\n\n");

        sb.append("    @Override\n    public android.app.Activity createActivity(Class<?> type) {\n");
        if (m != null) {
            for (ManifestInfo.Activity a : m.activities) {
                sb.append("        if (type == ").append(a.className).append(".class) {\n");
                sb.append("            return new ").append(a.className).append("();\n        }\n");
            }
        }
        sb.append("        return null;\n    }\n\n");

        sb.append("    @Override\n    public android.app.Application createApplication() {\n");
        String appCls = m == null || m.applicationClass == null ? "android.app.Application" : m.applicationClass;
        sb.append("        return new ").append(appCls).append("();\n    }\n}\n");
        return write(outDir, pkg, cls, sb.toString());
    }

    private static String refOrZero(Value v) {
        return v != null && v.type == Value.TYPE_REFERENCE ? "0x" + hex8(v.data) : "0";
    }

    private static String literalOrNull(Value v) {
        return v != null && v.type == Value.TYPE_STRING ? quote(v.string) : "null";
    }

    static String fieldName(String resName) {
        return resName.replace('.', '_').replace('-', '_').replace(':', '_');
    }

    static String hex8(int v) {
        String h = Integer.toHexString(v);
        while (h.length() < 8) {
            h = "0" + h;
        }
        return h;
    }

    /// A Java string literal. Non-ASCII is written as escapes: generated
    /// sources must stay ASCII like every other source in a Codename One build.
    /// One manifest `<intent-filter>` as the `IntentFilter` calls that
    /// rebuild it on the device, in a block of its own.
    private static void writeIntentFilter(StringBuilder sb, String activity, ManifestInfo.IntentFilter f) {
        sb.append("        {\n");
        sb.append("            android.content.IntentFilter f = intentFilter(").append(activity).append(".class);\n");
        for (String v : f.actions) {
            sb.append("            f.addAction(").append(quote(v)).append(");\n");
        }
        for (String v : f.categories) {
            sb.append("            f.addCategory(").append(quote(v)).append(");\n");
        }
        for (String v : f.schemes) {
            sb.append("            f.addDataScheme(").append(quote(v)).append(");\n");
        }
        for (ManifestInfo.DataPattern v : f.schemeSpecificParts) {
            sb.append("            f.addDataSchemeSpecificPart(").append(quote(v.pattern)).append(", ").append(v.type)
                    .append(");\n");
        }
        for (ManifestInfo.Authority v : f.authorities) {
            sb.append("            f.addDataAuthority(").append(quote(v.host)).append(", ")
                    .append(v.port == null ? "null" : quote(v.port)).append(");\n");
        }
        for (ManifestInfo.DataPattern v : f.paths) {
            sb.append("            f.addDataPath(").append(quote(v.pattern)).append(", ").append(v.type).append(");\n");
        }
        for (String v : f.types) {
            sb.append("            f.addDataType(").append(quote(v)).append(");\n");
        }
        sb.append("        }\n");
    }

    static String quote(String s) {
        StringBuilder sb = new StringBuilder("\"");
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '"':
                    sb.append("\\\"");
                    break;
                case '\\':
                    sb.append("\\\\");
                    break;
                case '\n':
                    sb.append("\\n");
                    break;
                case '\r':
                    sb.append("\\r");
                    break;
                case '\t':
                    sb.append("\\t");
                    break;
                default:
                    if (c < 0x20 || c > 0x7e) {
                        String h = Integer.toHexString(c);
                        sb.append("\\u");
                        for (int p = h.length(); p < 4; p++) {
                            sb.append('0');
                        }
                        sb.append(h);
                    } else {
                        sb.append(c);
                    }
            }
        }
        return sb.append('"').toString();
    }

    private static File write(File outDir, String pkg, String cls, String content) throws IOException {
        File dir = new File(outDir, pkg.replace('.', File.separatorChar));
        ResourceCompiler.ensureDir(dir);
        File f = new File(dir, cls + ".java");
        byte[] bytes = content.getBytes(Charset.forName("UTF-8"));
        if (f.isFile() && f.length() == bytes.length) {
            // Leave an unchanged file alone so incremental javac stays warm.
            byte[] old = java.nio.file.Files.readAllBytes(f.toPath());
            if (java.util.Arrays.equals(old, bytes)) {
                return f;
            }
        }
        Writer w = new OutputStreamWriter(new FileOutputStream(f), Charset.forName("UTF-8"));
        try {
            w.write(content);
        } finally {
            w.close();
        }
        return f;
    }
}
