/*
 * Copyright (c) 2008, 2010, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores
 * CA 94065 USA or visit www.oracle.com if you need additional information or
 * have any questions.
 */
package com.codename1.io;

import com.codename1.processing.Result;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.Reader;
import java.util.ArrayList;
import java.util.Hashtable;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Vector;

/// Fast and dirty parser for JSON content on the web, it essentially returns
/// a `java.util.Map` object containing the object fields mapped to their values. If the value is
/// a nested object a nested `java.util.Map`/`java.util.List` is returned.
///
/// The `JSONParser` returns a `Map` which is great if the root object is a `Map` but in
/// some cases its a list of elements (as is the case above). In this case a special case `"root"` element is
/// created to contain the actual list of elements. See the sample below for exact usage of this.
///
/// The sample below includes JSON from [https://anapioficeandfire.com/](https://anapioficeandfire.com/)
/// generated by the query [http://www.anapioficeandfire.com/api/characters?page=5&pageSize=3](http://www.anapioficeandfire.com/api/characters?page=5&pageSize=3):
///
/// ```java
/// // File: JSONParsingSample.java
/// Form hi = new Form("JSON Parsing", new BoxLayout(BoxLayout.Y_AXIS));
/// JSONParser json = new JSONParser();
/// try(Reader r = new InputStreamReader(Display.getInstance().getResourceAsStream(getClass(), "/anapioficeandfire.json"), "UTF-8")) {
///     Map data = json.parseJSON(r);
///     java.util.List<Map<String, Object>> content = (java.util.List<Map<String, Object>>)data.get("root");
///     for(Map obj : content) {
///         String url = (String)obj.get("url");
///         String name = (String)obj.get("name");
///         java.util.List titles = (java.util.List)obj.get("titles");
///         if(name == null || name.length() == 0) {
///             java.util.List aliases = (java.util.List)obj.get("aliases");
///             if(aliases != null && aliases.size() > 0) {
///                 name = aliases.get(0);
///             }
///         }
///         MultiButton mb = new MultiButton(name);
///         if(titles != null && titles.size() > 0) {
///             mb.setTextLine2(titles.get(0));
///         }
///         mb.addActionListener((e) -> Display.getInstance().execute(url));
///         hi.add(mb);
///     }
/// } catch(IOException err) {
///     Log.e(err);
/// }
/// hi.show();
/// ```
///
/// ```json
/// // File: anapioficeandfire.json
/// [
///   {
///     "url": "http://www.anapioficeandfire.com/api/characters/13",
///     "name": "Chayle",
///     "culture": "",
///     "born": "",
///     "died": "In 299 AC, at Winterfell",
///     "titles": [
///       "Septon"
///     ],
///     "aliases": [],
///     "father": "",
///     "mother": "",
///     "spouse": "",
///     "allegiances": [],
///     "books": [
///       "http://www.anapioficeandfire.com/api/books/1",
///       "http://www.anapioficeandfire.com/api/books/2",
///       "http://www.anapioficeandfire.com/api/books/3"
///     ],
///     "povBooks": [],
///     "tvSeries": [],
///     "playedBy": []
///   },
///   {
///     "url": "http://www.anapioficeandfire.com/api/characters/14",
///     "name": "Gillam",
///     "culture": "",
///     "born": "",
///     "died": "",
///     "titles": [
///       "Brother"
///     ],
///     "aliases": [],
///     "father": "",
///     "mother": "",
///     "spouse": "",
///     "allegiances": [],
///     "books": [
///       "http://www.anapioficeandfire.com/api/books/5"
///     ],
///     "povBooks": [],
///     "tvSeries": [],
///     "playedBy": []
///   },
///   {
///     "url": "http://www.anapioficeandfire.com/api/characters/15",
///     "name": "High Septon",
///     "culture": "",
///     "born": "",
///     "died": "",
///     "titles": [
///       "High Septon",
///       "His High Holiness",
///       "Father of the Faithful",
///       "Voice of the Seven on Earth"
///     ],
///     "aliases": [
///       "The High Sparrow"
///     ],
///     "father": "",
///     "mother": "",
///     "spouse": "",
///     "allegiances": [],
///     "books": [
///       "http://www.anapioficeandfire.com/api/books/5",
///       "http://www.anapioficeandfire.com/api/books/8"
///     ],
///     "povBooks": [],
///     "tvSeries": [
///       "Season 5"
///     ],
///     "playedBy": [
///       "Jonathan Pryce"
///     ]
///   }
/// ]
/// ```
///
/// The sample  code below fetches a page of data from the nestoria housing listing API as a list of Map elements.
/// You can see instructions on how to display the data in the `com.codename1.components.InfiniteScrollAdapter`
/// class.
///
/// ```java
/// int pageNumber = 1;
/// java.util.List<Map<String, Object>> fetchPropertyData(String text) {
///     try {
///         ConnectionRequest r = new ConnectionRequest();
///         r.setPost(false);
///         r.setUrl("http://api.nestoria.co.uk/api");
///         r.addArgument("pretty", "0");
///         r.addArgument("action", "search_listings");
///         r.addArgument("encoding", "json");
///         r.addArgument("listing_type", "buy");
///         r.addArgument("page", "" + pageNumber);
///         pageNumber++;
///         r.addArgument("country", "uk");
///         r.addArgument("place_name", text);
///         NetworkManager.getInstance().addToQueueAndWait(r);
///         Map result = new JSONParser().parseJSON(new InputStreamReader(new ByteArrayInputStream(r.getResponseData()), "UTF-8"));
///         Map response = (Map)result.get("response");
///         return (java.util.List<Map<String, Object>>)response.get("listings");
///     } catch(Exception err) {
///         Log.e(err);
///         return null;
///     }
/// }
/// ```
///
/// @author Shai Almog
public class JSONParser implements JSONParseCallback {

    private static boolean useLongsDefault;
    /// Indicates that the parser will generate Boolean objects and not just Strings for boolean values
    private static boolean useBooleanDefault;
    private static boolean includeNullsDefault;
    private boolean useLongs = useLongsDefault;
    private boolean useBoolean = useBooleanDefault;
    private boolean includeNulls = includeNullsDefault;
    private boolean modern;
    private Map<String, Object> state;
    private java.util.List<Object> parseStack;
    private String currentKey;
    /// If strict is set to false, then the parser will attempt to sanitize the JSON
    /// input before parsing.  I.e. it will accept invalid JSON, such as unquoted keys, etc..
    private boolean strict = true;

    /// Checks whether JSONParser instances will use longs to represent numeric values by default. This is just a
    /// global default setting.  You should use `#isUseLongsInstance()` to check the status for a particular
    /// JSONParser object.
    ///
    /// #### Returns
    ///
    /// the useLongsDefault
    ///
    /// #### Deprecated
    ///
    /// Use `#isUseLongsInstance()` to check whether the current JSONParser uses longs.
    public static boolean isUseLongs() {
        return useLongsDefault;
    }

    /// Indicates that the parser will generate long objects and not just doubles for numeric values.
    ///
    /// **Warning:**  This method will affect ALL JSONParser instances in the application.  Prefer to use `#setUseLongsInstance(boolean)`
    /// to only affect the behaviour of the particular JSONParser instance.
    ///
    /// #### Parameters
    ///
    /// - `aUseLongsDefault`: the useLongsDefault to set
    ///
    /// #### Deprecated
    ///
    /// Use `#setUseLongsInstance(boolean)`
    public static void setUseLongs(boolean aUseLongsDefault) {
        useLongsDefault = aUseLongsDefault;
    }

    /// Checks the default setting for `#isIncludeNullsInstance()`.
    ///
    /// #### Returns
    ///
    /// the includeNullsDefault The global default setting for `#isIncludeNullsInstance()`.
    ///
    /// #### Deprecated
    ///
    /// Use `#isIncludeNullsInstance()` instead.
    public static boolean isIncludeNulls() {
        return includeNullsDefault;
    }

    /// Sets the global default settings for `#isIncludeNullsInstance()`.
    ///
    /// #### Parameters
    ///
    /// - `aIncludeNullsDefault`: the includeNullsDefault to set
    ///
    /// #### Deprecated
    ///
    /// Use `#setIncludeNullsInstance(boolean)` instead.
    public static void setIncludeNulls(boolean aIncludeNullsDefault) {
        includeNullsDefault = aIncludeNullsDefault;
    }

    /// Global default setting for `#isUseBooleanInstance()`.
    ///
    /// #### Returns
    ///
    /// the useBooleanDefault
    ///
    /// #### Deprecated
    ///
    /// Use `#isUseBooleanInstance()` instead.
    public static boolean isUseBoolean() {
        return useBooleanDefault;
    }

    /// Sets the global default value for `#isUseBooleanInstance()`
    ///
    /// #### Parameters
    ///
    /// - `aUseBooleanDefault`: the useBooleanDefault to set
    ///
    /// #### Deprecated
    ///
    /// Use `#setUseBooleanInstance(boolean)` instead.
    public static void setUseBoolean(boolean aUseBooleanDefault) {
        useBooleanDefault = aUseBooleanDefault;
    }

    private static boolean useLongs(JSONParseCallback callback) {
        if (callback instanceof JSONParser) {
            return ((JSONParser) callback).isUseLongsInstance();
        }
        return useLongsDefault;
    }

    private static boolean useBoolean(JSONParseCallback callback) {
        if (callback instanceof JSONParser) {
            return ((JSONParser) callback).isUseBooleanInstance();
        }
        return useBooleanDefault;
    }

    /// Static method! Parses the given input stream and fires the data into the given callback.
    ///
    /// #### Parameters
    ///
    /// - `i`: the reader
    ///
    /// - `callback`: a generic callback to receive the parse events
    ///
    /// #### Throws
    ///
    /// - `IOException`: if thrown by the stream
    @SuppressWarnings("PMD.SwitchStmtsShouldHaveDefault")
    public static void parse(Reader i, JSONParseCallback callback) throws IOException {
        boolean quoteMode = false;
        ReaderClass rc = new ReaderClass();
        rc.buffOffset = 0;
        rc.buffSize = -1;
        int row = 1;
        int column = 1;
        StringBuilder currentToken = new StringBuilder();
        KeyStack blocks = new KeyStack();
        String currentBlock = "";
        String lastKey = null;
        try {
            while (callback.isAlive()) {
                int currentChar = rc.read(i);
                if (currentChar < 0) {
                    return;
                }
                char c = (char) currentChar;
                if (c == '\n') {
                    row++;
                    column = 0;
                } else {
                    column++;
                }

                if (quoteMode) {
                    switch (c) {
                        case '"':
                            String v = currentToken.toString();
                            callback.stringToken(v);
                            if (lastKey != null) {
                                callback.keyValue(lastKey, v);
                                lastKey = null;
                            } else {
                                lastKey = v;
                            }
                            currentToken.setLength(0);
                            quoteMode = false;
                            continue;
                        case '\\':
                            c = (char) rc.read(i);
                            if (c == 'u') {
                                String unicode = "" + ((char) rc.read(i)) + ((char) rc.read(i)) + ((char) rc.read(i)) + ((char) rc.read(i));
                                try {
                                    c = (char) Integer.parseInt(unicode, 16);
                                } catch (NumberFormatException err) {
                                    // problem in parsing the u notation!
                                    Log.e(err);
                                    Log.p("Error in parsing \\u" + unicode);
                                }
                            } else {
                                switch (c) {
                                    case 'n':
                                        currentToken.append('\n');
                                        continue;
                                    case 't':
                                        currentToken.append('\t');
                                        continue;
                                    case 'r':
                                        currentToken.append('\r');
                                        continue;
                                }
                            }
                            currentToken.append(c);
                            continue;
                    }
                    currentToken.append(c);
                } else {
                    switch (c) {
                        case 'n':
                            // check for null
                            char u = (char) rc.read(i);
                            char l = (char) rc.read(i);
                            char l2 = (char) rc.read(i);
                            if (u == 'u' && l == 'l' && l2 == 'l') {
                                // this is null
                                callback.stringToken(null);
                                if (lastKey != null) {
                                    callback.keyValue(lastKey, null);
                                    lastKey = null;
                                }
                            } else {
                                // parsing error....
                                Log.p("Expected null for key value while parsing JSON token at row: " + row + " column: " + column + " buffer: " + currentToken);
                            }

                            continue;
                        case 't':
                            // check for true
                            char a1 = (char) rc.read(i);
                            char a2 = (char) rc.read(i);
                            char a3 = (char) rc.read(i);
                            if (a1 == 'r' && a2 == 'u' && a3 == 'e') {
                                if (useBoolean(callback)) {
                                    callback.booleanToken(true);
                                } else {
                                    callback.stringToken("true");
                                }
                                if (lastKey != null) {
                                    callback.keyValue(lastKey, "true");
                                    lastKey = null;
                                }
                            } else {
                                // parsing error....
                                Log.p("Expected true for key value while parsing JSON token at row: " + row + " column: " + column + " buffer: " + currentToken);
                            }

                            continue;
                        case 'f':
                            // this can either be the start of "false" or the end of a
                            // fraction number...
                            if (currentToken.length() > 0) {
                                currentToken.append('f');
                                continue;
                            }
                            // check for false
                            char b1 = (char) rc.read(i);
                            char b2 = (char) rc.read(i);
                            char b3 = (char) rc.read(i);
                            char b4 = (char) rc.read(i);
                            if (b1 == 'a' && b2 == 'l' && b3 == 's' && b4 == 'e') {
                                if (useBoolean(callback)) {
                                    callback.booleanToken(false);
                                } else {
                                    callback.stringToken("false");
                                }
                                if (lastKey != null) {
                                    callback.keyValue(lastKey, "false");
                                    lastKey = null;
                                }
                            } else {
                                // parsing error....
                                Log.p("Expected false for key value while parsing JSON token at row: " + row + " column: " + column + " buffer: " + currentToken);
                            }

                            continue;
                        case '{':
                            if (lastKey == null) {
                                if (blocks.isEmpty()) {
                                    lastKey = "root";
                                } else {
                                    lastKey = blocks.peek();
                                }
                            }
                            blocks.push(lastKey);
                            callback.startBlock(lastKey);
                            lastKey = null;
                            continue;
                        case '}':
                            if (currentToken.length() > 0) {
                                try {
                                    String ct = currentToken.toString();
                                    if (useLongs(callback)) {
                                        if (ct.indexOf('.') > -1) {
                                            callback.numericToken(Double.parseDouble(ct));
                                        } else {
                                            callback.longToken(Long.parseLong(ct));
                                        }
                                    } else {
                                        callback.numericToken(Double.parseDouble(ct));
                                    }
                                    if (lastKey != null) {
                                        callback.keyValue(lastKey, currentToken.toString());
                                        lastKey = null;
                                        currentToken.setLength(0);
                                    }

                                } catch (NumberFormatException err) {
                                    Log.e(err);
                                    // this isn't a number!
                                }
                            }
                            currentBlock = blocks.pop();
                            callback.endBlock(currentBlock);
                            lastKey = null;
                            continue;
                        case '[':
                            blocks.push(lastKey);

                            callback.startArray(lastKey);
                            lastKey = null;
                            continue;
                        case ']':
                            if (currentToken.length() > 0) {
                                try {
                                    String ct = currentToken.toString();
                                    if (useLongs(callback)) {
                                        if (ct.indexOf('.') > -1) {
                                            callback.numericToken(Double.parseDouble(ct));
                                        } else {
                                            callback.longToken(Long.parseLong(ct));
                                        }
                                    } else {
                                        callback.numericToken(Double.parseDouble(ct));
                                    }
                                    if (lastKey != null) {
                                        callback.keyValue(lastKey, currentToken.toString());
                                        lastKey = null;
                                    }
                                } catch (NumberFormatException err) { // NOPMD EmptyCatchBlock
                                    // this isn't a number!
                                }
                            }
                            currentToken.setLength(0);

                            currentBlock = blocks.pop();
                            callback.endArray(currentBlock);
                            lastKey = null;
                            continue;
                        case ' ':
                        case '\r':
                        case '\t':
                        case '\n':
                            // whitespace
                            continue;

                        case '"':
                            quoteMode = true;
                            continue;
                        case ':':
                        case ',':
                            if (currentToken.length() > 0) {
                                try {
                                    String ct = currentToken.toString();
                                    if (useLongs(callback)) {
                                        if (ct.indexOf('.') > -1) {
                                            callback.numericToken(Double.parseDouble(ct));
                                        } else {
                                            callback.longToken(Long.parseLong(ct));
                                        }
                                    } else {
                                        callback.numericToken(Double.parseDouble(ct));
                                    }
                                    if (lastKey != null) {
                                        callback.keyValue(lastKey, currentToken.toString());
                                        lastKey = null;
                                    }
                                } catch (NumberFormatException err) { // NOPMD EmptyCatchBlock
                                    // this isn't a number!
                                }
                            }
                            currentToken.setLength(0);
                            continue;
                        case '0':
                        case '1':
                        case '2':
                        case '3':
                        case '4':
                        case '5':
                        case '6':
                        case '7':
                        case '8':
                        case '9':
                        case '-':
                        case '.':
                        case 'x':
                        case 'd':
                        case 'l':
                        case 'e':
                        case 'E':
                            currentToken.append(c);
                            continue;
                    }
                }
            }
        } catch (IOException err) {
            handleParsingException(i, err, row, column, currentToken);
        } catch (RuntimeException err) {
            handleParsingException(i, err, row, column, currentToken);
        }
    }

    private static void handleParsingException(Reader i, Exception err, int row, int column, StringBuilder currentToken) throws IOException {
        Log.e(err);
        Log.p("Exception during JSON parsing at row: " + row + " column: " + column + " buffer: " + currentToken);
        i.close();
    }

    /// Static method to convert the given `java.util.Map` to a valid JSON
    /// representation. The values allowed types are: `java.lang.Number`, `java.lang.String`, `java.lang.Boolean`,
    /// `java.util.List`, `java.util.Map` or null.
    ///
    /// Limited whitespace is inserted be make the resulting JSON string more
    /// readable.
    ///
    /// Simple example of usage:
    ///
    /// ```java
    /// `Map person = new LinkedHashMap<>();
    /// person.put("firstName", "Paco");
    /// person.put("lastName", "Bellz");
    /// person.put("isAlive", true);
    /// person.put("age", 35);
    /// person.put("weight (kg)", 70.7);
    ///
    /// Log.p("--- mapToJson() test");
    /// Log.p("\n" + mapToJson(person));`
    /// ```
    ///
    /// The output will be:
    ///
    /// ```java
    /// `{
    ///  "firstName": "Paco",
    ///  "lastName": "Bellz",
    ///  "isAlive": true,
    ///  "age": 35,
    ///  "weight (kg)": 70.7`
    /// }
    /// ```
    ///
    /// More complex example of usage:
    ///
    /// ```java
    /// `Map phoneNumber1 = new LinkedHashMap<>();
    /// phoneNumber1.put("home", "212 555-1234");
    /// Map phoneNumber2 = new LinkedHashMap<>();
    /// phoneNumber2.put("office", "646 555-4567");
    /// Map phoneNumber3 = new LinkedHashMap<>();
    /// phoneNumber3.put("mobile", "123 456-7890");
    /// Map phoneNumber4 = new LinkedHashMap<>();
    /// phoneNumber4.put("mobile", "06124578965");
    /// ArrayList phoneNumbers = new ArrayList();
    /// ArrayList phoneNumbers2 = new ArrayList();
    /// phoneNumbers.add(phoneNumber1);
    /// phoneNumbers.add(phoneNumber2);
    /// phoneNumbers.add(phoneNumber3);
    /// phoneNumbers2.add(phoneNumber4);
    /// Map address1 = new LinkedHashMap<>();
    /// address1.put("streetAddress", "53, London Street");
    /// address1.put("city", "Paris");
    /// address1.put("state", "FR");
    /// address1.put("postalCode", "54856");
    /// Map address2 = new LinkedHashMap<>();
    /// address2.put("streetAddress", "21 2nd Street");
    /// address2.put("city", "New York");
    /// address2.put("state", "NY");
    /// address2.put("postalCode", "10021-3100");
    /// Map secondPerson = new LinkedHashMap<>();
    /// secondPerson.put("firstName", "Gioia");
    /// secondPerson.put("lastName", "Mia");
    /// secondPerson.put("isAlive", true);
    /// secondPerson.put("age", 34);
    /// secondPerson.put("weight (kg)", 60.2);
    /// secondPerson.put("address", address2);
    /// address2.put("phoneNumbers", phoneNumbers2);
    /// Map firstPerson = new LinkedHashMap<>();
    /// firstPerson.put("firstName", "Paco");
    /// firstPerson.put("lastName", "Bellz");
    /// firstPerson.put("isAlive", true);
    /// firstPerson.put("age", 35);
    /// firstPerson.put("weight (kg)", 70.7);
    /// firstPerson.put("address", address1);
    /// firstPerson.put("partner", secondPerson);
    /// firstPerson.put("children", new ArrayList());
    /// firstPerson.put("extraInfo", null);
    /// firstPerson.put("phoneNumbers", phoneNumbers);
    /// List friends = new ArrayList();
    /// friends.add("Paul");
    /// friends.add("Karl");
    /// friends.add("Mary");
    /// firstPerson.put("onVacation", false);
    /// firstPerson.put("friends", friends);
    ///
    /// Log.p("--- mapToJson() test");
    /// Log.p("\n" + mapToJson(firstPerson));`
    /// ```
    ///
    /// The output will be:
    ///
    /// ```java
    /// `{
    ///  "firstName": "Paco",
    ///  "lastName": "Bellz",
    ///  "isAlive": true,
    ///  "age": 35,
    ///  "weight (kg)": 70.7,
    ///  "address": {
    ///    "streetAddress": "53, London Street",
    ///    "city": "Paris",
    ///    "state": "FR",
    ///    "postalCode": "54856"`,
    ///  "partner": {
    ///    "firstName": "Gioia",
    ///    "lastName": "Mia",
    ///    "isAlive": true,
    ///    "age": 34,
    ///    "weight (kg)": 60.2,
    ///    "address": {
    ///      "streetAddress": "21 2nd Street",
    ///      "city": "New York",
    ///      "state": "NY",
    ///      "postalCode": "10021-3100",
    ///      "phoneNumbers": [{"mobile": "06124578965"}]
    ///    }
    ///  },
    ///  "children": [],
    ///  "extraInfo": null,
    ///  "phoneNumbers": [
    ///    {"home": "212 555-1234"},
    ///    {"office": "646 555-4567"},
    ///    {"mobile": "123 456-7890"}
    ///  ],
    ///  "onVacation": false,
    ///  "friends": [
    ///    "Paul",
    ///    "Karl",
    ///    "Mary"
    ///  ]
    /// }
    /// }
    /// ```
    ///
    /// #### Parameters
    ///
    /// - `map`: The map to be converted to a JSON string
    ///
    /// #### Returns
    ///
    /// The JSON string
    public static String mapToJson(Map<String, ?> map) {
        return Result.fromContent(map).toString();
    }

    /// Convenience: parse a JSON object from a UTF-8 byte array. The
    /// `parseJSON(Reader)` overload is the canonical entry point but
    /// callers that already have bytes in hand don't need to wire up
    /// a `ByteArrayInputStream` + `InputStreamReader` themselves.
    public static Map<String, Object> parseJSON(byte[] bytes) throws IOException {
        if (bytes == null || bytes.length == 0) {
            return null;
        }
        InputStreamReader r = new InputStreamReader(
                new ByteArrayInputStream(bytes), "UTF-8");
        try {
            return new JSONParser().parseJSON(r);
        } finally {
            try {
                r.close();
            } catch (IOException ignored) {
                Log.e(ignored);
            }
        }
    }

    /// Convenience: parse a JSON object from an in-memory String.
    public static Map<String, Object> parseJSON(String json) throws IOException {
        if (json == null || json.length() == 0) {
            return null;
        }
        return parseJSON(json.getBytes("UTF-8"));
    }

    /// Wrapper that lets a caller embed a pre-built JSON fragment into
    /// a Map/List tree being serialized by [#toJson(Object)]. The
    /// fragment is inlined verbatim rather than escaped as a string
    /// literal. Useful when a value (such as a JSON-Schema for a tool
    /// parameter) is already in canonical JSON form.
    ///
    /// ```
    /// Map<String, Object> root = new HashMap<String, Object>();
    /// root.put("parameters", JSONParser.rawJson(schema));
    /// String body = JSONParser.toJson(root);
    /// ```
    public static final class RawJson {
        private final String json;

        private RawJson(String json) {
            this.json = json;
        }

        public String getJson() {
            return json;
        }
    }

    /// Creates a [RawJson] marker. See the class javadoc for usage.
    public static RawJson rawJson(String json) {
        return new RawJson(json);
    }

    /// Serializes a `Map`/`List`/`String`/`Number`/`Boolean`/`null` /
    /// [RawJson] tree to JSON. Differs from [#mapToJson(Map)] in three
    /// ways: it takes any root type (not just `Map`); it omits
    /// null-valued `Map` entries (rather than emitting `"key":null`,
    /// which many REST APIs reject); and it understands the [RawJson]
    /// sentinel so callers can splice pre-built fragments into the
    /// tree without re-escaping them.
    ///
    /// `Map` keys must be `String`. Floats and doubles serialize
    /// using `Double.toString` (no scientific notation for typical
    /// values); integral types (`Integer`, `Long`, etc.) serialize as
    /// integers.
    public static String toJson(Object value) {
        StringBuilder sb = new StringBuilder();
        writeJsonValue(sb, value);
        return sb.toString();
    }

    private static void writeJsonValue(StringBuilder sb, Object o) {
        if (o == null) {
            sb.append("null");
            return;
        }
        if (o instanceof RawJson) {
            String s = ((RawJson) o).getJson();
            sb.append(s == null || s.length() == 0 ? "null" : s);
            return;
        }
        if (o instanceof String) {
            writeJsonString(sb, (String) o);
            return;
        }
        if (o instanceof Boolean) {
            sb.append(((Boolean) o).booleanValue() ? "true" : "false");
            return;
        }
        if (o instanceof Number) {
            Number n = (Number) o;
            if (n instanceof Float || n instanceof Double) {
                double d = n.doubleValue();
                if (Double.isInfinite(d) || Double.isNaN(d)) {
                    sb.append("null");
                } else {
                    sb.append(d);
                }
            } else {
                sb.append(n.longValue());
            }
            return;
        }
        if (o instanceof Map) {
            sb.append('{');
            boolean first = true;
            Map m = (Map) o;
            for (Object kObj : m.keySet()) {
                Object v = m.get(kObj);
                if (v == null) {
                    // Null-valued entries are dropped on purpose; if
                    // a caller really needs `"k":null` on the wire,
                    // they can serialize with mapToJson(...) instead.
                    continue;
                }
                if (!first) {
                    sb.append(',');
                }
                first = false;
                writeJsonString(sb, kObj.toString());
                sb.append(':');
                writeJsonValue(sb, v);
            }
            sb.append('}');
            return;
        }
        if (o instanceof java.util.List) {
            sb.append('[');
            java.util.List l = (java.util.List) o;
            for (int i = 0; i < l.size(); i++) {
                if (i > 0) {
                    sb.append(',');
                }
                writeJsonValue(sb, l.get(i));
            }
            sb.append(']');
            return;
        }
        writeJsonString(sb, o.toString());
    }

    private static void writeJsonString(StringBuilder sb, String s) {
        sb.append('"');
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '"':
                    sb.append("\\\"");
                    break;
                case '\\':
                    sb.append("\\\\");
                    break;
                case '\b':
                    sb.append("\\b");
                    break;
                case '\f':
                    sb.append("\\f");
                    break;
                case '\n':
                    sb.append("\\n");
                    break;
                case '\r':
                    sb.append("\\r");
                    break;
                case '\t':
                    sb.append("\\t");
                    break;
                default:
                    if (c < 0x20) {
                        sb.append("\\u");
                        String h = Integer.toHexString(c);
                        for (int p = h.length(); p < 4; p++) {
                            sb.append('0');
                        }
                        sb.append(h);
                    } else {
                        sb.append(c);
                    }
            }
        }
        sb.append('"');
    }

    /// Cast helper for the `Hashtable`/`Vector`-style return values
    /// from [#parseJSON(java.io.Reader)]. Returns `null` when the
    /// input is `null`; callers wishing to walk a JSON object tree
    /// without sprinkling `(Map)` casts everywhere can pass each
    /// nested value through this.
    @SuppressWarnings("unchecked")
    public static Map<String, Object> asMap(Object o) {
        if (o == null) {
            return null;
        }
        return (Map<String, Object>) o;
    }

    /// Cast helper for list-typed values pulled out of a parsed JSON
    /// tree. Same null behavior as [#asMap].
    @SuppressWarnings("unchecked")
    public static java.util.List<Object> asList(Object o) {
        if (o == null) {
            return null;
        }
        return (java.util.List<Object>) o;
    }

    /// Retrieves a String field from a parsed JSON object. Returns
    /// `null` if the key is missing or the map is `null`; calls
    /// `toString()` on non-String values for resilience.
    public static String getString(Map m, String key) {
        if (m == null) {
            return null;
        }
        Object v = m.get(key);
        return v == null ? null : v.toString();
    }

    /// Retrieves an int field from a parsed JSON object, with a
    /// fallback when the key is missing, the map is `null`, or the
    /// value cannot be parsed as an integer.
    public static int getInt(Map m, String key, int defaultValue) {
        if (m == null) {
            return defaultValue;
        }
        Object v = m.get(key);
        if (v == null) {
            return defaultValue;
        }
        if (v instanceof Number) {
            return ((Number) v).intValue();
        }
        try {
            return Integer.parseInt(v.toString());
        } catch (NumberFormatException nfe) {
            return defaultValue;
        }
    }

    /// Retrieves a double field from a parsed JSON object, with a
    /// fallback when the key is missing, the map is `null`, or the
    /// value cannot be parsed as a number.
    public static double getDouble(Map m, String key, double defaultValue) {
        if (m == null) {
            return defaultValue;
        }
        Object v = m.get(key);
        if (v == null) {
            return defaultValue;
        }
        if (v instanceof Number) {
            return ((Number) v).doubleValue();
        }
        try {
            return Double.parseDouble(v.toString());
        } catch (NumberFormatException nfe) {
            return defaultValue;
        }
    }

    /// Checks to see if this parser generates long objects and not just doubles for numeric values.
    public boolean isUseLongsInstance() {
        return useLongs;
    }

    /// Sets the current JSONParser instance to use longs instead of doubles for numeric values.  Prefer this to the static `#setUseLongs(boolean)`
    /// so that it doesn't disrupt libraries that may depend on JSONParser.
    ///
    /// #### Parameters
    ///
    /// - `longs`: True to use
    ///
    /// #### Since
    ///
    /// 7.0
    public void setUseLongsInstance(boolean longs) {
        useLongs = longs;
    }

    /// Checks whether this parser will include null values in parsed content.
    ///
    /// #### Returns
    ///
    /// True if null values are included in parsed content.
    ///
    /// #### Since
    ///
    /// 7.0
    public boolean isIncludeNullsInstance() {
        return includeNulls;
    }

    /// Sets whether to include null values in parsed content.
    ///
    /// #### Parameters
    ///
    /// - `include`: True to include null values in parsed content.
    ///
    /// #### Since
    ///
    /// 7.0
    public void setIncludeNullsInstance(boolean include) {
        includeNulls = include;
    }

    /// Indicates that the parser will generate Boolean objects and not just Strings for boolean values
    ///
    /// #### Returns
    ///
    /// True if the parser will generate Boolean objects and not just Strings for boolean values.
    ///
    /// #### Since
    ///
    /// 7.0
    public boolean isUseBooleanInstance() {
        return useBoolean;
    }

    /// Indicates that the parser will generate Boolean objects and not just Strings for boolean values
    ///
    /// #### Parameters
    ///
    /// - `useBoolean`: True to generate Boolean objects and not just Strings for boolean values.
    ///
    /// #### Since
    ///
    /// 7.0
    public void setUseBooleanInstance(boolean useBoolean) {
        this.useBoolean = useBoolean;
    }

    /// Parses the given input stream into this object and returns the parse tree.
    ///
    /// The `JSONParser` returns a `Map` which is great if the root object is a `Map` but in
    /// some cases its a list of elements (as is the case above). In this case a special case `"root"` element is
    /// created to contain the actual list of elements. See the sample below for exact usage of this.
    ///
    /// The sample below includes JSON from [https://anapioficeandfire.com/](https://anapioficeandfire.com/)
    /// generated by the query [http://www.anapioficeandfire.com/api/characters?page=5&pageSize=3](http://www.anapioficeandfire.com/api/characters?page=5&pageSize=3):
    ///
    /// ```java
    /// // File: JSONParsingSample.java
    /// Form hi = new Form("JSON Parsing", new BoxLayout(BoxLayout.Y_AXIS));
    /// JSONParser json = new JSONParser();
    /// try(Reader r = new InputStreamReader(Display.getInstance().getResourceAsStream(getClass(), "/anapioficeandfire.json"), "UTF-8")) {
    ///     Map data = json.parseJSON(r);
    ///     java.util.List<Map<String, Object>> content = (java.util.List<Map<String, Object>>)data.get("root");
    ///     for(Map obj : content) {
    ///         String url = (String)obj.get("url");
    ///         String name = (String)obj.get("name");
    ///         java.util.List titles = (java.util.List)obj.get("titles");
    ///         if(name == null || name.length() == 0) {
    ///             java.util.List aliases = (java.util.List)obj.get("aliases");
    ///             if(aliases != null && aliases.size() > 0) {
    ///                 name = aliases.get(0);
    ///             }
    ///         }
    ///         MultiButton mb = new MultiButton(name);
    ///         if(titles != null && titles.size() > 0) {
    ///             mb.setTextLine2(titles.get(0));
    ///         }
    ///         mb.addActionListener((e) -> Display.getInstance().execute(url));
    ///         hi.add(mb);
    ///     }
    /// } catch(IOException err) {
    ///     Log.e(err);
    /// }
    /// hi.show();
    /// ```
    ///
    /// ```json
    /// // File: anapioficeandfire.json
    /// [
    ///   {
    ///     "url": "http://www.anapioficeandfire.com/api/characters/13",
    ///     "name": "Chayle",
    ///     "culture": "",
    ///     "born": "",
    ///     "died": "In 299 AC, at Winterfell",
    ///     "titles": [
    ///       "Septon"
    ///     ],
    ///     "aliases": [],
    ///     "father": "",
    ///     "mother": "",
    ///     "spouse": "",
    ///     "allegiances": [],
    ///     "books": [
    ///       "http://www.anapioficeandfire.com/api/books/1",
    ///       "http://www.anapioficeandfire.com/api/books/2",
    ///       "http://www.anapioficeandfire.com/api/books/3"
    ///     ],
    ///     "povBooks": [],
    ///     "tvSeries": [],
    ///     "playedBy": []
    ///   },
    ///   {
    ///     "url": "http://www.anapioficeandfire.com/api/characters/14",
    ///     "name": "Gillam",
    ///     "culture": "",
    ///     "born": "",
    ///     "died": "",
    ///     "titles": [
    ///       "Brother"
    ///     ],
    ///     "aliases": [],
    ///     "father": "",
    ///     "mother": "",
    ///     "spouse": "",
    ///     "allegiances": [],
    ///     "books": [
    ///       "http://www.anapioficeandfire.com/api/books/5"
    ///     ],
    ///     "povBooks": [],
    ///     "tvSeries": [],
    ///     "playedBy": []
    ///   },
    ///   {
    ///     "url": "http://www.anapioficeandfire.com/api/characters/15",
    ///     "name": "High Septon",
    ///     "culture": "",
    ///     "born": "",
    ///     "died": "",
    ///     "titles": [
    ///       "High Septon",
    ///       "His High Holiness",
    ///       "Father of the Faithful",
    ///       "Voice of the Seven on Earth"
    ///     ],
    ///     "aliases": [
    ///       "The High Sparrow"
    ///     ],
    ///     "father": "",
    ///     "mother": "",
    ///     "spouse": "",
    ///     "allegiances": [],
    ///     "books": [
    ///       "http://www.anapioficeandfire.com/api/books/5",
    ///       "http://www.anapioficeandfire.com/api/books/8"
    ///     ],
    ///     "povBooks": [],
    ///     "tvSeries": [
    ///       "Season 5"
    ///     ],
    ///     "playedBy": [
    ///       "Jonathan Pryce"
    ///     ]
    ///   }
    /// ]
    /// ```
    ///
    /// #### Parameters
    ///
    /// - `i`: the reader
    ///
    /// #### Returns
    ///
    /// the parse tree as a hashtable
    ///
    /// #### Throws
    ///
    /// - `IOException`: if thrown by the stream
    public Map<String, Object> parseJSON(Reader i) throws IOException {
        modern = true;
        state = new LinkedHashMap<String, Object>();
        parseStack = new ArrayList<Object>();
        currentKey = null;
        if (!strict) {
            i = new CharArrayReader(JSONSanitizer.sanitize(Util.readToString(i)).toCharArray());
        }
        parse(i, this);
        return state;
    }

    /// Parses the given input stream into this object and returns the parse tree
    ///
    /// #### Parameters
    ///
    /// - `i`: the reader
    ///
    /// #### Returns
    ///
    /// the parse tree as a hashtable
    ///
    /// #### Throws
    ///
    /// - `IOException`: if thrown by the stream
    ///
    /// #### Deprecated
    ///
    /// use the new parseJSON instead
    public Hashtable<String, Object> parse(Reader i) throws IOException {
        modern = false;
        Hashtable<String, Object> legacyState = new Hashtable<String, Object>();
        state = legacyState;
        parseStack = new Vector<Object>();
        currentKey = null;
        if (!strict) {
            String cleaned = JSONSanitizer.sanitize(Util.readToString(i));
            i = new CharArrayReader(cleaned.toCharArray());
        }
        parse(i, this);
        return legacyState;
    }

    private boolean isStackHash() {
        return !parseStack.isEmpty() &&
                parseStack.get(parseStack.size() - 1) instanceof Map;
    }

    private Map getStackHash() {
        return (Map) parseStack.get(parseStack.size() - 1);
    }

    private java.util.List<Object> getStackVec() {
        return (java.util.List<Object>) parseStack.get(parseStack.size() - 1);
    }

    /// {@inheritDoc}
    @Override
    public void startBlock(String blockName) {
        if (parseStack.isEmpty()) {
            parseStack.add(state);
        } else {
            Map newOne;
            if (modern) {
                newOne = new LinkedHashMap();
            } else {
                newOne = new Hashtable();
            }
            if (isStackHash()) {
                getStackHash().put(currentKey, newOne);
                currentKey = null;
            } else {
                getStackVec().add(newOne);
            }
            parseStack.add(newOne);
        }
    }

    /// {@inheritDoc}
    @Override
    public void endBlock(String blockName) {
        parseStack.remove(parseStack.size() - 1);
    }

    /// Checks if this JSON parser is in strict mode.  When in strict mode, which is the default,
    /// only valid JSON will be parsed.  If strict mode is disabled, then it will attempt to
    /// sanitize the JSON input before parsing.  This can be handy if you want to parse structures
    /// that are *almost* JSON.  E.g. non-quoted keys, single-quotes on strings, unquoted strings. Etc.
    ///
    /// #### Returns
    ///
    /// True if strict mode is enabled.
    ///
    /// #### Since
    ///
    /// 7.0
    ///
    /// #### See also
    ///
    /// - #setStrict(boolean)
    public boolean isStrict() {
        return strict;
    }

    /// Enables or disables strict mode.  Default is true.
    ///
    /// When strict mode is disabled, the parser will sanitize the JSON input before parsing.  The effect
    /// is that it will be able to parse input that is json-ish.
    ///
    /// Non-Strict Input
    /// The sanitizer takes JSON like content, and interprets it as JS eval
    /// would. Specifically, it deals with these non-standard constructs.
    ///
    /// - `'...'` Single quoted strings are converted to JSON strings.
    ///
    /// - `\xAB` Hex escapes are converted to JSON unicode escapes.
    ///
    /// - `\012` Octal escapes are converted to JSON unicode escapes.
    ///
    /// - `0xAB` Hex integer literals are converted to JSON decimal
    /// numbers.
    ///
    /// - `012` Octal integer literals are converted to JSON decimal
    /// numbers.
    ///
    /// - `+.5` Decimal numbers are coerced to JSON's stricter format.
    ///
    /// - `[0,,2]` Elisions in arrays are filled with `null`.
    ///
    /// - `[1,2,3,]` Trailing commas are removed.
    ///
    /// - `{foo:"bar"}` Unquoted property names are quoted.
    ///
    /// - `//comments` JS style line and block comments are removed.
    ///
    /// - `(...)` Grouping parentheses are removed.
    ///
    /// #### Parameters
    ///
    /// - `strict`: True to enable strict mode, false to disable it.
    ///
    /// #### See also
    ///
    /// - #isStrict()
    public void setStrict(boolean strict) {
        this.strict = strict;
    }

    /// {@inheritDoc}
    @Override
    public void startArray(String arrayName) {
        java.util.List<Object> currentVector;
        if (modern) {
            currentVector = new ArrayList<Object>();
        } else {
            currentVector = new Vector<Object>();
        }

        // the root of the JSON is an array, we need to wrap it in an assignment
        if (parseStack.isEmpty()) {
            parseStack.add(state);
            currentKey = "root";
        }
        if (isStackHash()) {
            getStackHash().put(currentKey, currentVector);
            currentKey = null;
        } else {
            getStackVec().add(currentVector);
        }
        parseStack.add(currentVector);
    }

    /// {@inheritDoc}
    @Override
    public void endArray(String arrayName) {
        parseStack.remove(parseStack.size() - 1);
    }

    /// {@inheritDoc}
    @Override
    public void stringToken(String tok) {
        if (isStackHash()) {
            if (currentKey == null) {
                currentKey = tok;
            } else {
                if (tok != null || isIncludeNullsInstance()) {
                    getStackHash().put(currentKey, tok);
                }
                currentKey = null;
            }
        } else {
            getStackVec().add(tok);
        }
    }

    /// {@inheritDoc}
    @Override
    public void numericToken(double tok) {
        if (isStackHash()) {
            getStackHash().put(currentKey, Double.valueOf(tok));
            currentKey = null;
        } else {
            getStackVec().add(Double.valueOf(tok));
        }
    }

    /// {@inheritDoc}
    @Override
    public void longToken(long tok) {
        if (isStackHash()) {
            getStackHash().put(currentKey, Long.valueOf(tok));
            currentKey = null;
        } else {
            getStackVec().add(Long.valueOf(tok));
        }
    }

    /// {@inheritDoc}
    @Override
    public void booleanToken(boolean tok) {
        if (isStackHash()) {
            getStackHash().put(currentKey, tok);
            currentKey = null;
        } else {
            getStackVec().add(tok);
        }
    }

    /// {@inheritDoc}
    @Override
    public void keyValue(String key, String value) {
    }

    /// {@inheritDoc}
    @Override
    public boolean isAlive() {
        return true;
    }

    static class ReaderClass {
        char[] buffer;
        int buffOffset;
        int buffSize = -1;

        int read(Reader is) throws IOException {
            int c = -1;
            if (buffer == null) {
                buffer = new char[8192];
            }

            if (buffSize < 0 || buffOffset >= buffSize) {
                buffSize = is.read(buffer, 0, buffer.length);
                if (buffSize < 0) {
                    return -1;
                }
                buffOffset = 0;
            }
            c = buffer[buffOffset];
            buffOffset++;

            return c;
        }

    }

    static class KeyStack extends Vector {
        protected String peek() {
            return (String) elementAt(0);
        }

        protected void push(String key) {
            insertElementAt(key, 0);
        }

        protected String pop() {
            if (isEmpty()) {
                return null;
            }
            String key = peek();
            removeElementAt(0);
            return key;
        }
    }


}
