codename1.packageName=com.codename1.guibuilder
codename1.mainName=CodenameOneGUIBuilder
codename1.displayName=Codename One GUI Builder
codename1.version=1.0
codename1.vendor=Codename One
codename1.cssTheme=true
codename1.arg.java.version=17
