/*
 * Copyright (c) 2012-2026, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation. Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Codename One through http://www.codenameone.com/ if you
 * need additional information or have any questions.
 */
package com.codename1.social;

import com.codename1.io.AccessToken;
import com.codename1.io.Preferences;
import com.codename1.io.oidc.OidcClient;
import com.codename1.io.oidc.OidcException;
import com.codename1.io.oidc.OidcTokens;
import com.codename1.security.Hash;
import com.codename1.security.SecureRandom;
import com.codename1.util.Base64;
import com.codename1.util.SuccessCallback;

import java.util.Map;

/// `Sign in with Apple` for Codename One. Replaces the external
/// `cn1-applesignin` library for new code; the cn1lib continues to work
/// on its own (this class doesn't depend on it and doesn't forward to it
/// -- they're independent implementations).
///
/// Behavior by platform:
///
/// - **iOS 13+** -- native `ASAuthorizationAppleIDProvider` flow via
///   [AppleSignInNative]. Returns the identity token plus the user's name
///   and email on the first authorization (Apple does not echo them on
///   subsequent ones; this class persists them in [Preferences]).
/// - **Android / JavaSE / Web** -- web fallback via
///   [com.codename1.io.oidc.OidcClient] against the public Apple OIDC issuer
///   (`https://appleid.apple.com`). Requires a *Services ID* (web client
///   ID), a redirect URI registered with Apple, and a `client_secret` JWT
///   generated server-side (use [#setClientSecret(String)]).
///
/// #### Quick example
///
/// ```java
/// AppleSignIn apple = AppleSignIn.getInstance()
///     .withServiceId("com.example.appleweb")     // web only
///     .withRedirectUri("https://example.com/cb"); // web only
///
/// apple.signIn("name email", new AppleSignInCallback() {
///     public void onSuccess(AppleSignInResult result) {
///         String id    = result.getUserId();
///         String email = result.getEmail();
///         String idTok = result.getIdentityToken();
///         // send idTok to your backend for verification
///     }
///     public void onError(String error) { ... }
///     public void onCancel() { ... }
/// });
/// ```
///
/// @since 7.0.245
public final class AppleSignIn extends Login {

    /// Apple's public OIDC issuer.
    public static final String APPLE_ISSUER = "https://appleid.apple.com";

    private static final String PREF_NAME = "cn1.applesignin.name";
    private static final String PREF_EMAIL = "cn1.applesignin.email";
    private static final String PREF_USER = "cn1.applesignin.userid";
    private static final String PREF_LOGGED_IN = "cn1.applesignin.loggedIn";

    private static AppleSignIn INSTANCE;

    private String serviceId;          // web Services ID
    private String webRedirectUri;     // for web fallback only
    private String webClientSecret;    // JWT generated by your backend
    private String defaultScopes = "name email";

    private AppleSignIn() {}

    public static synchronized AppleSignIn getInstance() {
        if (INSTANCE == null) {
            INSTANCE = new AppleSignIn();
        }
        return INSTANCE;
    }

    /// Apple *Services ID* used for the web fallback. Required only when
    /// running on platforms without the native sheet (Android, JavaSE, Web).
    public AppleSignIn withServiceId(String serviceId) {
        this.serviceId = serviceId;
        super.setClientId(serviceId);
        return this;
    }

    /// Redirect URI registered with Apple for the Services ID. Used by the
    /// web fallback.
    public AppleSignIn withRedirectUri(String redirectUri) {
        this.webRedirectUri = redirectUri;
        super.setRedirectURI(redirectUri);
        return this;
    }

    /// Client-secret JWT generated by your backend (Apple does not let mobile
    /// apps mint this themselves -- see the developer guide for the recipe).
    public AppleSignIn withClientSecret(String secret) {
        this.webClientSecret = secret;
        super.setClientSecret(secret);
        return this;
    }

    public AppleSignIn withDefaultScopes(String scopes) {
        this.defaultScopes = scopes;
        return this;
    }

    @Override
    public boolean isNativeLoginSupported() {
        AppleSignInNative n = lookupNative();
        return n != null && n.isSupported();
    }

    @Override
    public boolean nativeIsLoggedIn() {
        AppleSignInNative n = lookupNative();
        if (n != null && n.isSupported()) {
            return n.isLoggedIn();
        }
        return Preferences.get(PREF_LOGGED_IN, false);
    }

    @Override
    public void nativeLogout() {
        AppleSignInNative n = lookupNative();
        if (n != null && n.isSupported()) {
            n.signOut();
        }
        Preferences.delete(PREF_LOGGED_IN);
        Preferences.delete(PREF_NAME);
        Preferences.delete(PREF_EMAIL);
        Preferences.delete(PREF_USER);
    }

    @Override
    public void nativelogin() {
        signIn(defaultScopes, new LoginCallbackAdapter());
    }

    @Override
    protected boolean validateToken(String token) {
        // Apple identity tokens carry an `exp` claim; we trust it.
        return true;
    }

    /// Primary entry point. Triggers either the native sheet (iOS) or the
    /// web OIDC fallback (everything else) and delivers the result to
    /// `callback`.
    public void signIn(String scopes, final AppleSignInCallback callback) {
        if (callback == null) {
            throw new IllegalArgumentException("callback must not be null");
        }
        final String resolvedScopes = scopes != null ? scopes : defaultScopes;
        AppleSignInNative n = lookupNative();
        if (n != null && n.isSupported()) {
            signInNative(n, resolvedScopes, callback);
        } else {
            signInWeb(resolvedScopes, callback);
        }
    }

    private void signInNative(final AppleSignInNative n,
                              final String scopes,
                              final AppleSignInCallback callback) {
        final byte[] rawNonce = SecureRandom.bytes(32);
        final String plainNonce = strip(Base64.encodeUrlSafe(rawNonce));
        // Apple expects the SHA-256 hash of the nonce as the `nonce` value
        // sent on the request; the returned ID token then carries the *hashed*
        // value in its `nonce` claim. We hash it here.
        byte[] hashed;
        try {
            hashed = Hash.sha256(plainNonce.getBytes("UTF-8"));
        } catch (java.io.UnsupportedEncodingException e) {
            // UTF-8 is guaranteed by the Java spec on every JVM; reach this
            // branch only on a malformed runtime. Rethrow rather than fall
            // back to the platform default encoding (SpotBugs DM_DEFAULT_ENCODING).
            throw new IllegalStateException("UTF-8 is not available on this JVM", e);
        }
        final String hashedNonce = strip(Base64.encodeUrlSafe(hashed));
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    String packed = n.signIn(scopes, hashedNonce);
                    if (packed == null || packed.length() == 0) {
                        callback.onCancel();
                        return;
                    }
                    AppleSignInResult result = parsePackedResult(packed);
                    if (result.getIdentityToken() == null) {
                        callback.onError("Apple Sign-In returned no identity token");
                        return;
                    }
                    persistProfile(result);
                    setAccessToken(buildAccessToken(result));
                    callback.onSuccess(result);
                } catch (Throwable t) {
                    callback.onError(t.getMessage());
                }
            }
        }, "AppleSignIn-native").start();
    }

    private void signInWeb(final String scopes, final AppleSignInCallback callback) {
        if (serviceId == null || webRedirectUri == null) {
            callback.onError("AppleSignIn web fallback requires setServiceId() and setRedirectUri()");
            return;
        }
        // Apple advertises `.well-known/openid-configuration` -- discover then auth.
        OidcClient.discover(APPLE_ISSUER)
                .ready(new SuccessCallback<OidcClient>() {
                    @Override
                    public void onSucess(OidcClient client) {
                        // Apple does NOT issue refresh tokens to public clients; require
                        // form_post + `response_mode` for compatibility.
                        client.setClientId(serviceId)
                                .setRedirectUri(webRedirectUri)
                                .setScopes(splitScopes(scopes))
                                .setResponseMode("form_post");
                        if (webClientSecret != null) {
                            client.setClientSecret(webClientSecret);
                        }
                        client.authorize()
                                .ready(new SuccessCallback<OidcTokens>() {
                                    @Override
                                    public void onSucess(OidcTokens t) {
                                        AppleSignInResult r = fromOidcTokens(t);
                                        persistProfile(r);
                                        setAccessToken(t.toAccessToken());
                                        callback.onSuccess(r);
                                    }
                                })
                                .except(new SuccessCallback<Throwable>() {
                                    @Override
                                    public void onSucess(Throwable err) {
                                        if (err instanceof OidcException &&
                                                OidcException.USER_CANCELLED.equals(
                                                        ((OidcException) err).getError())) {
                                            callback.onCancel();
                                        } else {
                                            callback.onError(err.getMessage());
                                        }
                                    }
                                });
                    }
                })
                .except(new SuccessCallback<Throwable>() {
                    @Override
                    public void onSucess(Throwable err) {
                        callback.onError("Apple OIDC discovery failed: " + err.getMessage());
                    }
                });
    }

    private void persistProfile(AppleSignInResult result) {
        if (result.getUserId() != null) {
            Preferences.set(PREF_USER, result.getUserId());
        }
        if (result.getEmail() != null) {
            Preferences.set(PREF_EMAIL, result.getEmail());
        }
        if (result.getFullName() != null) {
            Preferences.set(PREF_NAME, result.getFullName());
        }
        Preferences.set(PREF_LOGGED_IN, true);
    }

    private AccessToken buildAccessToken(AppleSignInResult result) {
        return new AccessToken(
                result.getAuthorizationCode(),
                null,
                null,
                result.getIdentityToken());
    }

    private static String[] splitScopes(String scopes) {
        if (scopes == null) {
            return new String[0];
        }
        String trimmed = scopes.trim();
        if (trimmed.length() == 0) {
            return new String[0];
        }
        return com.codename1.util.StringUtil.tokenize(trimmed, ' ').toArray(new String[0]);
    }

    private static AppleSignInResult parsePackedResult(String packed) {
        String[] parts = explode(packed, '|', 6);
        AppleSignInResult r = new AppleSignInResult();
        r.identityToken = empty(parts[0]) ? null : parts[0];
        r.authorizationCode = empty(parts[1]) ? null : parts[1];
        r.userId = empty(parts[2]) ? null : parts[2];
        String given = empty(parts[3]) ? null : parts[3];
        String family = empty(parts[4]) ? null : parts[4];
        r.email = empty(parts[5]) ? null : parts[5];
        if (given != null || family != null) {
            r.fullName = (given == null ? "" : given) +
                    (given != null && family != null ? " " : "") +
                    (family == null ? "" : family);
        }
        // Backfill from preferences when Apple omits the profile on
        // subsequent logins.
        if (r.email == null) {
            r.email = Preferences.get(PREF_EMAIL, (String) null);
        }
        if (r.fullName == null) {
            r.fullName = Preferences.get(PREF_NAME, (String) null);
        }
        return r;
    }

    private static AppleSignInResult fromOidcTokens(OidcTokens t) {
        AppleSignInResult r = new AppleSignInResult();
        r.identityToken = t.getIdToken();
        r.authorizationCode = (String) t.getRawResponse().get("code");
        r.userId = t.getSubject();
        r.email = t.getEmail();
        Map<String, Object> claims = t.getIdTokenClaims();
        Object name = claims != null ? claims.get("name") : null;
        if (name != null) {
            r.fullName = name.toString();
        }
        return r;
    }

    private static String[] explode(String s, char sep, int expected) {
        String[] out = new String[expected];
        for (int i = 0; i < expected; i++) {
            out[i] = "";
        }
        int idx = 0;
        int start = 0;
        int len = s.length();
        for (int i = 0; i < len; i++) {
            if (s.charAt(i) == sep) {
                if (idx < expected) {
                    out[idx++] = s.substring(start, i);
                }
                start = i + 1;
            }
        }
        if (idx < expected) {
            out[idx] = s.substring(start);
        }
        return out;
    }

    private static boolean empty(String s) {
        return s == null || s.length() == 0;
    }

    private static String strip(String s) {
        StringBuilder b = new StringBuilder(s.length());
        int len = s.length();
        for (int i = 0; i < len; i++) {
            char c = s.charAt(i);
            if (c == '=' || c == '\n' || c == '\r') {
                continue;
            }
            b.append(c);
        }
        return b.toString();
    }

    private static AppleSignInNative provider;

    /// Registers the native [AppleSignInNative] implementation. Called at
    /// app startup by the port (`AppleSignInNativeImpl.init()`); cn1lib
    /// authors can also call this to plug in their own implementation, e.g.
    /// wrapping the `AuthenticationServices` framework differently. Pass
    /// `null` to fall back to the [com.codename1.io.oidc.OidcClient] web
    /// flow.
    ///
    /// We use an explicit setter rather than `Class.forName` because
    /// Codename One obfuscates class names; the port instantiates the impl
    /// itself and passes the instance here.
    public static void setProvider(AppleSignInNative p) {
        synchronized (AppleSignIn.class) {
            provider = p;
        }
    }

    private static AppleSignInNative lookupNative() {
        synchronized (AppleSignIn.class) {
            return provider;
        }
    }

    /// Bridges [AppleSignInCallback] into the legacy [LoginCallback] used by
    /// [Login#doLogin()].
    private final class LoginCallbackAdapter implements AppleSignInCallback {
        @Override
        public void onSuccess(AppleSignInResult result) {
            // `callback` from Login is package-private; trigger success via setAccessToken side-effect.
            if (callback != null) {
                callback.loginSuccessful();
            }
        }

        @Override
        public void onError(String error) {
            if (callback != null) {
                callback.loginFailed(error);
            }
        }

        @Override
        public void onCancel() {
            if (callback != null) {
                callback.loginFailed("cancelled");
            }
        }
    }
}
