/*
 * Copyright (c) 2012, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Codename One through http://www.codenameone.com/ if you
 * need additional information or have any questions.
 */
package com.codename1.gamebuilder.editor;

/// Generates the two files the builder writes into a project for a scene, mirroring how
/// the GUI builder pairs a {@code .gui} data file with a {@code .java} companion:
///
/// - the {@code <Name>.game} JSON (the level data, from `GameLevel#toJson()`), and
/// - a thin {@code <Name>.java} that extends
///   `com.codename1.gaming.level.GameSceneView`, loads that resource at runtime and
///   exposes a behavior hook. The generated load wiring lives between DON'T EDIT
///   markers (the region the Maven goal's monitor refreshes); the {@code onUpdate}
///   body is yours to edit and is preserved across regeneration.
public final class CompanionCodeGen {
    /// Marker the Maven goal uses to find the regenerated region.
    public static final String GEN_BEGIN = "//-- GAMEBUILDER GENERATED - DO NOT EDIT BELOW";
    public static final String GEN_END = "//-- GAMEBUILDER GENERATED - DO NOT EDIT ABOVE";

    private CompanionCodeGen() {
    }

    /// The level JSON to write to {@code <Name>.game}.
    public static String gameData(EditorModel model) {
        return model.level().toJson();
    }

    /// The companion Java source for the scene. {@code gameResourcePath} is the runtime
    /// classpath path of the {@code .game} file (e.g. {@code /games/Level1.game}).
    public static String companionJava(String packageName, String className, String gameResourcePath) {
        boolean blank = packageName == null || packageName.trim().isEmpty();
        String pkg = blank ? "" : "package " + packageName + ";\n\n";
        String body = """
                import com.codename1.gaming.level.AssetCatalog;
                import com.codename1.gaming.level.GameLevel;
                import com.codename1.gaming.level.GameSceneView;
                import com.codename1.ui.Display;

                /// Generated by the Codename One game builder. The level data lives in
                /// {RES} and is loaded at runtime; edit the level visually with
                /// `mvn cn1:gamebuilder`. Put your game logic in onUpdate.
                public class {CLS} extends GameSceneView {
                    public {CLS}(AssetCatalog catalog) {
                        super(loadLevel(), catalog);
                        initScene();
                    }

                    {BEGIN}
                    private static GameLevel loadLevel() {
                        try {
                            return GameLevel.load(Display.getInstance().getResourceAsStream({CLS}.class, "{RES}"));
                        } catch (java.io.IOException err) {
                            throw new RuntimeException("failed to load level {RES}", err);
                        }
                    }

                    private void initScene() {
                        // generated behavior wiring is refreshed here by the editor
                    }
                    {END}

                    @Override
                    protected void onUpdate(double deltaSeconds) {
                        // TODO: your per-frame game logic
                    }
                }
                """;
        return pkg + body
                .replace("{RES}", gameResourcePath)
                .replace("{CLS}", className)
                .replace("{BEGIN}", GEN_BEGIN)
                .replace("{END}", GEN_END);
    }
}
