/*
 * Copyright (c) 2026, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Codename One through http://www.codenameone.com/ if you
 * need additional information or have any questions.
 */
package com.codename1.builders;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Generates the source of the health background-listener factory that the
 * runtime consults after the OS relaunches an app to deliver health data.
 *
 * <p><b>Why generated rather than reflective.</b> A subscription persists
 * the name of its listener class, and after a process relaunch that string
 * is all that survives. Resolving it with {@code Class.forName} is the
 * obvious approach and is wrong on these targets: a class referenced only
 * by a string is invisible to the iOS and JavaScript translators' dead-code
 * elimination, so it can be stripped from the very build that needs it, and
 * obfuscation renames it so a name persisted by an earlier version stops
 * resolving.</p>
 *
 * <p>So the binding is decided here, at build time. The class scanner
 * already records implemented interfaces, so implementations of
 * {@code com.codename1.health.HealthBackgroundListener} are detectable; for
 * each one this emits a direct {@code new} expression. That is a real
 * reference, which shrinking and obfuscation both follow correctly, and it
 * needs no reflection at runtime. The name keys stay stable because
 * {@link HealthManifestFragments#proguardKeepRules(List)} emits
 * {@code -keepnames} for the same classes.</p>
 *
 * <p><b>Keep this file in sync with the BuildDaemon copy.</b></p>
 */
final class HealthListenerBindings {

    /** Package and class of the generated factory. */
    static final String PACKAGE = "com.codename1.health.generated";
    static final String CLASS_NAME = "CN1HealthListenerBindings";
    static final String FQCN = PACKAGE + "." + CLASS_NAME;

    private HealthListenerBindings() {
    }

    /**
     * Returns the Java source of the factory, or {@code null} when the app
     * declares no background listeners -- in which case nothing is
     * generated and nothing is registered, and the runtime simply defers
     * any background delivery rather than losing it.
     *
     * @param listenerClassNames fully qualified names of classes
     *                           implementing
     *                           {@code HealthBackgroundListener}
     */
    static String generate(List<String> listenerClassNames) {
        if (listenerClassNames == null || listenerClassNames.isEmpty()) {
            return null;
        }
        List<String> sorted = new ArrayList<String>(listenerClassNames);
        Collections.sort(sorted);

        StringBuilder sb = new StringBuilder();
        sb.append("package ").append(PACKAGE).append(";\n\n");
        sb.append("import com.codename1.health.HealthBackgroundListener;\n");
        sb.append("import com.codename1.health")
                .append(".HealthBackgroundListenerFactory;\n");
        sb.append("import com.codename1.health.HealthStore;\n\n");
        sb.append("/**\n");
        sb.append(" * Generated by the Codename One build server. Binds the")
                .append(" health background\n");
        sb.append(" * listeners this app declares to direct constructor")
                .append(" calls, so that no\n");
        sb.append(" * reflection is needed after a background relaunch and")
                .append(" the classes\n");
        sb.append(" * survive shrinking and obfuscation. Do not edit.\n");
        sb.append(" */\n");
        sb.append("public final class ").append(CLASS_NAME)
                .append(" implements HealthBackgroundListenerFactory {\n\n");
        sb.append("    public static void install() {\n");
        sb.append("        HealthStore.setBackgroundListenerFactory(new ")
                .append(CLASS_NAME).append("());\n");
        sb.append("    }\n\n");
        sb.append("    public HealthBackgroundListener create(String")
                .append(" className) {\n");
        for (int i = 0; i < sorted.size(); i++) {
            String fqcn = sorted.get(i);
            sb.append("        if (\"").append(fqcn)
                    .append("\".equals(className)) {\n");
            sb.append("            return new ").append(fqcn).append("();\n");
            sb.append("        }\n");
        }
        sb.append("        return null;\n");
        sb.append("    }\n");
        sb.append("}\n");
        return sb.toString();
    }

    /**
     * The statement injected into app startup to install the factory, or
     * {@code null} when nothing was generated.
     */
    static String installStatement(List<String> listenerClassNames) {
        if (listenerClassNames == null || listenerClassNames.isEmpty()) {
            return null;
        }
        return FQCN + ".install();\n";
    }

    /** The path the generated source is written to, relative to a source root. */
    static String sourcePath() {
        return PACKAGE.replace('.', '/') + "/" + CLASS_NAME + ".java";
    }
}
