// Generated by cn1:generate-grpc.
package com.example.hello;

import com.codename1.annotations.grpc.GrpcClient;
import com.codename1.annotations.grpc.Rpc;
import com.codename1.annotations.rest.Header;
import com.codename1.io.grpc.GrpcClients;
import com.codename1.io.grpc.GrpcResponse;
import com.codename1.util.OnComplete;

// tag::appendix-goal-generate-grpc-java-001[]
@GrpcClient("helloworld.Greeter")
public interface GreeterGrpc {

    @Rpc("SayHello")
    void sayHello(com.example.hello.HelloRequest request, @Header("Authorization") String bearerToken, OnComplete<GrpcResponse<com.example.hello.HelloReply>> callback);

    static GreeterGrpc of(String baseUrl) {
        return GrpcClients.create(GreeterGrpc.class, baseUrl);
    }
}
// end::appendix-goal-generate-grpc-java-001[]
