// Generated by cn1:generate-grpc.
package com.example.hello;

import com.codename1.annotations.grpc.ProtoField;
import com.codename1.annotations.grpc.ProtoMessage;
import java.util.List;

@ProtoMessage
public record HelloRequest(
    @ProtoField(tag = 1) String name,
    @ProtoField(tag = 2) List<String> aliases,
    @ProtoField(tag = 3) com.example.hello.Mood mood
) {}
