package com.codename1.initializr.model;

import com.codename1.io.Util;
import com.codename1.testing.AbstractTest;
import com.codename1.util.StringUtil;
import net.sf.zipme.ZipEntry;
import net.sf.zipme.ZipInputStream;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Integration test that ensures a project generated by Initializr round-trips through
 * generate-app-project without silently diverging in output.
 */
public class GeneratorModelRoundTripTemplateIntegrationTest extends AbstractTest {
    @Override
    public boolean runTest() throws Exception {
        String appName = "RoundTripInitializrApp";
        String packageName = "com.acme.initializr.roundtrip";

        byte[] zip = createProjectZip(appName, packageName);
        Path sourceProjectDir = Files.createTempDirectory("initializr-roundtrip-source-");
        unzipProject(zip, sourceProjectDir);

        Files.write(sourceProjectDir.resolve("generate-app-project.rpf"), buildTemplateConfig(appName, packageName).getBytes("UTF-8"));

        String cn1Version = extractCn1Version(Files.readAllBytes(sourceProjectDir.resolve("pom.xml")));
        Path workingDir = Files.createTempDirectory("initializr-roundtrip-work-");
        String generatedArtifactId = "initializr-roundtrip-generated";
        Path generatedProjectDir = workingDir.resolve(generatedArtifactId);

        int exitCode = runGenerateAppProject(workingDir, sourceProjectDir, cn1Version, generatedArtifactId, appName, packageName);
        assertTrue(exitCode == 0, "generate-app-project should complete successfully");

        assertTrue(Files.isDirectory(generatedProjectDir), "Generated project directory should exist");
        assertProjectsMatch(sourceProjectDir, generatedProjectDir);
        return true;
    }

    private byte[] createProjectZip(String appName, String packageName) throws IOException {
        ByteArrayOutputStream output = new ByteArrayOutputStream();
        GeneratorModel.create(IDE.INTELLIJ, Template.BAREBONES, appName, packageName).writeProjectZip(output);
        return output.toByteArray();
    }

    private String buildTemplateConfig(String appName, String packageName) {
        return "template.type=maven\n" +
                "template.mainName=" + appName + "\n" +
                "template.packageName=" + packageName + "\n";
    }

    private int runGenerateAppProject(Path workingDir, Path sourceProjectDir, String cn1Version, String artifactId,
                                      String appName, String packageName) throws Exception {
        List<String> cmd = new ArrayList<String>();
        Collections.addAll(cmd,
                "mvn",
                "com.codenameone:codenameone-maven-plugin:" + cn1Version + ":generate-app-project",
                "-DarchetypeGroupId=com.codenameone",
                "-DarchetypeArtifactId=cn1app-archetype",
                "-DarchetypeVersion=" + cn1Version,
                "-DartifactId=" + artifactId,
                "-DgroupId=" + packageName,
                "-Dversion=1.0-SNAPSHOT",
                "-DmainName=" + appName,
                "-DpackageName=" + packageName,
                "-DinteractiveMode=false",
                "-DsourceProject=" + sourceProjectDir.toAbsolutePath()
        );

        ProcessBuilder pb = new ProcessBuilder(cmd);
        pb.directory(workingDir.toFile());
        pb.redirectErrorStream(true);

        List<String> output = new ArrayList<String>();
        Process process = pb.start();
        try (InputStream in = process.getInputStream()) {
            java.io.BufferedReader r = new java.io.BufferedReader(new java.io.InputStreamReader(in));
            String line;
            while ((line = r.readLine()) != null) {
                output.add(line);
            }
        }
        int exit = process.waitFor();
        if (exit != 0) {
            StringBuilder sb = new StringBuilder();
            for (String line : output) {
                if (sb.length() > 12000) {
                    sb.append("\n...[truncated]");
                    break;
                }
                sb.append(line).append('\n');
            }
            System.out.println(sb.toString());
        }
        return exit;
    }

    private String extractCn1Version(byte[] rootPomBytes) {
        String pom = StringUtil.newString(rootPomBytes);
        String startTag = "<cn1.version>";
        String endTag = "</cn1.version>";
        int start = pom.indexOf(startTag);
        int end = pom.indexOf(endTag);
        assertTrue(start >= 0 && end > start, "Generated pom.xml should include cn1.version");
        return pom.substring(start + startTag.length(), end).trim();
    }

    private void assertProjectsMatch(Path expected, Path actual) throws IOException {
        Set<String> ignoredFiles = new HashSet<String>();
        ignoredFiles.add("generate-app-project.rpf");

        List<String> expectedFiles = listFiles(expected, ignoredFiles);
        List<String> actualFiles = listFiles(actual, ignoredFiles);

        assertEquals(expectedFiles, actualFiles);

        for (String relativePath : expectedFiles) {
            byte[] expectedData = Files.readAllBytes(expected.resolve(relativePath));
            byte[] actualData = Files.readAllBytes(actual.resolve(relativePath));
            if (!java.util.Arrays.equals(expectedData, actualData)) {
                fail("File content differs after round-trip: " + relativePath);
            }
        }
    }

    private List<String> listFiles(Path root, Set<String> ignoredFiles) throws IOException {
        List<String> out = new ArrayList<String>();
        try (java.util.stream.Stream<Path> stream = Files.walk(root)) {
            stream.filter(Files::isRegularFile).forEach(p -> {
                String rel = root.relativize(p).toString().replace('\\', '/');
                if (rel.startsWith("target/")) {
                    return;
                }
                if (ignoredFiles.contains(rel)) {
                    return;
                }
                out.add(rel);
            });
        }
        Collections.sort(out);
        return out;
    }

    private void unzipProject(byte[] zipData, Path destination) throws IOException {
        ByteArrayInputStream input = new ByteArrayInputStream(zipData);
        ZipInputStream zis = new ZipInputStream(input);
        try {
            ZipEntry entry = zis.getNextEntry();
            while (entry != null) {
                if (!entry.isDirectory()) {
                    Path target = destination.resolve(entry.getName());
                    Path parent = target.getParent();
                    if (parent != null) {
                        Files.createDirectories(parent);
                    }
                    FileOutputStream fos = new FileOutputStream(target.toFile());
                    try {
                        Util.copyNoClose(zis, fos, 8192);
                    } finally {
                        fos.close();
                    }
                }
                zis.closeEntry();
                entry = zis.getNextEntry();
            }
        } finally {
            zis.close();
            input.close();
        }
    }
}
