/*
 * Copyright (c) 2012, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Codename One through http://www.codenameone.com/ if you
 * need additional information or have any questions.
 */
package com.codename1.impl.backend.test;

import com.codename1.impl.backend.BackendApplication;

/// One test class's configuration, generated by the build as
/// `<TestClass>Cn1TestContext`: what to start, and how to fill the test's fields
/// from it.
public interface TestContext {
    /// Equal for two classes whose applications would be the same, so one running
    /// application serves both.
    String key();

    /// The module's `application.properties`, compiled in, as key and value pairs.
    String[] compiledSettings();

    /// The profile's `application-<profile>.properties`, compiled in, as key and
    /// value pairs. Above [#compiledSettings] and below the environment, where a
    /// server reads that file.
    String[] profileSettings();

    /// The test's own properties, as key and value pairs. These win over every
    /// other layer, the environment included.
    String[] properties();

    String profile();

    /// The ordinal of `BackendTest.WebEnvironment`.
    int webEnvironment();

    /// Whether the beans need a database, as the generated main asks.
    boolean requiresDataSource();

    /// Runs before the application starts: registers the generated daos.
    void prepare();

    /// A new wiring of this test's beans.
    BackendApplication createApplication();

    /// The names of the mock beans, reset after each test.
    String[] mockBeans();

    /// Fills the test instance's `@Autowired`, `@LocalServerPort` and
    /// `@MockitoBean` fields.
    void inject(Object test, TestEnvironment environment) throws Exception;
}
