package com.codename1.tools.skindesigner;

import com.codename1.io.JSONParser;
import com.codename1.io.Log;
import com.codename1.ui.Display;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

/**
 * Bundled device database loaded from {@code /devices.json} at startup.
 *
 * The JSON catalog is generated by
 * {@code tools/devicedb/build_devices_json.py} from a public GSMArena dump
 * and refreshed by CI on a schedule. Bundling it avoids any runtime fetch,
 * which would hit CORS in the JavaScript port.
 */
public final class DeviceDatabase {
    public static final String FORM_PHONE = "Phone";
    public static final String FORM_TABLET = "Tablet";
    public static final String FORM_FOLDABLE = "Foldable";

    public static final class Device {
        public final String id;
        public final String brand;
        public final String os;
        public final int year;
        public final String form;
        public final String name;
        public final int resolutionW;
        public final int resolutionH;
        public final double screenSize;
        public final int ppi;
        public final String platformName;
        public final boolean hasNotch;
        public final boolean hasIsland;
        public final boolean hasHole;
        public final boolean hasHomeIndicator;
        public final int safeTop;
        public final int safeBottom;
        public final int safeLeft;
        public final int safeRight;
        public final String systemFont;
        public final String proportionalFont;
        public final String monoFont;
        public final int fontSmall;
        public final int fontMedium;
        public final int fontLarge;
        public final boolean tablet;

        Device(String id, String brand, String os, int year, String form, String name,
               int rw, int rh, double screenSize, int ppi,
               String platformName,
               boolean hasNotch, boolean hasIsland, boolean hasHole, boolean hasHomeIndicator,
               int safeTop, int safeBottom, int safeLeft, int safeRight,
               String systemFont, String proportionalFont, String monoFont,
               int fontSmall, int fontMedium, int fontLarge,
               boolean tablet) {
            this.id = id;
            this.brand = brand;
            this.os = os;
            this.year = year;
            this.form = form;
            this.name = name;
            this.resolutionW = rw;
            this.resolutionH = rh;
            this.screenSize = screenSize;
            this.ppi = ppi;
            this.platformName = platformName;
            this.hasNotch = hasNotch;
            this.hasIsland = hasIsland;
            this.hasHole = hasHole;
            this.hasHomeIndicator = hasHomeIndicator;
            this.safeTop = safeTop;
            this.safeBottom = safeBottom;
            this.safeLeft = safeLeft;
            this.safeRight = safeRight;
            this.systemFont = systemFont;
            this.proportionalFont = proportionalFont;
            this.monoFont = monoFont;
            this.fontSmall = fontSmall;
            this.fontMedium = fontMedium;
            this.fontLarge = fontLarge;
            this.tablet = tablet;
        }

        public boolean matchesFormFilter(String filter) {
            if (filter == null || "all".equals(filter)) return true;
            if ("phone".equals(filter)) return FORM_PHONE.equals(form);
            if ("tablet".equals(filter)) return FORM_TABLET.equals(form);
            if ("fold".equals(filter)) return FORM_FOLDABLE.equals(form);
            return true;
        }

        public boolean matchesQuery(String query) {
            if (query == null || query.isEmpty()) return true;
            String q = query.toLowerCase();
            return name.toLowerCase().contains(q) || brand.toLowerCase().contains(q);
        }
    }

    private static List<Device> CACHE;
    private static List<String> BRANDS_CACHE;

    /** Bundled JSON resource path; loaded once and cached. */
    public static synchronized List<Device> all() {
        if (CACHE == null) {
            CACHE = load();
        }
        return CACHE;
    }

    /** Distinct brand names ordered by descending device count. */
    public static synchronized List<String> brands() {
        if (BRANDS_CACHE == null) {
            Set<String> seen = new TreeSet<>();
            for (Device d : all()) seen.add(d.brand);
            BRANDS_CACHE = new ArrayList<>(seen);
        }
        return BRANDS_CACHE;
    }

    public static Device findById(String id) {
        if (id == null) return null;
        for (Device d : all()) {
            if (id.equals(d.id)) return d;
        }
        return null;
    }

    @SuppressWarnings("unchecked")
    private static List<Device> load() {
        InputStream is = Display.getInstance().getResourceAsStream(
                DeviceDatabase.class, "/devices.json");
        if (is == null) {
            Log.p("devices.json missing — falling back to empty device list");
            return Collections.emptyList();
        }
        try (InputStreamReader r = new InputStreamReader(is, "UTF-8")) {
            JSONParser p = new JSONParser();
            Map<String, Object> root = p.parseJSON(r);
            Object arr = root.get("devices");
            if (!(arr instanceof List)) {
                return Collections.emptyList();
            }
            List<Map<String, Object>> raw = (List<Map<String, Object>>) arr;
            List<Device> out = new ArrayList<>(raw.size());
            for (Map<String, Object> m : raw) {
                Device d = parseDevice(m);
                if (d != null) out.add(d);
            }
            // Sort by year desc, then brand, then name
            Collections.sort(out, new Comparator<Device>() {
                @Override
                public int compare(Device a, Device b) {
                    int c = Integer.compare(b.year, a.year);
                    if (c != 0) return c;
                    c = a.brand.compareToIgnoreCase(b.brand);
                    if (c != 0) return c;
                    return a.name.compareToIgnoreCase(b.name);
                }
            });
            return Collections.unmodifiableList(out);
        } catch (IOException err) {
            Log.e(err);
            return Collections.emptyList();
        }
    }

    @SuppressWarnings("unchecked")
    private static Device parseDevice(Map<String, Object> m) {
        try {
            String id = str(m, "id", "");
            String brand = str(m, "brand", "Unknown");
            String name = str(m, "name", "?");
            String os = str(m, "os", "");
            int year = num(m, "year", 0);
            String form = str(m, "form", FORM_PHONE);
            int w = num(m, "w", 0);
            int h = num(m, "h", 0);
            int ppi = num(m, "ppi", 0);
            double inches = numDouble(m, "inches", 0);
            String platform = str(m, "platform", "and");
            boolean tablet = bool(m, "tablet", false);
            boolean hasNotch = bool(m, "hasNotch", false);
            boolean hasIsland = bool(m, "hasIsland", false);
            boolean hasHole = bool(m, "hasHole", false);
            boolean hasHome = bool(m, "hasHome", false);
            int safeTop = num(m, "safeTop", 0);
            int safeBottom = num(m, "safeBottom", 0);

            Map<String, Object> fonts = m.get("fonts") instanceof Map
                    ? (Map<String, Object>) m.get("fonts")
                    : Collections.<String, Object>emptyMap();
            String sysFont = str(fonts, "system", "Helvetica");
            String propFont = str(fonts, "prop", sysFont);
            String monoFont = str(fonts, "mono", "Courier");
            int sm = num(fonts, "small", 12);
            int md = num(fonts, "medium", 15);
            int lg = num(fonts, "large", 22);

            if (id.isEmpty()) id = (brand + "_" + name).toLowerCase();
            if (w <= 0 || h <= 0 || ppi <= 0) return null;
            return new Device(id, brand, os, year, form, name, w, h, inches, ppi, platform,
                    hasNotch, hasIsland, hasHole, hasHome,
                    safeTop, safeBottom, 0, 0,
                    sysFont, propFont, monoFont, sm, md, lg, tablet);
        } catch (Exception err) {
            Log.e(err);
            return null;
        }
    }

    private static String str(Map<String, Object> m, String key, String def) {
        Object v = m.get(key);
        if (v == null) return def;
        return v.toString();
    }

    private static int num(Map<String, Object> m, String key, int def) {
        Object v = m.get(key);
        if (v == null) return def;
        if (v instanceof Number) return ((Number) v).intValue();
        try { return Integer.parseInt(v.toString()); } catch (NumberFormatException nfe) {
            try { return (int) Double.parseDouble(v.toString()); } catch (NumberFormatException nfe2) { return def; }
        }
    }

    private static double numDouble(Map<String, Object> m, String key, double def) {
        Object v = m.get(key);
        if (v == null) return def;
        if (v instanceof Number) return ((Number) v).doubleValue();
        try { return Double.parseDouble(v.toString()); } catch (NumberFormatException nfe) { return def; }
    }

    private static boolean bool(Map<String, Object> m, String key, boolean def) {
        Object v = m.get(key);
        if (v == null) return def;
        if (v instanceof Boolean) return (Boolean) v;
        String s = v.toString().toLowerCase();
        return "true".equals(s) || "1".equals(s) || "yes".equals(s);
    }

    private DeviceDatabase() {}
}
