// Auto-generated by Codename One from the com.codename1.surfaces framework.
// Compiled ONLY into the CN1Widgets extension target (iOS 16.1+). Generic renderer that
// lowers the canonical surfaces node tree (schema v1) to SwiftUI. This is data-driven:
// the same code renders every widget kind and live activity of every app.

import Foundation
import SwiftUI
import UIKit

/// Everything a render pass needs besides the node itself.
struct CN1RenderContext {
    /// Flat state map of the active timeline entry / live activity update; resolves ${key}.
    var state: [String: Any]
    /// Directory holding the published PNG blobs, nil when images cannot resolve.
    var imagesDir: URL?
    /// Widget kind id or live activity type, used as the src of action deep links.
    var source: String
    /// Whether per-node Link actions work in this context. Small widgets and compact
    /// island regions only support the root action (widgetURL / default tap).
    var allowLinks: Bool
    /// Layout axis of the enclosing container, so weighted children expand along it.
    var parentAxis: Axis?
}

private let cn1MaxDepth = 8

/// Renders one node (recursively) to SwiftUI. Unknown node types render as empty views so
/// newer documents degrade gracefully on older renderers.
func cn1RenderNode(_ node: [String: Any], _ ctx: CN1RenderContext, depth: Int = 0) -> AnyView {
    if depth > cn1MaxDepth {
        return AnyView(EmptyView())
    }
    let content: AnyView
    switch cn1Str(node, "t") ?? "" {
    case "col":
        content = cn1RenderStack(node, ctx, depth: depth, axis: .vertical)
    case "row":
        content = cn1RenderStack(node, ctx, depth: depth, axis: .horizontal)
    case "box":
        content = cn1RenderBox(node, ctx, depth: depth)
    case "text":
        content = cn1RenderText(node, ctx)
    case "dyn":
        content = cn1RenderDynamicText(node, ctx)
    case "img":
        content = cn1RenderImage(node, ctx)
    case "prog":
        content = cn1RenderProgress(node, ctx)
    case "spacer":
        content = AnyView(Spacer(minLength: cn1CGFloat(node["min"]) ?? 0))
    default:
        content = AnyView(EmptyView())
    }
    return cn1ApplyModifiers(content, node: node, ctx: ctx)
}

// MARK: - Containers

private func cn1RenderStack(_ node: [String: Any], _ ctx: CN1RenderContext, depth: Int, axis: Axis) -> AnyView {
    let children = cn1Children(node)
    let spacing = cn1CGFloat(node["spacing"]) ?? 0
    var childCtx = ctx
    childCtx.parentAxis = axis
    if axis == .vertical {
        let alignment = cn1HorizontalAlignment(node["align"])
        return AnyView(VStack(alignment: alignment, spacing: spacing) {
            ForEach(0..<children.count, id: \.self) { i in
                cn1RenderNode(children[i], childCtx, depth: depth + 1)
            }
        })
    }
    let alignment = cn1VerticalAlignment(node["align"])
    return AnyView(HStack(alignment: alignment, spacing: spacing) {
        ForEach(0..<children.count, id: \.self) { i in
            cn1RenderNode(children[i], childCtx, depth: depth + 1)
        }
    })
}

private func cn1RenderBox(_ node: [String: Any], _ ctx: CN1RenderContext, depth: Int) -> AnyView {
    let children = cn1Children(node)
    let boxAlignment = cn1Alignment(node["align"]) ?? .center
    var childCtx = ctx
    childCtx.parentAxis = nil
    return AnyView(ZStack(alignment: boxAlignment) {
        ForEach(0..<children.count, id: \.self) { i in
            let child = children[i]
            let rendered = cn1RenderNode(child, childCtx, depth: depth + 1)
            // Per-child alignment inside the box: expand a clear frame to the box bounds and
            // pin the child inside it (ZStack itself only supports one shared alignment).
            if let childAlignment = cn1Alignment(child["align"]) {
                rendered.frame(maxWidth: .infinity, maxHeight: .infinity, alignment: childAlignment)
            } else {
                rendered
            }
        }
    })
}

private func cn1Children(_ node: [String: Any]) -> [[String: Any]] {
    var out: [[String: Any]] = []
    for child in cn1Arr(node, "ch") ?? [] {
        if let dict = child as? [String: Any] {
            out.append(dict)
        }
    }
    return out
}

private func cn1HorizontalAlignment(_ value: Any?) -> HorizontalAlignment {
    switch value as? String {
    case "topLeading", "leading", "bottomLeading":
        return .leading
    case "topTrailing", "trailing", "bottomTrailing":
        return .trailing
    default:
        return .center
    }
}

private func cn1VerticalAlignment(_ value: Any?) -> VerticalAlignment {
    switch value as? String {
    case "topLeading", "top", "topTrailing":
        return .top
    case "bottomLeading", "bottom", "bottomTrailing":
        return .bottom
    default:
        return .center
    }
}

// MARK: - Text

private func cn1StyledText(_ text: Text, _ node: [String: Any]) -> AnyView {
    let size = cn1CGFloat(node["size"]) ?? 14
    var styled = text.font(.system(size: size, weight: cn1FontWeight(node["fw"])))
    if let color = cn1Color(node["color"]) {
        styled = styled.foregroundColor(color)
    }
    if let maxLines = cn1Int(node["maxLines"]), maxLines > 0 {
        return AnyView(styled.lineLimit(maxLines))
    }
    return AnyView(styled)
}

private func cn1RenderText(_ node: [String: Any], _ ctx: CN1RenderContext) -> AnyView {
    let raw = cn1Str(node, "text") ?? ""
    return cn1StyledText(Text(cn1Interpolate(raw, state: ctx.state)), node)
}

/// Dynamic text ticks natively on the OS clock with no process wakeups -- the killer
/// feature for countdowns and ETAs. The date comes from a state key ("dateKey") or an
/// epoch-ms literal ("date").
private func cn1RenderDynamicText(_ node: [String: Any], _ ctx: CN1RenderContext) -> AnyView {
    var date: Date?
    if let key = cn1Str(node, "dateKey") {
        date = cn1DateMs(ctx.state[key])
    }
    if date == nil {
        date = cn1DateMs(node["date"])
    }
    guard let resolved = date else {
        return cn1StyledText(Text(""), node)
    }
    let text: Text
    switch cn1Str(node, "style") ?? "timerDown" {
    case "timerUp":
        // .timer counts up once the date passes (and down while it is still ahead).
        text = Text(resolved, style: .timer)
    case "time":
        text = Text(resolved, style: .time)
    case "date":
        text = Text(resolved, style: .date)
    case "relative":
        text = Text(resolved, style: .relative)
    default: // timerDown
        let now = Date()
        if resolved > now {
            // timerInterval stops at zero instead of counting into negative time.
            text = Text(timerInterval: now...resolved, countsDown: true)
        } else {
            text = Text("0:00")
        }
    }
    return cn1StyledText(text, node)
}

// MARK: - Images

private let cn1MaxImageDimension: CGFloat = 1024

/// Widget extensions run under a tight (~30MB) memory cap: decode from the app group
/// container and downsample anything larger than 1024px on its longest side.
private func cn1LoadImage(_ dir: URL?, name: String) -> UIImage? {
    guard let dir = dir, !name.isEmpty else {
        return nil
    }
    let path = dir.appendingPathComponent(name + ".png").path
    guard let image = UIImage(contentsOfFile: path) else {
        return nil
    }
    let largest = max(image.size.width, image.size.height)
    if largest <= cn1MaxImageDimension {
        return image
    }
    let scale = cn1MaxImageDimension / largest
    let target = CGSize(width: image.size.width * scale, height: image.size.height * scale)
    let renderer = UIGraphicsImageRenderer(size: target)
    return renderer.image { _ in
        image.draw(in: CGRect(origin: .zero, size: target))
    }
}

private func cn1RenderImage(_ node: [String: Any], _ ctx: CN1RenderContext) -> AnyView {
    guard let ui = cn1LoadImage(ctx.imagesDir, name: cn1Str(node, "name") ?? "") else {
        return AnyView(Color.clear)
    }
    let tint = cn1Color(node["tint"])
    var image = Image(uiImage: ui)
    if tint != nil {
        image = image.renderingMode(.template)
    }
    let scaled: AnyView
    switch cn1Str(node, "scale") ?? "fit" {
    case "fill":
        scaled = AnyView(image.resizable().scaledToFill().clipped())
    case "center":
        scaled = AnyView(image)
    default: // fit
        scaled = AnyView(image.resizable().scaledToFit())
    }
    if let tint = tint {
        return AnyView(scaled.foregroundColor(tint))
    }
    return scaled
}

// MARK: - Progress

private func cn1RenderProgress(_ node: [String: Any], _ ctx: CN1RenderContext) -> AnyView {
    let circular = cn1Str(node, "style") == "circular"
    let color = cn1Color(node["color"])
    var view: AnyView
    if let start = cn1DateMs(node["start"]), let end = cn1DateMs(node["end"]), end > start {
        // Date-interval progress advances natively on the OS clock, like dynamic text.
        // The circular style falls back to the same linear bar (no native timer ring).
        view = AnyView(ProgressView(timerInterval: start...end, countsDown: false) {
            EmptyView()
        } currentValueLabel: {
            EmptyView()
        }.progressViewStyle(.linear))
    } else {
        var value = cn1Double(node["value"]) ?? 0
        if let key = cn1Str(node, "valueKey"), let stateValue = cn1Double(ctx.state[key]) {
            value = stateValue
        }
        value = min(max(value, 0), 1)
        if circular {
            view = AnyView(Gauge(value: value, in: 0...1) {
                EmptyView()
            }.gaugeStyle(.accessoryCircularCapacity))
        } else {
            view = AnyView(ProgressView(value: value))
        }
    }
    if let color = color {
        view = AnyView(view.tint(color))
    }
    return view
}

// MARK: - Shared modifiers

/// Applies the shared node styling in the framework's canonical order: padding sits inside
/// the background, the background is clipped by the corner radius, fixed sizes wrap the
/// decorated node, weights expand along the parent axis, actions wrap everything.
private func cn1ApplyModifiers(_ view: AnyView, node: [String: Any], ctx: CN1RenderContext) -> AnyView {
    var out = view
    if let pad = node["pad"] as? [Any], pad.count == 4 {
        let insets = EdgeInsets(
                top: cn1CGFloat(pad[0]) ?? 0,
                leading: cn1CGFloat(pad[3]) ?? 0,
                bottom: cn1CGFloat(pad[2]) ?? 0,
                trailing: cn1CGFloat(pad[1]) ?? 0)
        out = AnyView(out.padding(insets))
    }
    let corner = cn1CGFloat(node["corner"]) ?? 0
    if let background = cn1Color(node["bg"]) {
        out = AnyView(out.background(RoundedRectangle(cornerRadius: corner).fill(background)))
    } else if corner > 0 {
        out = AnyView(out.clipShape(RoundedRectangle(cornerRadius: corner)))
    }
    let width = cn1CGFloat(node["w"])
    let height = cn1CGFloat(node["h"])
    if width != nil || height != nil {
        out = AnyView(out.frame(width: width, height: height))
    }
    if let weight = cn1Double(node["weight"]), weight > 0 {
        // Expand along the parent's layout axis and bias the space distribution.
        // layoutPriority approximates proportional weights, the documented LCD.
        switch ctx.parentAxis {
        case .horizontal:
            out = AnyView(out.frame(maxWidth: .infinity))
        case .vertical:
            out = AnyView(out.frame(maxHeight: .infinity))
        default:
            out = AnyView(out.frame(maxWidth: .infinity, maxHeight: .infinity))
        }
        out = AnyView(out.layoutPriority(weight))
    }
    if ctx.allowLinks, let action = cn1Dict(node, "action"),
       let url = cn1ActionURL(source: ctx.source, action: action) {
        out = AnyView(Link(destination: url) { out })
    }
    return out
}

/// Finds the root node's action deep link, applied via .widgetURL so the root action works
/// on families where Link is unsupported (small widgets, lock screen accessories).
func cn1RootActionURL(_ node: [String: Any]?, source: String) -> URL? {
    guard let node = node, let action = cn1Dict(node, "action") else {
        return nil
    }
    return cn1ActionURL(source: source, action: action)
}
