// Auto-generated by Codename One from the com.codename1.surfaces framework.
// Compiled into the MAIN APP target (copied into <MainClass>-src by the build).
// WidgetKit and ActivityKit are Swift-only frameworks, so the Objective-C surfaces
// natives in IOSNative.m reach this class via NSClassFromString(@"CN1SurfaceBridge")
// and typed objc_msgSend casts -- keep the @objc names below stable.
//
// The app target may deploy far below iOS 16.1: every WidgetKit/ActivityKit reference
// is behind canImport + runtime #available guards so the class compiles and loads on
// any deployment target and answers "unsupported" gracefully.

import Foundation

#if canImport(WidgetKit)
import WidgetKit
#endif
#if canImport(ActivityKit) && !targetEnvironment(macCatalyst)
import ActivityKit
#endif

@objc(CN1SurfaceBridge)
public class CN1SurfaceBridge: NSObject {

    // WidgetCenter.getCurrentConfigurations is async; cache the last answer so the
    // synchronous Java query returns something useful (0 while still unknown, the
    // documented contract). Each call refreshes the cache for the next one.
    private static let countsLock = NSLock()
    private static var cachedCounts: [String: Int] = [:]

    /// Re-renders the widgets of one kind from their persisted timelines; an empty kind
    /// reloads every kind.
    @objc public static func reloadTimelines(_ kind: String) {
        #if canImport(WidgetKit)
        if #available(iOS 14.0, *) {
            if kind.isEmpty {
                WidgetCenter.shared.reloadAllTimelines()
            } else {
                WidgetCenter.shared.reloadTimelines(ofKind: kind)
            }
        }
        #endif
    }

    /// Number of installed widget instances of a kind; 0 while the async WidgetCenter
    /// answer has not arrived yet.
    @objc public static func installedCount(_ kind: String) -> Int {
        #if canImport(WidgetKit)
        if #available(iOS 14.0, *) {
            WidgetCenter.shared.getCurrentConfigurations { result in
                if case .success(let infos) = result {
                    var counts: [String: Int] = [:]
                    for info in infos {
                        counts[info.kind, default: 0] += 1
                    }
                    countsLock.lock()
                    cachedCounts = counts
                    countsLock.unlock()
                }
            }
            countsLock.lock()
            let count = cachedCounts[kind] ?? 0
            countsLock.unlock()
            return count
        }
        #endif
        return 0
    }

    /// True when ActivityKit is available and the user has not disabled live activities.
    @objc public static func activitiesEnabled() -> Bool {
        #if canImport(ActivityKit) && !targetEnvironment(macCatalyst)
        if #available(iOS 16.1, *) {
            return ActivityAuthorizationInfo().areActivitiesEnabled
        }
        #endif
        return false
    }

    /// Starts a live activity from the serialized descriptor (which embeds the initial
    /// state). Returns the ActivityKit activity id, or "" on failure.
    @objc public static func startActivity(_ descriptorJson: String) -> String {
        #if canImport(ActivityKit) && !targetEnvironment(macCatalyst)
        if #available(iOS 16.1, *) {
            guard let data = descriptorJson.data(using: .utf8),
                  let doc = (try? JSONSerialization.jsonObject(with: data, options: [])) as? [String: Any] else {
                return ""
            }
            let activityType = doc["type"] as? String ?? ""
            var stateJson = "{}"
            if let state = doc["state"], JSONSerialization.isValidJSONObject(state),
               let stateData = try? JSONSerialization.data(withJSONObject: state, options: []),
               let encoded = String(data: stateData, encoding: .utf8) {
                stateJson = encoded
            }
            let attributes = CN1SurfaceAttributes(descriptorJson: descriptorJson, activityType: activityType)
            let contentState = CN1SurfaceAttributes.ContentState(stateJson: stateJson)
            do {
                // The request(attributes:contentState:pushType:) signature is the iOS 16.1
                // baseline (deprecated in 16.2 in favor of ActivityContent); intentional so
                // the extension's 16.1 deployment target keeps working.
                let activity = try Activity<CN1SurfaceAttributes>.request(
                        attributes: attributes, contentState: contentState, pushType: nil)
                // Reclaim any image blobs left by a prior activity that has fully ended.
                cn1SweepActivityImages()
                return activity.id
            } catch {
                NSLog("CN1SurfaceBridge: failed to start live activity: %@", String(describing: error))
                // The Java bridge wrote this start's images before calling us; the request
                // failed so no activity references them -- reclaim them now.
                cn1SweepActivityImages()
                return ""
            }
        }
        #endif
        return ""
    }

    /// Pushes a fresh state into a running activity; the views re-interpolate locally.
    @objc public static func updateActivity(_ id: String, stateJson: String) {
        #if canImport(ActivityKit) && !targetEnvironment(macCatalyst)
        if #available(iOS 16.1, *) {
            let contentState = CN1SurfaceAttributes.ContentState(stateJson: stateJson)
            Task {
                for activity in Activity<CN1SurfaceAttributes>.activities where activity.id == id {
                    await activity.update(using: contentState)
                }
            }
        }
        #endif
    }

    /// Ends a running activity, optionally showing a final state before dismissal.
    @objc public static func endActivity(_ id: String, finalStateJson: String?, immediate: Bool) {
        #if canImport(ActivityKit) && !targetEnvironment(macCatalyst)
        if #available(iOS 16.1, *) {
            let finalState = finalStateJson.map { CN1SurfaceAttributes.ContentState(stateJson: $0) }
            Task {
                for activity in Activity<CN1SurfaceAttributes>.activities where activity.id == id {
                    await activity.end(using: finalState, dismissalPolicy: immediate ? .immediate : .default)
                }
                // Reclaim image blobs after the end resolves: a non-immediate dismissal leaves the
                // activity lingering in Activity.activities (and its artwork referenced), so only a
                // truly-gone activity's images are swept.
                cn1SweepActivityImages()
            }
        }
        #endif
    }

    /// Deletes live-activity image blobs no longer referenced by ANY tracked activity.
    /// Activity.activities is authoritative for what is still live OR lingering after end() (a
    /// dismissed activity remains there until the system removes it), and every activity's
    /// descriptorJson carries the complete `images` reference list, so a content-hash blob
    /// survives while any activity still references it and is reclaimed once none do -- fixing the
    /// unbounded growth of the shared cn1surfaces/activities directory.
    ///
    /// Guarded like every other ActivityKit member here: ActivityKit is absent on Mac Catalyst,
    /// tvOS and watchOS (where this app-target glue still compiles), so both the body and its
    /// call sites live inside this same condition.
    #if canImport(ActivityKit) && !targetEnvironment(macCatalyst)
    @available(iOS 16.1, *)
    static func cn1SweepActivityImages() {
        // Resolve the activities image dir inline from the app-group constant: this bridge is
        // compiled into the APP target, which does not include CN1SurfaceModel.swift (its
        // cn1SurfacesActivitiesDir lives only in the widget extension), so mirror the same path.
        guard let container = FileManager.default.containerURL(
                forSecurityApplicationGroupIdentifier: cn1SurfacesAppGroup) else {
            return
        }
        let dir = container.appendingPathComponent("cn1surfaces", isDirectory: true)
                .appendingPathComponent("activities", isDirectory: true)
        var referenced = Set<String>()
        for activity in Activity<CN1SurfaceAttributes>.activities {
            guard let data = activity.attributes.descriptorJson.data(using: .utf8),
                  let doc = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any],
                  let names = doc["images"] as? [Any] else {
                continue
            }
            for name in names {
                if let s = name as? String {
                    referenced.insert(s)
                }
            }
        }
        let fm = FileManager.default
        guard let entries = try? fm.contentsOfDirectory(at: dir, includingPropertiesForKeys: nil) else {
            return
        }
        for url in entries where url.pathExtension == "png" {
            if !referenced.contains(url.deletingPathExtension().lastPathComponent) {
                try? fm.removeItem(at: url)
            }
        }
    }
    #endif
}
