codename1.android.keystore=
codename1.android.keystoreAlias=
codename1.android.keystorePassword=
codename1.arg.block_server_registration=true
codename1.arg.ios.newStorageLocation=true
codename1.arg.ios.NSCameraUsageDescription=Some functionality of the application requires your camera
codename1.arg.java.version=17
codename1.arg.javascript.inject_proxy=false
codename1.cssTheme=true
codename1.displayName=CN1Playground
codename1.icon=icon.png
codename1.ios.appid=Q5GHSKAL2F.com.codenameone.playground
codename1.ios.certificate=
codename1.ios.certificatePassword=
codename1.ios.debug.certificate=
codename1.ios.debug.certificatePassword=
codename1.ios.debug.provision=
codename1.ios.provision=
codename1.ios.release.certificate=
codename1.ios.release.certificatePassword=
codename1.ios.release.provision=
codename1.kotlin=false
codename1.mainName=CN1Playground
codename1.packageName=com.codenameone.playground
codename1.secondaryTitle=Hello World
codename1.vendor=CodenameOne
codename1.version=1.0
