/*
 * Copyright (c) 2026, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Codename One through http://www.codenameone.com/ if you
 * need additional information or have any questions.
 */
package com.codename1.intents;

import java.util.List;
import java.util.Map;

/// Internal contract between the build-time-generated intent table and the
/// framework. Application code should neither implement nor call this --
/// declare intents with `com.codename1.annotations.AppIntent` and, if you need
/// to run one yourself, call [Intents#invoke].
///
/// A single implementation is generated by the Codename One Maven plugin from
/// the `AppIntent` and `IntentEntity` annotations in the project and installs
/// itself on [Intents] during startup. Every call it makes into application code
/// is a direct static invocation emitted at build time: there is no reflection,
/// which is what lets the whole mechanism survive the iOS translator's dead-code
/// elimination and Android's obfuscation.
public interface IntentDispatcher {

    /// Every intent declared in this application.
    List<IntentDeclaration> describe();

    /// Runs one intent. Parameter values arrive as the wire types -- `String`
    /// for entities, which the generated code resolves through the entity's
    /// `BY_ID` query before calling the handler.
    ///
    /// #### Parameters
    ///
    /// - `intentId`: the declared intent id
    /// - `params`: parameter values keyed by name, never null
    /// - `ctx`: the invocation context
    ///
    /// #### Returns
    ///
    /// the handler's result, or null when no intent has that id
    IntentResult invoke(String intentId, Map<String, Object> params, IntentContext ctx);

    /// Answers an entity query on behalf of the platform, so the system can run
    /// its own picker before the handler is called.
    ///
    /// #### Parameters
    ///
    /// - `entityType`: the entity type id
    /// - `kind`: `byId`, `suggested` or `search`
    /// - `argument`: the id for `byId`, the search text for `search`, ignored
    ///   for `suggested`
    ///
    /// #### Returns
    ///
    /// the matching entities, empty when the type declares no such query
    List<Entity> queryEntities(String entityType, String kind, String argument);
}
