/*
 * Copyright (c) 2026, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Codename One in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Codename One through http://www.codenameone.com/ if
 * you need additional information or have any questions.
 */
package com.codename1.impl.javase;

import org.junit.jupiter.api.Test;

import java.awt.Rectangle;
import java.lang.reflect.Method;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * A skin generated by the skin designer paints its notch, Dynamic Island and
 * punch-hole cutouts ON the screen rect, which is where they sit on the
 * hardware. That also puts them on the simulator's input surface, so the skin
 * declares them in a {@code cutouts} property and the pointer path drops
 * events inside them; otherwise a click on an opaque notch reaches whatever
 * app content is hidden underneath.
 */
public class JavaSEPortSkinCutoutTest {

    @SuppressWarnings("unchecked")
    private static List<Rectangle> parse(String spec) throws Exception {
        Method m = JavaSEPort.class.getDeclaredMethod("parseCutouts", String.class);
        m.setAccessible(true);
        return (List<Rectangle>) m.invoke(null, spec);
    }

    @SuppressWarnings("unchecked")
    private static List<Rectangle> rotate(List<Rectangle> portraitCutouts, int displayH)
            throws Exception {
        Method m = JavaSEPort.class.getDeclaredMethod("rotateCutoutsForLandscape",
                List.class, int.class);
        m.setAccessible(true);
        return (List<Rectangle>) m.invoke(null, portraitCutouts, displayH);
    }

    @Test
    public void aSkinThatDeclaresNoCutoutsKeepsTheOldPointerBehaviour() throws Exception {
        // Every skin written before the property existed -- including the
        // shipped iPhoneX and watch skins -- must be untouched by this.
        assertNull(parse(null), "no property means no cutout rectangles");
        assertNull(parse(""), "an empty property means no cutout rectangles");
        assertNull(parse("   "), "a blank property means no cutout rectangles");
    }

    @Test
    public void malformedEntriesAreDroppedWithoutLosingTheRest() throws Exception {
        // A bad entry leaves that cutout clickable, which is the old
        // behaviour; it must not take the whole skin's input handling with it.
        List<Rectangle> rects = parse("10,0,100,40;garbage;nope,1,2,3;5,5,0,9;20,30,40,50");
        assertNotNull(rects);
        assertEquals(2, rects.size(), "only the two well-formed, non-empty rectangles survive");
        assertEquals(new Rectangle(10, 0, 100, 40), rects.get(0));
        assertEquals(new Rectangle(20, 30, 40, 50), rects.get(1));
        assertNull(parse("garbage"), "a property with nothing usable in it is the same as none");
    }

    @Test
    public void aNotchAnchoredToThePortraitTopLandsOnTheLandscapeRightEdge() throws Exception {
        // skin_l.png is skin.png through Image.rotate90Degrees, which maps
        // (x, y) to (height - 1 - y, x). An iPhone 13 Pro Max notch: 482px
        // wide, 120px tall, centred on a 1284x2778 display.
        int displayW = 1284;
        int displayH = 2778;
        List<Rectangle> portraitCutouts = parse("401,0,482,120");
        assertNotNull(portraitCutouts);

        List<Rectangle> landscapeCutouts = rotate(portraitCutouts, displayH);
        assertNotNull(landscapeCutouts);
        Rectangle r = landscapeCutouts.get(0);

        // The landscape display is displayH wide by displayW tall.
        assertEquals(displayH - 120, r.x, "the notch sits against the landscape right edge");
        assertEquals(displayH, r.x + r.width, "and reaches it exactly");
        assertEquals(401, r.y);
        assertEquals(120, r.width, "the portrait height becomes the landscape width");
        assertEquals(482, r.height);
        assertTrue(r.y + r.height <= displayW, "and stays inside the landscape display");
    }

    @Test
    public void aPointInsideACutoutIsRejectedAndOneBesideItIsNot() throws Exception {
        JavaSEPort port = new JavaSEPort();
        Method isOnCutout = JavaSEPort.class.getDeclaredMethod("isPointerOnCutout",
                int.class, int.class);
        isOnCutout.setAccessible(true);

        java.lang.reflect.Field cutouts = JavaSEPort.class.getDeclaredField("cutoutsPortrait");
        cutouts.setAccessible(true);
        java.lang.reflect.Field portraitFlag = JavaSEPort.class.getDeclaredField("portrait");
        portraitFlag.setAccessible(true);
        portraitFlag.setBoolean(port, true);

        assertFalse((Boolean) isOnCutout.invoke(port, 640, 20),
                "with no cutouts declared nothing is rejected");

        cutouts.set(port, parse("401,0,482,120"));

        assertTrue((Boolean) isOnCutout.invoke(port, 640, 20),
                "the middle of the notch is not display");
        assertTrue((Boolean) isOnCutout.invoke(port, 401, 0),
                "the top-left corner is inside");
        assertFalse((Boolean) isOnCutout.invoke(port, 883, 20),
                "one pixel past the right edge is display again");
        assertFalse((Boolean) isOnCutout.invoke(port, 640, 120),
                "the first row below the notch is display again -- that is where "
                        + "the status bar content actually renders");
        assertFalse((Boolean) isOnCutout.invoke(port, 100, 20),
                "the screen beside the notch takes touches on the hardware, so it "
                        + "must keep taking them here");
    }
}
