/*
 * Copyright (c) 2012, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Codename One through http://www.codenameone.com/ if you
 * need additional information or have any questions.
 */

/*
 * The SQLite binding shared by the native Windows and Linux ports.
 *
 * Both ports are ParparVM C targets and need exactly the same code, but their native entry points
 * are name mangled from different Java classes. Rather than keeping two copies of four hundred
 * lines of C in step by hand, the logic lives here once as static functions and the mangled entry
 * points are generated by CN1_DB_DEFINE_NATIVES(prefix). Each port's own .c file is then four
 * lines long.
 *
 * This file is emitted by the translator alongside the bundled engine, and only for applications
 * that use com.codename1.db, so the port .c files guard their include with __has_include.
 */
#ifndef CN1_DB_SQLITE_IMPL_H
#define CN1_DB_SQLITE_IMPL_H

/*
 * The engine header is emitted only for applications that use com.codename1.db. When it is absent
 * this file still defines every native entry point, as a stub that reports no database support.
 *
 * Defining them unconditionally matters: the translator can be driven directly, without the
 * builder that sets the flag, and an application whose classes reference the database API would
 * then fail to link with no useful explanation. A stub turns that into an ordinary IOException.
 */
#if defined(__has_include)
#  if __has_include("cn1_sqlite3.h")
#    define CN1_DB_ENGINE_PRESENT 1
#  endif
#else
#  define CN1_DB_ENGINE_PRESENT 1
#endif

/* Generated by the translator; supplies __NEW_java_io_IOException and its constructor. Needed by
 * both branches below, so it sits above the gate. */
#include "java_io_IOException.h"

#ifdef CN1_DB_ENGINE_PRESENT
#include "cn1_sqlite3.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <errno.h>

extern JAVA_OBJECT allocArray(CODENAME_ONE_THREAD_STATE, int length, struct clazz* type, int primitiveSize, int dim);

/*
 * SQLCipher compatible keying, provided by the bundled engine.
 */
extern int sqlite3_key(sqlite3 *db, const void *pKey, int nKey);
extern int sqlite3_rekey(sqlite3 *db, const void *pKey, int nKey);

/** Raises java.io.IOException with an explicit message. */
static void cn1DbThrow(CODENAME_ONE_THREAD_STATE, const char* message) {
    JAVA_OBJECT ex = __NEW_java_io_IOException(threadStateData);
    java_io_IOException___INIT_____java_lang_String(threadStateData, ex,
            newStringFromCString(threadStateData, message));
    throwException(threadStateData, ex);
}

/** Raises java.io.IOException carrying the connection's last error message. */
static void cn1DbThrowSqlite(CODENAME_ONE_THREAD_STATE, sqlite3* db, const char* context) {
    char buffer[512];
    const char* detail = db != NULL ? sqlite3_errmsg(db) : "unknown SQLite error";
    snprintf(buffer, sizeof(buffer), "%s: %s", context, detail);
    cn1DbThrow(threadStateData, buffer);
}

/**
 * Selects the SQLCipher 4 on-disk format.
 *
 * Without this the engine would use its own cipher scheme, and the resulting file could not be
 * opened on any other Codename One platform.
 */
static int cn1DbApplyCipherProfile(sqlite3* db) {
    if (sqlite3_exec(db, "PRAGMA cipher = 'sqlcipher'", NULL, NULL, NULL) != SQLITE_OK) {
        return SQLITE_ERROR;
    }
    return sqlite3_exec(db, "PRAGMA legacy = 4", NULL, NULL, NULL);
}

/** Confirms a key actually decrypts the database; SQLCipher applies keys lazily. */
static int cn1DbProbeKey(sqlite3* db) {
    return sqlite3_exec(db, "SELECT count(*) FROM sqlite_master", NULL, NULL, NULL);
}

/** Raises when a bind fails. SQLite unbinds the old value first, so ignoring this leaves the
 * parameter as SQL NULL and the statement runs with something the caller never supplied. */
static void cn1DbCheckBind(CODENAME_ONE_THREAD_STATE, sqlite3_stmt* stmt, int rc, int index) {
    char buffer[256];
    if (rc == SQLITE_OK) {
        return;
    }
    snprintf(buffer, sizeof(buffer), "Parameter %d could not be bound: %s", index,
            sqlite3_errstr(rc));
    cn1DbThrow(threadStateData, buffer);
}

static JAVA_OBJECT cn1DbBlobToByteArray(CODENAME_ONE_THREAD_STATE, const void* bytes, int length) {
    JAVA_OBJECT arr;
    JAVA_ARRAY_BYTE* data;
    if (length < 0 || (bytes == NULL && length > 0)) {
        return JAVA_NULL;
    }
    /* A zero length blob is a blob, not SQL NULL: SQLite may hand back a null pointer for it, and
     * turning that into null would disagree with the column type and with wasNull(). */
    arr = allocArray(threadStateData, length, &class_array1__JAVA_BYTE, sizeof(JAVA_ARRAY_BYTE), 1);
    data = (JAVA_ARRAY_BYTE*)((JAVA_ARRAY)arr)->data;
    if (length > 0) {
        memcpy(data, bytes, (size_t)length);
    }
    return arr;
}

#endif /* CN1_DB_ENGINE_PRESENT */

/*
 * Generates the port's native entry points. Every non void native gets both the plain symbol and
 * the _R_<returntype> wrapper the VM calls; omitting either is a link error.
 */
#ifdef CN1_DB_ENGINE_PRESENT

#ifdef _WIN32
/* Without this, windows.h drags in the original winsock.h, whose struct timeval collides with
 * the one winsock2.h has already defined for anything else in the translation unit that needed
 * sockets -- a hard redefinition error, and the reason this include has to be spelled out rather
 * than dropped in. Guarded because the bundled engine defines it the same way. */
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <wchar.h>

/*
 * Windows takes a narrow path in the active ANSI code page, and this port's paths are UTF-8.
 *
 * sqlite3_open_v2 reads UTF-8 and gets it right, so a database under a profile directory with a
 * non-ASCII name -- the default storage location is under Local AppData, which carries the user's
 * name -- opens and works. The CRT's fopen and remove take the same bytes and read them as ANSI,
 * so they look somewhere else: exists() answers false for a database that is there, and delete()
 * sees ENOENT and reports success while leaving the file behind. The wide-character calls take
 * UTF-16 and are the only ones that agree with the engine.
 */
static wchar_t* cn1DbWidePath(const char* utf8) {
    int chars;
    wchar_t* wide;
    if (utf8 == NULL) {
        return NULL;
    }
    chars = MultiByteToWideChar(CP_UTF8, 0, utf8, -1, NULL, 0);
    if (chars <= 0) {
        return NULL;
    }
    wide = (wchar_t*)malloc((size_t)chars * sizeof(wchar_t));
    if (wide == NULL) {
        return NULL;
    }
    if (MultiByteToWideChar(CP_UTF8, 0, utf8, -1, wide, chars) <= 0) {
        free(wide);
        return NULL;
    }
    return wide;
}

/** The message for an errno value, into the caller's buffer. */
static const char* cn1DbErrorText(int code, char* buffer, size_t length) {
    /* strerror is deprecated on this toolchain, and the deprecation is a warning on every build
     * of this file rather than a one-off. strerror_s is the replacement it names. */
    if (strerror_s(buffer, length, code) != 0) {
        return "unknown error";
    }
    return buffer;
}

/** Whether a file exists, by a path the engine and the filesystem agree on. */
static int cn1DbFileExists(const char* utf8) {
    wchar_t* wide = cn1DbWidePath(utf8);
    DWORD attributes;
    if (wide == NULL) {
        return 0;
    }
    attributes = GetFileAttributesW(wide);
    free(wide);
    return attributes != INVALID_FILE_ATTRIBUTES
            && (attributes & FILE_ATTRIBUTE_DIRECTORY) == 0;
}

/** Removes a file, returning 0 on success and setting errno as remove() would. */
static int cn1DbFileRemove(const char* utf8) {
    wchar_t* wide = cn1DbWidePath(utf8);
    int result;
    if (wide == NULL) {
        errno = ENOMEM;
        return -1;
    }
    result = _wremove(wide);
    free(wide);
    return result;
}

#else

/** The message for an errno value. The buffer is unused here and kept for one signature. */
static const char* cn1DbErrorText(int code, char* buffer, size_t length) {
    (void)buffer;
    (void)length;
    return strerror(code);
}

/** Whether a file exists. Everywhere but Windows the narrow path is already the right bytes. */
static int cn1DbFileExists(const char* utf8) {
    FILE* f = fopen(utf8, "rb");
    if (f == NULL) {
        return 0;
    }
    fclose(f);
    return 1;
}

/** Removes a file, returning 0 on success and setting errno. */
static int cn1DbFileRemove(const char* utf8) {
    return remove(utf8);
}

#endif /* _WIN32 */
#define CN1_DB_DEFINE_NATIVES(PREFIX)                                                              \
                                                                                                   \
JAVA_BOOLEAN PREFIX##_sqlDbExists___java_lang_String(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT path) { \
    return cn1DbFileExists(stringToUTF8(threadStateData, path)) ? JAVA_TRUE : JAVA_FALSE;           \
}                                                                                                   \
JAVA_BOOLEAN PREFIX##_sqlDbExists___java_lang_String_R_boolean(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT path) { \
    return PREFIX##_sqlDbExists___java_lang_String(threadStateData, path);                          \
}                                                                                                   \
                                                                                                   \
JAVA_VOID PREFIX##_sqlDbDelete___java_lang_String(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT path) {    \
    const char* target = stringToUTF8(threadStateData, path);                                       \
    /* Deleting what is not there is the documented no-op. Any other failure -- a read-only file, \
     * or a Windows handle still open on it -- has to be reported, or delete() returns and the    \
     * database is still sitting there. */                                                         \
    if (cn1DbFileRemove(target) != 0 && errno != ENOENT) {                                          \
        char cn1DbDeleteMessage[512];                                                               \
        char cn1DbDeleteReason[128];                                                                \
        snprintf(cn1DbDeleteMessage, sizeof(cn1DbDeleteMessage),                                    \
                "The database %s could not be deleted: %s", target,                                 \
                cn1DbErrorText(errno, cn1DbDeleteReason, sizeof(cn1DbDeleteReason)));               \
        cn1DbThrow(threadStateData, cn1DbDeleteMessage);                                            \
    }                                                                                               \
}                                                                                                   \
                                                                                                   \
JAVA_LONG PREFIX##_sqlDbOpen___java_lang_String(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT path) {      \
    sqlite3* db = NULL;                                                                             \
    const char* p = stringToUTF8(threadStateData, path);                                            \
    int rc = sqlite3_open_v2(p, &db,                                                                \
            SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE | SQLITE_OPEN_FULLMUTEX, NULL);              \
    if (rc != SQLITE_OK) {                                                                          \
        /* Copy the message out and close before raising. throwException longjmps, so anything    \
         * after it never runs -- and SQLite hands back a usable handle even on a failed open,    \
         * which then leaks once per caught failure. */                                            \
        char cn1DbOpenMessage[512];                                                                 \
        snprintf(cn1DbOpenMessage, sizeof(cn1DbOpenMessage), "Failed to open the database: %s",     \
                db != NULL ? sqlite3_errmsg(db) : "unknown SQLite error");                          \
        if (db != NULL) {                                                                           \
            sqlite3_close_v2(db);                                                                   \
        }                                                                                           \
        cn1DbThrow(threadStateData, cn1DbOpenMessage);                                               \
        return 0;                                                                                   \
    }                                                                                               \
    return (JAVA_LONG)(intptr_t)db;                                                                 \
}                                                                                                   \
JAVA_LONG PREFIX##_sqlDbOpen___java_lang_String_R_long(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT path) { \
    return PREFIX##_sqlDbOpen___java_lang_String(threadStateData, path);                            \
}                                                                                                   \
                                                                                                   \
JAVA_BOOLEAN PREFIX##_sqlDbApplyKey___long_java_lang_String(CODENAME_ONE_THREAD_STATE, JAVA_LONG dbPeer, JAVA_OBJECT key) { \
    sqlite3* db = (sqlite3*)(intptr_t)dbPeer;                                                       \
    const char* k;                                                                                  \
    if (cn1DbApplyCipherProfile(db) != SQLITE_OK) {                                                 \
        return JAVA_FALSE;                                                                          \
    }                                                                                               \
    k = stringToUTF8(threadStateData, key);                                                         \
    if (sqlite3_key(db, k, (int)strlen(k)) != SQLITE_OK) {                                          \
        return JAVA_FALSE;                                                                          \
    }                                                                                               \
    return cn1DbProbeKey(db) == SQLITE_OK ? JAVA_TRUE : JAVA_FALSE;                                 \
}                                                                                                   \
JAVA_BOOLEAN PREFIX##_sqlDbApplyKey___long_java_lang_String_R_boolean(CODENAME_ONE_THREAD_STATE, JAVA_LONG dbPeer, JAVA_OBJECT key) { \
    return PREFIX##_sqlDbApplyKey___long_java_lang_String(threadStateData, dbPeer, key);            \
}                                                                                                   \
                                                                                                   \
/* Reports the SQLite result rather than a pass or fail, so the caller can tell a key that did not \
 * decrypt the file (SQLITE_NOTADB) from a corrupt image or a read error, which no key repairs. */  \
JAVA_INT PREFIX##_sqlDbApplyKeyStatus___long_java_lang_String(CODENAME_ONE_THREAD_STATE, JAVA_LONG dbPeer, JAVA_OBJECT key) { \
    sqlite3* db = (sqlite3*)(intptr_t)dbPeer;                                                       \
    const char* k;                                                                                  \
    int rc;                                                                                         \
    if (cn1DbApplyCipherProfile(db) != SQLITE_OK) {                                                 \
        return SQLITE_ERROR;                                                                        \
    }                                                                                               \
    k = stringToUTF8(threadStateData, key);                                                         \
    rc = sqlite3_key(db, k, (int)strlen(k));                                                        \
    if (rc != SQLITE_OK) {                                                                          \
        return rc;                                                                                  \
    }                                                                                               \
    return cn1DbProbeKey(db);                                                                       \
}                                                                                                   \
JAVA_INT PREFIX##_sqlDbApplyKeyStatus___long_java_lang_String_R_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG dbPeer, JAVA_OBJECT key) { \
    return PREFIX##_sqlDbApplyKeyStatus___long_java_lang_String(threadStateData, dbPeer, key);      \
}                                                                                                   \
                                                                                                   \
JAVA_VOID PREFIX##_sqlDbRekey___long_java_lang_String(CODENAME_ONE_THREAD_STATE, JAVA_LONG dbPeer, JAVA_OBJECT key) { \
    sqlite3* db = (sqlite3*)(intptr_t)dbPeer;                                                       \
    int rc;                                                                                         \
    if (cn1DbApplyCipherProfile(db) != SQLITE_OK) {                                                 \
        cn1DbThrow(threadStateData, "This build does not support encrypted databases");             \
        return;                                                                                     \
    }                                                                                               \
    if (key == JAVA_NULL) {                                                                         \
        rc = sqlite3_rekey(db, NULL, 0);                                                            \
    } else {                                                                                        \
        const char* k = stringToUTF8(threadStateData, key);                                         \
        rc = sqlite3_rekey(db, k, (int)strlen(k));                                                  \
    }                                                                                               \
    if (rc != SQLITE_OK) {                                                                          \
        cn1DbThrowSqlite(threadStateData, db, "Failed to change the database key");                 \
    }                                                                                               \
}                                                                                                   \
                                                                                                   \
JAVA_BOOLEAN PREFIX##_sqlDbIsCipherAvailable__(CODENAME_ONE_THREAD_STATE) {                         \
    return JAVA_TRUE;                                                                               \
}                                                                                                   \
JAVA_BOOLEAN PREFIX##_sqlDbIsCipherAvailable___R_boolean(CODENAME_ONE_THREAD_STATE) {               \
    return JAVA_TRUE;                                                                               \
}                                                                                                   \
                                                                                                   \
JAVA_VOID PREFIX##_sqlDbClose___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG dbPeer) {                 \
    if (dbPeer != 0) {                                                                              \
        sqlite3_close_v2((sqlite3*)(intptr_t)dbPeer);                                               \
    }                                                                                               \
}                                                                                                   \
                                                                                                   \
JAVA_VOID PREFIX##_sqlDbExecScript___long_java_lang_String(CODENAME_ONE_THREAD_STATE, JAVA_LONG dbPeer, JAVA_OBJECT sql) { \
    sqlite3* db = (sqlite3*)(intptr_t)dbPeer;                                                       \
    char* err = NULL;                                                                               \
    if (sqlite3_exec(db, stringToUTF8(threadStateData, sql), NULL, NULL, &err) != SQLITE_OK) {      \
        char buffer[512];                                                                           \
        snprintf(buffer, sizeof(buffer), "SQL error: %s", err != NULL ? err : "unknown");           \
        if (err != NULL) {                                                                          \
            sqlite3_free(err);                                                                      \
        }                                                                                           \
        cn1DbThrow(threadStateData, buffer);                                                        \
    }                                                                                               \
}                                                                                                   \
                                                                                                   \
JAVA_LONG PREFIX##_sqlStmtPrepare___long_java_lang_String(CODENAME_ONE_THREAD_STATE, JAVA_LONG dbPeer, JAVA_OBJECT sql) { \
    sqlite3* db = (sqlite3*)(intptr_t)dbPeer;                                                       \
    sqlite3_stmt* stmt = NULL;                                                                      \
    if (sqlite3_prepare_v2(db, stringToUTF8(threadStateData, sql), -1, &stmt, NULL) != SQLITE_OK) { \
        cn1DbThrowSqlite(threadStateData, db, "Failed to compile the statement");                   \
        return 0;                                                                                   \
    }                                                                                               \
    return (JAVA_LONG)(intptr_t)stmt;                                                               \
}                                                                                                   \
JAVA_LONG PREFIX##_sqlStmtPrepare___long_java_lang_String_R_long(CODENAME_ONE_THREAD_STATE, JAVA_LONG dbPeer, JAVA_OBJECT sql) { \
    return PREFIX##_sqlStmtPrepare___long_java_lang_String(threadStateData, dbPeer, sql);           \
}                                                                                                   \
                                                                                                   \
JAVA_INT PREFIX##_sqlStmtParameterCount___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer) {     \
    return sqlite3_bind_parameter_count((sqlite3_stmt*)(intptr_t)stmtPeer);                         \
}                                                                                                   \
JAVA_INT PREFIX##_sqlStmtParameterCount___long_R_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer) { \
    return sqlite3_bind_parameter_count((sqlite3_stmt*)(intptr_t)stmtPeer);                         \
}                                                                                                   \
                                                                                                   \
JAVA_VOID PREFIX##_sqlStmtBindNull___long_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer, JAVA_INT index) { \
    cn1DbCheckBind(threadStateData, (sqlite3_stmt*)(intptr_t)stmtPeer,                              \
            sqlite3_bind_null((sqlite3_stmt*)(intptr_t)stmtPeer, index), index);                    \
}                                                                                                   \
                                                                                                   \
JAVA_VOID PREFIX##_sqlStmtBindText___long_int_byte_1ARRAY(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer, JAVA_INT index, JAVA_OBJECT value) { \
    sqlite3_stmt* stmt = (sqlite3_stmt*)(intptr_t)stmtPeer;                                         \
    JAVA_ARRAY arr;                                                                                 \
    if (value == JAVA_NULL) {                                                                       \
        cn1DbCheckBind(threadStateData, stmt, sqlite3_bind_null(stmt, index), index);                \
        return;                                                                                     \
    }                                                                                               \
    /* The caller encodes, and the length is the array's rather than "up to the first zero byte": \
     * a Java string may hold a zero character and SQLite stores it, so measuring with strlen       \
     * would drop that character and everything after it. */                                        \
    arr = (JAVA_ARRAY)value;                                                                        \
    cn1DbCheckBind(threadStateData, stmt,                                                           \
            sqlite3_bind_text(stmt, index, (const char*)arr->data, arr->length,                     \
                    SQLITE_TRANSIENT), index);                                                      \
}                                                                                                   \
                                                                                                   \
JAVA_VOID PREFIX##_sqlStmtBindBlob___long_int_byte_1ARRAY(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer, JAVA_INT index, JAVA_OBJECT value) { \
    sqlite3_stmt* stmt = (sqlite3_stmt*)(intptr_t)stmtPeer;                                         \
    JAVA_ARRAY arr;                                                                                 \
    if (value == JAVA_NULL) {                                                                       \
        cn1DbCheckBind(threadStateData, stmt, sqlite3_bind_null(stmt, index), index);                \
        return;                                                                                     \
    }                                                                                               \
    arr = (JAVA_ARRAY)value;                                                                        \
    cn1DbCheckBind(threadStateData, stmt,                                                           \
            sqlite3_bind_blob(stmt, index, arr->data, arr->length, SQLITE_TRANSIENT), index);       \
}                                                                                                   \
                                                                                                   \
JAVA_VOID PREFIX##_sqlStmtBindLong___long_int_long(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer, JAVA_INT index, JAVA_LONG value) { \
    cn1DbCheckBind(threadStateData, (sqlite3_stmt*)(intptr_t)stmtPeer,                              \
            sqlite3_bind_int64((sqlite3_stmt*)(intptr_t)stmtPeer, index, value), index);            \
}                                                                                                   \
                                                                                                   \
JAVA_VOID PREFIX##_sqlStmtBindDouble___long_int_double(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer, JAVA_INT index, JAVA_DOUBLE value) { \
    cn1DbCheckBind(threadStateData, (sqlite3_stmt*)(intptr_t)stmtPeer,                              \
            sqlite3_bind_double((sqlite3_stmt*)(intptr_t)stmtPeer, index, value), index);           \
}                                                                                                   \
                                                                                                   \
JAVA_BOOLEAN PREFIX##_sqlStmtStep___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer) {           \
    sqlite3_stmt* stmt = (sqlite3_stmt*)(intptr_t)stmtPeer;                                         \
    int rc = sqlite3_step(stmt);                                                                    \
    if (rc == SQLITE_ROW) {                                                                         \
        return JAVA_TRUE;                                                                           \
    }                                                                                               \
    if (rc != SQLITE_DONE) {                                                                        \
        cn1DbThrowSqlite(threadStateData, sqlite3_db_handle(stmt), "Failed to step the statement"); \
    }                                                                                               \
    return JAVA_FALSE;                                                                              \
}                                                                                                   \
JAVA_BOOLEAN PREFIX##_sqlStmtStep___long_R_boolean(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer) { \
    return PREFIX##_sqlStmtStep___long(threadStateData, stmtPeer);                                  \
}                                                                                                   \
                                                                                                   \
JAVA_VOID PREFIX##_sqlStmtReset___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer) {             \
    sqlite3_reset((sqlite3_stmt*)(intptr_t)stmtPeer);                                               \
}                                                                                                   \
                                                                                                   \
JAVA_VOID PREFIX##_sqlStmtFinalize___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer) {          \
    if (stmtPeer != 0) {                                                                            \
        sqlite3_finalize((sqlite3_stmt*)(intptr_t)stmtPeer);                                        \
    }                                                                                               \
}                                                                                                   \
                                                                                                   \
JAVA_VOID PREFIX##_sqlStmtExecuteAndFinalize___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer) { \
    sqlite3_stmt* stmt = (sqlite3_stmt*)(intptr_t)stmtPeer;                                         \
    sqlite3* db = sqlite3_db_handle(stmt);                                                          \
    int rc;                                                                                         \
    while ((rc = sqlite3_step(stmt)) == SQLITE_ROW) {                                               \
    }                                                                                               \
    sqlite3_finalize(stmt);                                                                         \
    if (rc != SQLITE_DONE) {                                                                        \
        cn1DbThrowSqlite(threadStateData, db, "Failed to execute the statement");                   \
    }                                                                                               \
}                                                                                                   \
                                                                                                   \
JAVA_INT PREFIX##_sqlColCount___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer) {               \
    return sqlite3_column_count((sqlite3_stmt*)(intptr_t)stmtPeer);                                 \
}                                                                                                   \
JAVA_INT PREFIX##_sqlColCount___long_R_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer) {         \
    return sqlite3_column_count((sqlite3_stmt*)(intptr_t)stmtPeer);                                 \
}                                                                                                   \
                                                                                                   \
JAVA_OBJECT PREFIX##_sqlColName___long_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer, JAVA_INT col) { \
    /* UTF-8 bytes, decoded by the caller, for the reason given on sqlColText: an identifier is as  \
     * free to be non-ASCII as a value is. */                                                       \
    const char* name = sqlite3_column_name((sqlite3_stmt*)(intptr_t)stmtPeer, col);                 \
    if (name == NULL) {                                                                             \
        return JAVA_NULL;                                                                           \
    }                                                                                               \
    return cn1DbBlobToByteArray(threadStateData, name, (int)strlen(name));                          \
}                                                                                                   \
JAVA_OBJECT PREFIX##_sqlColName___long_int_R_byte_1ARRAY(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer, JAVA_INT col) { \
    return PREFIX##_sqlColName___long_int(threadStateData, stmtPeer, col);                          \
}                                                                                                   \
                                                                                                   \
JAVA_BOOLEAN PREFIX##_sqlColIsNull___long_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer, JAVA_INT col) { \
    return sqlite3_column_type((sqlite3_stmt*)(intptr_t)stmtPeer, col) == SQLITE_NULL               \
            ? JAVA_TRUE : JAVA_FALSE;                                                               \
}                                                                                                   \
JAVA_BOOLEAN PREFIX##_sqlColIsNull___long_int_R_boolean(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer, JAVA_INT col) { \
    return PREFIX##_sqlColIsNull___long_int(threadStateData, stmtPeer, col);                        \
}                                                                                                   \
                                                                                                   \
JAVA_OBJECT PREFIX##_sqlColText___long_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer, JAVA_INT col) { \
    sqlite3_stmt* stmt = (sqlite3_stmt*)(intptr_t)stmtPeer;                                         \
    const void* text;                                                                               \
    int length;                                                                                     \
    if (sqlite3_column_type(stmt, col) == SQLITE_NULL) {                                            \
        return JAVA_NULL;                                                                           \
    }                                                                                               \
    /* Handed back as the engine's own UTF-8 bytes, for the caller to decode. The conversions the   \
     * VM offers here widen one byte to one character, which is not UTF-8, and a C string would     \
     * also end at an embedded zero byte. sqlite3_column_bytes must follow the _text call: it       \
     * reports the length of the value as that call converted it. */                                \
    text = sqlite3_column_text(stmt, col);                                                          \
    length = sqlite3_column_bytes(stmt, col);                                                       \
    return cn1DbBlobToByteArray(threadStateData, text, length);                                     \
}                                                                                                   \
JAVA_OBJECT PREFIX##_sqlColText___long_int_R_byte_1ARRAY(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer, JAVA_INT col) { \
    return PREFIX##_sqlColText___long_int(threadStateData, stmtPeer, col);                          \
}                                                                                                   \
                                                                                                   \
JAVA_OBJECT PREFIX##_sqlColBlob___long_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer, JAVA_INT col) { \
    sqlite3_stmt* stmt = (sqlite3_stmt*)(intptr_t)stmtPeer;                                         \
    const void* bytes = sqlite3_column_blob(stmt, col);                                             \
    int length = sqlite3_column_bytes(stmt, col);                                                   \
    return cn1DbBlobToByteArray(threadStateData, bytes, length);                                    \
}                                                                                                   \
JAVA_OBJECT PREFIX##_sqlColBlob___long_int_R_byte_1ARRAY(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer, JAVA_INT col) { \
    return PREFIX##_sqlColBlob___long_int(threadStateData, stmtPeer, col);                          \
}                                                                                                   \
                                                                                                   \
JAVA_DOUBLE PREFIX##_sqlColDouble___long_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer, JAVA_INT col) { \
    return sqlite3_column_double((sqlite3_stmt*)(intptr_t)stmtPeer, col);                           \
}                                                                                                   \
JAVA_DOUBLE PREFIX##_sqlColDouble___long_int_R_double(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer, JAVA_INT col) { \
    return sqlite3_column_double((sqlite3_stmt*)(intptr_t)stmtPeer, col);                           \
}                                                                                                   \
                                                                                                   \
JAVA_LONG PREFIX##_sqlColLong___long_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer, JAVA_INT col) { \
    return sqlite3_column_int64((sqlite3_stmt*)(intptr_t)stmtPeer, col);                            \
}                                                                                                   \
JAVA_LONG PREFIX##_sqlColLong___long_int_R_long(CODENAME_ONE_THREAD_STATE, JAVA_LONG stmtPeer, JAVA_INT col) { \
    return sqlite3_column_int64((sqlite3_stmt*)(intptr_t)stmtPeer, col);                            \
}

#else /* !CN1_DB_ENGINE_PRESENT */

#include <stddef.h>

/** Raises java.io.IOException saying this build has no database. */
static void cn1DbThrowUnavailable(CODENAME_ONE_THREAD_STATE) {
    JAVA_OBJECT ex = __NEW_java_io_IOException(threadStateData);
    java_io_IOException___INIT_____java_lang_String(threadStateData, ex,
            newStringFromCString(threadStateData,
                    "This build does not include the SQLite engine"));
    throwException(threadStateData, ex);
}

/*
 * Stub entry points, so an application that references com.codename1.db always links even when the
 * engine was not emitted. openOrCreateDB fails with a clear IOException rather than an unresolved
 * symbol, and the conformance suite self-skips on the resulting failure.
 */
#define CN1_DB_DEFINE_NATIVES(PREFIX)                                                              \
JAVA_BOOLEAN PREFIX##_sqlDbExists___java_lang_String(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT p) { return JAVA_FALSE; } \
JAVA_BOOLEAN PREFIX##_sqlDbExists___java_lang_String_R_boolean(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT p) { return JAVA_FALSE; } \
JAVA_VOID PREFIX##_sqlDbDelete___java_lang_String(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT p) { }     \
JAVA_LONG PREFIX##_sqlDbOpen___java_lang_String(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT p) { cn1DbThrowUnavailable(threadStateData); return 0; } \
JAVA_LONG PREFIX##_sqlDbOpen___java_lang_String_R_long(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT p) { cn1DbThrowUnavailable(threadStateData); return 0; } \
JAVA_BOOLEAN PREFIX##_sqlDbApplyKey___long_java_lang_String(CODENAME_ONE_THREAD_STATE, JAVA_LONG d, JAVA_OBJECT k) { return JAVA_FALSE; } \
JAVA_BOOLEAN PREFIX##_sqlDbApplyKey___long_java_lang_String_R_boolean(CODENAME_ONE_THREAD_STATE, JAVA_LONG d, JAVA_OBJECT k) { return JAVA_FALSE; } \
JAVA_INT PREFIX##_sqlDbApplyKeyStatus___long_java_lang_String(CODENAME_ONE_THREAD_STATE, JAVA_LONG d, JAVA_OBJECT k) { return 1; } \
JAVA_INT PREFIX##_sqlDbApplyKeyStatus___long_java_lang_String_R_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG d, JAVA_OBJECT k) { return 1; } \
JAVA_VOID PREFIX##_sqlDbRekey___long_java_lang_String(CODENAME_ONE_THREAD_STATE, JAVA_LONG d, JAVA_OBJECT k) { cn1DbThrowUnavailable(threadStateData); } \
JAVA_BOOLEAN PREFIX##_sqlDbIsCipherAvailable__(CODENAME_ONE_THREAD_STATE) { return JAVA_FALSE; }    \
JAVA_BOOLEAN PREFIX##_sqlDbIsCipherAvailable___R_boolean(CODENAME_ONE_THREAD_STATE) { return JAVA_FALSE; } \
JAVA_VOID PREFIX##_sqlDbClose___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG d) { }                    \
JAVA_VOID PREFIX##_sqlDbExecScript___long_java_lang_String(CODENAME_ONE_THREAD_STATE, JAVA_LONG d, JAVA_OBJECT s) { cn1DbThrowUnavailable(threadStateData); } \
JAVA_LONG PREFIX##_sqlStmtPrepare___long_java_lang_String(CODENAME_ONE_THREAD_STATE, JAVA_LONG d, JAVA_OBJECT s) { cn1DbThrowUnavailable(threadStateData); return 0; } \
JAVA_LONG PREFIX##_sqlStmtPrepare___long_java_lang_String_R_long(CODENAME_ONE_THREAD_STATE, JAVA_LONG d, JAVA_OBJECT s) { cn1DbThrowUnavailable(threadStateData); return 0; } \
JAVA_INT PREFIX##_sqlStmtParameterCount___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG s) { return 0; } \
JAVA_INT PREFIX##_sqlStmtParameterCount___long_R_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG s) { return 0; } \
JAVA_VOID PREFIX##_sqlStmtBindNull___long_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG s, JAVA_INT i) { } \
JAVA_VOID PREFIX##_sqlStmtBindText___long_int_byte_1ARRAY(CODENAME_ONE_THREAD_STATE, JAVA_LONG s, JAVA_INT i, JAVA_OBJECT v) { } \
JAVA_VOID PREFIX##_sqlStmtBindBlob___long_int_byte_1ARRAY(CODENAME_ONE_THREAD_STATE, JAVA_LONG s, JAVA_INT i, JAVA_OBJECT v) { } \
JAVA_VOID PREFIX##_sqlStmtBindLong___long_int_long(CODENAME_ONE_THREAD_STATE, JAVA_LONG s, JAVA_INT i, JAVA_LONG v) { } \
JAVA_VOID PREFIX##_sqlStmtBindDouble___long_int_double(CODENAME_ONE_THREAD_STATE, JAVA_LONG s, JAVA_INT i, JAVA_DOUBLE v) { } \
JAVA_BOOLEAN PREFIX##_sqlStmtStep___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG s) { return JAVA_FALSE; } \
JAVA_BOOLEAN PREFIX##_sqlStmtStep___long_R_boolean(CODENAME_ONE_THREAD_STATE, JAVA_LONG s) { return JAVA_FALSE; } \
JAVA_VOID PREFIX##_sqlStmtReset___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG s) { }                  \
JAVA_VOID PREFIX##_sqlStmtFinalize___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG s) { }               \
JAVA_VOID PREFIX##_sqlStmtExecuteAndFinalize___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG s) { cn1DbThrowUnavailable(threadStateData); } \
JAVA_INT PREFIX##_sqlColCount___long(CODENAME_ONE_THREAD_STATE, JAVA_LONG s) { return 0; }          \
JAVA_INT PREFIX##_sqlColCount___long_R_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG s) { return 0; }    \
JAVA_OBJECT PREFIX##_sqlColName___long_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG s, JAVA_INT c) { return JAVA_NULL; } \
JAVA_OBJECT PREFIX##_sqlColName___long_int_R_byte_1ARRAY(CODENAME_ONE_THREAD_STATE, JAVA_LONG s, JAVA_INT c) { return JAVA_NULL; } \
JAVA_BOOLEAN PREFIX##_sqlColIsNull___long_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG s, JAVA_INT c) { return JAVA_TRUE; } \
JAVA_BOOLEAN PREFIX##_sqlColIsNull___long_int_R_boolean(CODENAME_ONE_THREAD_STATE, JAVA_LONG s, JAVA_INT c) { return JAVA_TRUE; } \
JAVA_OBJECT PREFIX##_sqlColText___long_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG s, JAVA_INT c) { return JAVA_NULL; } \
JAVA_OBJECT PREFIX##_sqlColText___long_int_R_byte_1ARRAY(CODENAME_ONE_THREAD_STATE, JAVA_LONG s, JAVA_INT c) { return JAVA_NULL; } \
JAVA_OBJECT PREFIX##_sqlColBlob___long_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG s, JAVA_INT c) { return JAVA_NULL; } \
JAVA_OBJECT PREFIX##_sqlColBlob___long_int_R_byte_1ARRAY(CODENAME_ONE_THREAD_STATE, JAVA_LONG s, JAVA_INT c) { return JAVA_NULL; } \
JAVA_DOUBLE PREFIX##_sqlColDouble___long_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG s, JAVA_INT c) { return 0; } \
JAVA_DOUBLE PREFIX##_sqlColDouble___long_int_R_double(CODENAME_ONE_THREAD_STATE, JAVA_LONG s, JAVA_INT c) { return 0; } \
JAVA_LONG PREFIX##_sqlColLong___long_int(CODENAME_ONE_THREAD_STATE, JAVA_LONG s, JAVA_INT c) { return 0; } \
JAVA_LONG PREFIX##_sqlColLong___long_int_R_long(CODENAME_ONE_THREAD_STATE, JAVA_LONG s, JAVA_INT c) { return 0; }

#endif /* CN1_DB_ENGINE_PRESENT */

#endif /* CN1_DB_SQLITE_IMPL_H */
