/*
 * Copyright (c) 2026, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Codename One through http://www.codenameone.com/ if you
 * need additional information or have any questions.
 */
package com.codename1.router;

import com.codename1.ui.Form;

/// Internal contract between the build-time-generated route table and the
/// framework. Application code should not implement or call this directly --
/// declare deep-linkable forms with `com.codename1.annotations.Route` and use
/// `Navigation#navigate(String)` for in-app routing.
///
/// A single implementation, generated by the Codename One Maven plugin from
/// `@Route` annotations in the project, is installed on `Display` during
/// startup. Implementations resolve a URL to a `Form` factory and return
/// the resulting form -- they do not show the form; the caller
/// (`Navigation`) is responsible for stack bookkeeping and the
/// `Form#show` / `Form#showBack` call.
public interface RouteDispatcher {
    /// Resolve a URL to a Form. Returns the freshly built form when a route
    /// matched, or null otherwise.
    Form dispatch(String url);
}
