#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
package ${package};
/*
[archetype]
----
extends=../helloworld-archetype
groupId=com.codenameone.archetypes
artifactId=helloworld3-archetype
version=7.0-SNAPSHOT
parentGroupId=com.codenameone.archetypes
parentArtifactId=generated-archetypes
version=7.0-SNAPSHOT
----

[dependencies]
----
<dependency>
    <groupId>com.codenameone.libs</groupId>
    <artifactId>filechooser-lib</artifactId>
    <version>1.0-SNAPSHOT</version>
    <type>pom</type>
</dependency>
----
 */
import static com.codename1.ui.CN.*;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class ${mainName} {

private Form current;
private Resources theme;

public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
        // prevent the event from propagating
        err.consume();
        if(err.getError() != null) {
        Log.e(err.getError());
        }
        Log.sendLogAsync();
        Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });
        }


public void start() {
        if(current != null){
        current.show();
        return;
        }
        //WebSocket sock;
        Form hi = new Form("Hi World", BoxLayout.y());
        hi.add(new Label("Hello World"));

        hi.show();
        }

public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
        ((Dialog)current).dispose();
        current = getCurrentForm();
        }
        }

public void destroy() {
        }

        }
