package com.codename1.svg.transcoder;

import com.codename1.svg.transcoder.codegen.JavaCodeGenerator;
import com.codename1.svg.transcoder.model.SVGDocument;
import com.codename1.svg.transcoder.parser.SVGParser;

import java.io.*;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Top-level entry point: parse an SVG file and emit a Codename One
 * {@code GeneratedSVGImage} subclass. Also generates a small registry class
 * that wires the emitted images into a {@code Resources} instance at runtime
 * via {@code Resources.registerGeneratedImage(String, Image)}.
 */
public final class SVGTranscoder {

    /** Per-image entry -- used both by the per-file transcode and the registry emitter. */
    public static final class GeneratedClass {
        public final String packageName;
        public final String className;
        /** Logical resource name used at runtime (e.g. "home" for "home.svg"). */
        public final String resourceName;

        public GeneratedClass(String packageName, String className, String resourceName) {
            this.packageName = packageName;
            this.className = className;
            this.resourceName = resourceName;
        }

        public String fullyQualified() {
            return packageName == null || packageName.isEmpty() ? className : packageName + "." + className;
        }
    }

    private SVGTranscoder() { }

    /** Parse {@code svg} and write a Java source file to {@code out}. */
    public static void transcode(InputStream svg, String packageName, String className, Writer out) throws IOException {
        SVGDocument doc = new SVGParser().parse(svg);
        new JavaCodeGenerator(doc, packageName, className).generate(out);
    }

    public static void transcode(File svgFile, String packageName, String className, File outFile) throws IOException {
        if (outFile.getParentFile() != null) {
            outFile.getParentFile().mkdirs();
        }
        InputStream in = new BufferedInputStream(new FileInputStream(svgFile));
        try {
            Writer w = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(outFile), "UTF-8"));
            try {
                transcode(in, packageName, className, w);
            } finally {
                w.close();
            }
        } finally {
            in.close();
        }
    }

    /**
     * Emit a {@code SVGRegistry} class with a single public static method
     * {@code install(Resources)}, which instantiates each generated SVG image
     * and registers it under its source filename. The runtime
     * {@code Resources} class also looks up this same registry class via
     * reflection so generated SVGs appear under {@code getImage(name)} for
     * any resources bundle that has been opened in this VM.
     */
    public static void writeRegistry(String packageName, String className, java.util.List<GeneratedClass> classes, Writer out) throws IOException {
        // dedupe by resource name; last wins
        Map<String, GeneratedClass> unique = new LinkedHashMap<String, GeneratedClass>();
        for (GeneratedClass c : classes) {
            unique.put(c.resourceName, c);
        }

        if (packageName != null && !packageName.isEmpty()) {
            out.write("package " + packageName + ";\n\n");
        }
        out.write("import com.codename1.ui.Image;\n");
        out.write("import com.codename1.ui.util.Resources;\n\n");
        out.write("/** Generated by codenameone-svg-transcoder. DO NOT EDIT.\n");
        out.write(" *  Registers transcoded SVG images so they are returned by\n");
        out.write(" *  {@link Resources#getImage(String)}.\n");
        out.write(" */\n");
        out.write("public final class " + className + " {\n\n");
        out.write("    private static volatile boolean __installed;\n\n");
        out.write("    private " + className + "() { }\n\n");
        out.write("    /** Idempotent. Registers each generated SVG image both globally\n");
        out.write("     *  (so any Resources opened in this VM can resolve them) and on\n");
        out.write("     *  the provided instance for direct lookup. */\n");
        out.write("    public static void install(Resources r) {\n");
        out.write("        installGlobal();\n");
        out.write("        if (r != null) {\n");
        for (GeneratedClass c : unique.values()) {
            out.write("            r.setImage(\"" + escapeJavaString(c.resourceName) + "\", new " + c.fullyQualified() + "());\n");
        }
        out.write("        }\n");
        out.write("    }\n\n");
        out.write("    /** Called via reflection by Resources lazily -- see Resources#getImage. */\n");
        out.write("    public static void installGlobal() {\n");
        out.write("        if (__installed) return;\n");
        out.write("        synchronized (" + className + ".class) {\n");
        out.write("            if (__installed) return;\n");
        for (GeneratedClass c : unique.values()) {
            out.write("            Resources.registerGeneratedImage(\"" + escapeJavaString(c.resourceName) + "\", new " + c.fullyQualified() + "());\n");
        }
        out.write("            __installed = true;\n");
        out.write("        }\n");
        out.write("    }\n");
        out.write("}\n");
    }

    /** "home.svg" -> "HomeSvg". Used to derive a class name from a filename. */
    public static String classNameFor(String fileName) {
        String stem = fileName;
        int dot = stem.lastIndexOf('.');
        if (dot > 0) {
            stem = stem.substring(0, dot);
        }
        StringBuilder sb = new StringBuilder();
        boolean upper = true;
        for (int i = 0; i < stem.length(); i++) {
            char c = stem.charAt(i);
            if (c == '_' || c == '-' || c == ' ' || c == '.') { upper = true; continue; }
            if (sb.length() == 0 && Character.isDigit(c)) {
                sb.append('_').append(c);
                upper = true;
                continue;
            }
            if (!Character.isJavaIdentifierPart(c)) c = '_';
            sb.append(upper ? Character.toUpperCase(c) : c);
            upper = false;
        }
        if (sb.length() == 0) {
            sb.append("Svg");
        }
        return sb.toString();
    }

    private static String escapeJavaString(String s) {
        StringBuilder sb = new StringBuilder(s.length() + 4);
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            switch (c) {
                case '\\': sb.append("\\\\"); break;
                case '"':  sb.append("\\\""); break;
                case '\n': sb.append("\\n"); break;
                case '\r': sb.append("\\r"); break;
                case '\t': sb.append("\\t"); break;
                default:   sb.append(c);
            }
        }
        return sb.toString();
    }
}
