/*
 * Copyright (c) 2026, Codename One and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Codename One designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Codename One through http://www.codenameone.com/ if you
 * need additional information or have any questions.
 */

// Native implementation of IOSNative.isAppClipHandoffSupported(String) and
// .consumeAppClipInviteHandoff(String), which back
// com.codename1.impl.ios.IOSAppClipHandoff.
//
// The App Clip half of the same exchange is generated by IPhoneBuilder into
// the clip's own target (InviteAppClipBuilder); the two agree on the app group, the
// defaults key and the two field names, and on nothing else. Keep them in
// step: the clip is a separate binary that ships inside the application, so a
// mismatch here is not a compile error anywhere -- the code is simply never
// found and every iOS install reads as organic.

#include "xmlvm.h"
#ifndef NEW_CODENAME_ONE_VM
#include "xmlvm-util.h"
#endif
#import "CodenameOne_GLViewController.h"

#ifdef CN1_INCLUDE_INVITE_APPCLIP

#import <Foundation/Foundation.h>

#ifdef NEW_CODENAME_ONE_VM
extern JAVA_OBJECT fromNSString(CODENAME_ONE_THREAD_STATE, NSString* str);
extern NSString*   toNSString(CODENAME_ONE_THREAD_STATE, JAVA_OBJECT str);
#else
extern JAVA_OBJECT fromNSString(NSString* str);
extern NSString*   toNSString(JAVA_OBJECT str);
#endif

// The one key the clip writes and the application consumes. A dictionary
// rather than a bare string so the click time rides along: the clip is the
// only process that ever knew it, and it is gone by the time the application
// exists.
static NSString * const kCN1InviteHandoffKey = @"cn1-invite-app-clip-handoff";
static NSString * const kCN1InviteCodeField = @"code";
static NSString * const kCN1InviteClickedField = @"clicked";

// Opened fresh on each call and autoreleased rather than cached in a static.
// The port is built without ARC, and a cached suite would outlive an entitlement
// change across a background relaunch; this is called twice per install at most.
static NSUserDefaults *cn1InviteSuite(NSString *group) {
    if (group == nil || group.length == 0) {
        return nil;
    }
    NSUserDefaults *suite = [[[NSUserDefaults alloc] initWithSuiteName:group] autorelease];
    return suite;
}

JAVA_BOOLEAN com_codename1_impl_ios_IOSNative_isAppClipHandoffSupported___java_lang_String_R_boolean(
        CN1_THREAD_STATE_MULTI_ARG JAVA_OBJECT me, JAVA_OBJECT groupObj) {
    // initWithSuiteName: answers nil when the process carries no such app
    // group, which is exactly the question being asked -- an application built
    // without a clip has no group and must report unsupported rather than
    // spend an attempt discovering there is nothing to read.
    return cn1InviteSuite(toNSString(CN1_THREAD_STATE_PASS_ARG groupObj)) != nil
            ? JAVA_TRUE : JAVA_FALSE;
}

JAVA_OBJECT com_codename1_impl_ios_IOSNative_consumeAppClipInviteHandoff___java_lang_String_R_java_lang_String(
        CN1_THREAD_STATE_MULTI_ARG JAVA_OBJECT me, JAVA_OBJECT groupObj) {
    NSUserDefaults *suite = cn1InviteSuite(toNSString(CN1_THREAD_STATE_PASS_ARG groupObj));
    if (suite == nil) {
        return JAVA_NULL;
    }
    // objectForKey:, not dictionaryForKey:, because the shared container is
    // writable by the clip and a wrong type there must read as "nothing was
    // left" rather than raise: dictionaryForKey: answers nil for a non-
    // dictionary, but the field reads below would then go to the wrong class.
    id stored = [suite objectForKey:kCN1InviteHandoffKey];
    if (![stored isKindOfClass:[NSDictionary class]]) {
        if (stored != nil) {
            [suite removeObjectForKey:kCN1InviteHandoffKey];
        }
        return JAVA_NULL;
    }
    NSDictionary *handoff = (NSDictionary *)stored;
    id codeValue = [handoff objectForKey:kCN1InviteCodeField];
    NSString *code = [codeValue isKindOfClass:[NSString class]] ? (NSString *)codeValue : nil;
    id clickedValue = [handoff objectForKey:kCN1InviteClickedField];
    long long clicked = [clickedValue isKindOfClass:[NSNumber class]]
            ? [(NSNumber *)clickedValue longLongValue] : 0;

    // Cleared whatever was found, including a malformed record. Read once is
    // the contract AppClipHandoffSource states, and it is what stops a second
    // launch claiming a code the first already claimed.
    [suite removeObjectForKey:kCN1InviteHandoffKey];

    if (code == nil || code.length == 0) {
        return JAVA_NULL;
    }
    // A newline separates the two, so a code carrying one would be read as a
    // code plus garbage. Codes are Crockford base32 and cannot, but the clip
    // writes what the link gave it and the link is somebody else's input.
    if ([code rangeOfString:@"\n"].location != NSNotFound) {
        return JAVA_NULL;
    }
    NSString *joined = [NSString stringWithFormat:@"%@\n%lld", code, clicked];
    return fromNSString(CN1_THREAD_STATE_PASS_ARG joined);
}

#endif
