#Updated keystore
#Mon Jun 22 11:54:44 IDT 2026
codename1.android.keystore=/Users/shai/dev/cn4/CodenameOne/scripts/fidelity-app/android/../common/androidCerts/KeyChain.ks
codename1.android.keystoreAlias=androidKey
codename1.android.keystorePassword=password
codename1.arg.android.gradleDep=implementation 'com.google.android.material\:material\:1.12.0'
codename1.arg.android.useAndroidX=true
codename1.arg.ios.metal=true
codename1.arg.ios.newStorageLocation=true
codename1.arg.ios.uiscene=true
codename1.arg.java.version=17
codename1.cssTheme=true
codename1.displayName=Fidelity
codename1.icon=icon.png
codename1.ios.appid=Q5GHSKAL2F.com.codenameone.fidelity
codename1.ios.certificate=
codename1.ios.certificatePassword=
codename1.ios.debug.certificate=
codename1.ios.debug.certificatePassword=
codename1.ios.debug.provision=
codename1.ios.provision=
codename1.ios.release.certificate=
codename1.ios.release.certificatePassword=
codename1.kotlin=false
codename1.languageLevel=5
codename1.mainName=FidelityApp
codename1.packageName=com.codenameone.fidelity
codename1.rim.certificatePassword=
codename1.rim.signtoolCsk=
codename1.rim.signtoolDb=
codename1.secondaryTitle=Fidelity
codename1.vendor=CodenameOne
codename1.version=1.0
