/*
 * Copyright (c) 2008, 2010, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 */
package com.codename1.maven.processors;

import com.codename1.maven.annotations.AbstractAnnotationProcessor;
import com.codename1.maven.annotations.AnnotatedClass;
import com.codename1.maven.annotations.AnnotationValues;
import com.codename1.maven.annotations.MethodInfo;
import com.codename1.maven.annotations.ProcessingException;
import com.codename1.maven.annotations.ProcessorContext;

import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;

/// Build-time `@com.codename1.annotations.Route` processor.
///
/// Scans the project's compiled `.class` files for `@Route`-annotated classes,
/// validates them (extends `Form`; pattern is non-empty and starts with `/`;
/// has an accessible constructor; no duplicate patterns), then emits a
/// `com.codename1.router.generated.RoutesIndex` class via ASM that:
///
/// 1. Calls `Router.getInstance().route(pattern, builder)` for every accepted
///    route, prefering a `(RouteContext)` constructor over a no-arg one.
/// 2. Uses a single inner `RoutesIndex$Builder` class with a tableswitch over
///    a route index — keeps the per-route class explosion bounded at 2
///    regardless of route count.
///
/// **Fail-fast.** Errors are reported via `ProcessorContext#error` and abort
/// the build (the orchestrator never writes generated classes when errors are
/// pending), so an invalid `@Route` declaration cannot ship.
public final class RouteAnnotationProcessor extends AbstractAnnotationProcessor {

    public static final String ROUTE_DESC = "Lcom/codename1/annotations/Route;";
    public static final String ROUTES_DESC = "Lcom/codename1/annotations/Route$Routes;";

    static final String FORM_INTERNAL = "com/codename1/ui/Form";
    static final String CONTEXT_INTERNAL = "com/codename1/router/RouteContext";
    static final String BUILDER_INTERNAL = "com/codename1/router/RouteBuilder";
    static final String ROUTER_INTERNAL = "com/codename1/router/Router";
    static final String INDEX_INTERNAL = "com/codename1/router/generated/RoutesIndex";
    static final String DISPATCH_INTERNAL = INDEX_INTERNAL + "$Builder";

    private static final String NO_ARG_CTOR_DESC = "()V";
    private static final String CTX_CTOR_DESC = "(L" + CONTEXT_INTERNAL + ";)V";

    /// Single source of truth for the set of descriptors this processor handles.
    private static final Set<String> DESCRIPTORS;
    static {
        Set<String> s = new java.util.LinkedHashSet<String>();
        s.add(ROUTE_DESC);
        s.add(ROUTES_DESC);
        DESCRIPTORS = Collections.unmodifiableSet(s);
    }

    // ------------------------------------------------------------------------
    // State (reset on each #start)
    // ------------------------------------------------------------------------

    /// Routes accepted by the processor, keyed by pattern. TreeMap so the
    /// generated bytecode is deterministic regardless of class-scan order
    /// (helps reproducibility of binary output / cache invalidation).
    private final TreeMap<String, Entry> accepted = new TreeMap<String, Entry>();

    // ------------------------------------------------------------------------
    // SPI
    // ------------------------------------------------------------------------

    @Override
    public Set<String> getAnnotationDescriptors() {
        return DESCRIPTORS;
    }

    @Override
    public void emitStubs(ProcessorContext ctx) throws ProcessingException {
        // Compile-time stub. Apps reference RoutesIndex.register() in their
        // init() method; this source makes that resolvable before
        // process-annotations runs (and the resulting .class will be
        // overwritten with the real bytecode after compile).
        String stub =
                "// Auto-generated stub — overwritten by cn1:process-annotations.\n" +
                "package com.codename1.router.generated;\n" +
                "\n" +
                "/**\n" +
                " * Stub generated by the Codename One Maven plugin. The\n" +
                " * {@code cn1:process-annotations} goal overwrites this class with\n" +
                " * the actual route registrations after compile. If you see this\n" +
                " * file unchanged in target/classes after a build, the\n" +
                " * process-annotations goal did not run.\n" +
                " */\n" +
                "public final class RoutesIndex {\n" +
                "    private RoutesIndex() { }\n" +
                "    public static void register() { }\n" +
                "}\n";
        ctx.emitStubSource(INDEX_INTERNAL, stub);
    }

    @Override
    public void start(ProcessorContext ctx) throws ProcessingException {
        accepted.clear();
    }

    @Override
    public void processClass(AnnotatedClass cls, ProcessorContext ctx) throws ProcessingException {
        if (cls.isInterface() || cls.isAbstract() || cls.isSynthetic()) {
            // Annotations on these aren't actionable; report only if a Route
            // annotation is actually present (otherwise the dispatch wouldn't
            // have brought us here at all).
            if (cls.getClassAnnotation(ROUTE_DESC) != null
                    || cls.getClassAnnotation(ROUTES_DESC) != null) {
                ctx.error(cls, "@Route is not allowed on abstract / interface / synthetic classes; "
                        + "only concrete Form subclasses can be route targets");
            }
            return;
        }

        List<AnnotationValues> annotations = collectRouteAnnotations(cls);
        if (annotations.isEmpty()) return;

        // Validate base: must extend Form.
        if (!extendsForm(cls, ctx)) {
            ctx.error(cls, "@Route classes must extend com.codename1.ui.Form (transitively); "
                    + cls.getBinaryName() + " extends " + dot(cls.getSuperInternalName()));
            return;
        }

        // Determine constructor kind. We accept either a public (RouteContext)
        // ctor or a public no-arg one; the (RouteContext) form wins when both
        // exist because it gives access to path params.
        ConstructorKind kind = pickConstructor(cls);
        if (kind == ConstructorKind.NONE) {
            ctx.error(cls, "@Route class needs either a public no-arg constructor or "
                    + "a public constructor taking com.codename1.router.RouteContext");
            return;
        }

        for (int i = 0; i < annotations.size(); i++) {
            AnnotationValues av = annotations.get(i);
            String pattern = av.getString("value");
            // `@Route#name()` is captured by the scanner but not consumed yet —
            // it's reserved for a future reverse-routing API. Leaving the
            // attribute in the annotation but unread here keeps existing user
            // code valid while a downstream feature picks it up.
            if (pattern == null || pattern.length() == 0) {
                ctx.error(cls, "@Route value is required and must be a non-empty path");
                continue;
            }
            if (pattern.charAt(0) != '/') {
                ctx.error(cls, "@Route value must start with '/'; got: \"" + pattern + "\"");
                continue;
            }

            Entry prev = accepted.get(pattern);
            if (prev != null && !prev.targetInternal.equals(cls.getInternalName())) {
                ctx.error(cls, "duplicate @Route pattern \"" + pattern
                        + "\": already declared on " + dot(prev.targetInternal));
                continue;
            }

            accepted.put(pattern, new Entry(pattern, cls.getInternalName(), kind));
        }
    }

    @Override
    public void finish(ProcessorContext ctx) throws ProcessingException {
        // Never write output when validation has already failed — the
        // orchestrator would refuse to flush, but generating the bytecode
        // for invalid input is wasted work too.
        if (ctx.hasErrors()) return;

        List<Entry> ordered = new ArrayList<Entry>(accepted.values());
        ctx.emitClass(INDEX_INTERNAL, generateIndex(ordered));
        ctx.emitClass(DISPATCH_INTERNAL, generateDispatcher(ordered));
        ctx.getLog().info("cn1: routed " + ordered.size() + " @Route classes into "
                + dot(INDEX_INTERNAL));
    }

    // ------------------------------------------------------------------------
    // Validation helpers
    // ------------------------------------------------------------------------

    private static List<AnnotationValues> collectRouteAnnotations(AnnotatedClass cls) {
        List<AnnotationValues> out = new ArrayList<AnnotationValues>();
        AnnotationValues single = cls.getClassAnnotation(ROUTE_DESC);
        if (single != null) out.add(single);
        AnnotationValues container = cls.getClassAnnotation(ROUTES_DESC);
        if (container != null) {
            Object value = container.get("value");
            if (value instanceof List<?>) {
                List<?> items = (List<?>) value;
                for (int i = 0; i < items.size(); i++) {
                    Object it = items.get(i);
                    if (it instanceof AnnotationValues) out.add((AnnotationValues) it);
                }
            }
        }
        return out;
    }

    private static boolean extendsForm(AnnotatedClass cls, ProcessorContext ctx) {
        if (cls == null) return false;
        if (FORM_INTERNAL.equals(cls.getInternalName())) return true;
        String parent = cls.getSuperInternalName();
        while (parent != null) {
            if (FORM_INTERNAL.equals(parent)) return true;
            AnnotatedClass parentCls = ctx.lookup(parent);
            if (parentCls == null) {
                // Left the project — heuristically also accept any class whose
                // super-name lives in the codename1.ui package since the
                // project's compiled classpath doesn't include the cn1 core
                // JAR. Form itself lives in com/codename1/ui/Form, so:
                return parent.startsWith("com/codename1/ui/") && parent.endsWith("Form")
                        || parent.equals("com/codename1/ui/Dialog");
            }
            parent = parentCls.getSuperInternalName();
        }
        return false;
    }

    private static ConstructorKind pickConstructor(AnnotatedClass cls) {
        boolean hasNoArg = false;
        boolean hasCtx = false;
        for (int i = 0; i < cls.getMethods().size(); i++) {
            MethodInfo m = cls.getMethods().get(i);
            if (!m.isConstructor() || !m.isPublic()) continue;
            String d = m.getDescriptor();
            if (NO_ARG_CTOR_DESC.equals(d)) hasNoArg = true;
            else if (CTX_CTOR_DESC.equals(d)) hasCtx = true;
        }
        if (hasCtx) return ConstructorKind.ROUTE_CONTEXT;
        if (hasNoArg) return ConstructorKind.NO_ARG;
        return ConstructorKind.NONE;
    }

    private static String dot(String internalName) {
        return internalName == null ? "null" : internalName.replace('/', '.');
    }

    // ------------------------------------------------------------------------
    // Bytecode generation
    // ------------------------------------------------------------------------

    /// Generates:
    /// ```
    /// public final class com.codename1.router.generated.RoutesIndex {
    ///   private RoutesIndex() {}
    ///   public static void register() {
    ///     Router r = Router.getInstance();
    ///     r.route("/a", new RoutesIndex$Builder(0));
    ///     r.route("/b", new RoutesIndex$Builder(1));
    ///     // ...
    ///   }
    /// }
    /// ```
    static byte[] generateIndex(List<Entry> routes) {
        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);
        cw.visit(Opcodes.V1_8, Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL | Opcodes.ACC_SUPER,
                INDEX_INTERNAL, null, "java/lang/Object", null);
        cw.visitSource("RoutesIndex.java", null);

        // private RoutesIndex() { super(); }
        MethodVisitor init = cw.visitMethod(Opcodes.ACC_PRIVATE, "<init>", "()V", null, null);
        init.visitCode();
        init.visitVarInsn(Opcodes.ALOAD, 0);
        init.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
        init.visitInsn(Opcodes.RETURN);
        init.visitMaxs(1, 1);
        init.visitEnd();

        // public static void register() { ... }
        MethodVisitor reg = cw.visitMethod(Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC,
                "register", "()V", null, null);
        reg.visitCode();
        reg.visitMethodInsn(Opcodes.INVOKESTATIC, ROUTER_INTERNAL, "getInstance",
                "()L" + ROUTER_INTERNAL + ";", false);
        reg.visitVarInsn(Opcodes.ASTORE, 0);

        for (int i = 0; i < routes.size(); i++) {
            reg.visitVarInsn(Opcodes.ALOAD, 0);
            reg.visitLdcInsn(routes.get(i).pattern);
            reg.visitTypeInsn(Opcodes.NEW, DISPATCH_INTERNAL);
            reg.visitInsn(Opcodes.DUP);
            pushInt(reg, i);
            reg.visitMethodInsn(Opcodes.INVOKESPECIAL, DISPATCH_INTERNAL, "<init>", "(I)V", false);
            reg.visitMethodInsn(Opcodes.INVOKEVIRTUAL, ROUTER_INTERNAL, "route",
                    "(Ljava/lang/String;L" + BUILDER_INTERNAL + ";)L" + ROUTER_INTERNAL + ";",
                    false);
            reg.visitInsn(Opcodes.POP);
        }

        reg.visitInsn(Opcodes.RETURN);
        reg.visitMaxs(0, 0); // COMPUTE_MAXS
        reg.visitEnd();

        cw.visitEnd();
        return cw.toByteArray();
    }

    /// Generates the dispatcher inner class:
    /// ```
    /// final class com.codename1.router.generated.RoutesIndex$Builder
    ///         implements com.codename1.router.RouteBuilder {
    ///   private final int idx;
    ///   Builder(int idx) { this.idx = idx; }
    ///   public com.codename1.ui.Form build(com.codename1.router.RouteContext ctx) {
    ///     switch (idx) {
    ///       case 0: return new com.example.HomeForm();
    ///       case 1: return new com.example.ProfileForm(ctx);
    ///       // ...
    ///     }
    ///     throw new AssertionError("bad route index");
    ///   }
    /// }
    /// ```
    static byte[] generateDispatcher(List<Entry> routes) {
        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);
        cw.visit(Opcodes.V1_8, Opcodes.ACC_FINAL | Opcodes.ACC_SUPER,
                DISPATCH_INTERNAL, null, "java/lang/Object",
                new String[] { BUILDER_INTERNAL });
        cw.visitInnerClass(DISPATCH_INTERNAL, INDEX_INTERNAL, "Builder",
                Opcodes.ACC_PRIVATE | Opcodes.ACC_STATIC | Opcodes.ACC_FINAL);

        cw.visitField(Opcodes.ACC_PRIVATE | Opcodes.ACC_FINAL, "idx", "I", null, null).visitEnd();

        MethodVisitor init = cw.visitMethod(0, "<init>", "(I)V", null, null);
        init.visitCode();
        init.visitVarInsn(Opcodes.ALOAD, 0);
        init.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
        init.visitVarInsn(Opcodes.ALOAD, 0);
        init.visitVarInsn(Opcodes.ILOAD, 1);
        init.visitFieldInsn(Opcodes.PUTFIELD, DISPATCH_INTERNAL, "idx", "I");
        init.visitInsn(Opcodes.RETURN);
        init.visitMaxs(0, 0);
        init.visitEnd();

        // public Form build(RouteContext ctx)
        MethodVisitor build = cw.visitMethod(Opcodes.ACC_PUBLIC,
                "build", "(L" + CONTEXT_INTERNAL + ";)L" + FORM_INTERNAL + ";", null, null);
        build.visitCode();
        build.visitVarInsn(Opcodes.ALOAD, 0);
        build.visitFieldInsn(Opcodes.GETFIELD, DISPATCH_INTERNAL, "idx", "I");

        if (routes.isEmpty()) {
            // Defensive: empty routes — throw straight away.
            emitAssertionThrow(build, "no @Route classes configured");
            build.visitInsn(Opcodes.POP); // pop the idx we loaded
        } else {
            Label[] caseLabels = new Label[routes.size()];
            for (int i = 0; i < routes.size(); i++) caseLabels[i] = new Label();
            Label defaultLabel = new Label();
            build.visitTableSwitchInsn(0, routes.size() - 1, defaultLabel, caseLabels);

            for (int i = 0; i < routes.size(); i++) {
                build.visitLabel(caseLabels[i]);
                Entry e = routes.get(i);
                build.visitTypeInsn(Opcodes.NEW, e.targetInternal);
                build.visitInsn(Opcodes.DUP);
                if (e.kind == ConstructorKind.ROUTE_CONTEXT) {
                    build.visitVarInsn(Opcodes.ALOAD, 1);
                    build.visitMethodInsn(Opcodes.INVOKESPECIAL, e.targetInternal,
                            "<init>", CTX_CTOR_DESC, false);
                } else {
                    build.visitMethodInsn(Opcodes.INVOKESPECIAL, e.targetInternal,
                            "<init>", NO_ARG_CTOR_DESC, false);
                }
                build.visitInsn(Opcodes.ARETURN);
            }

            build.visitLabel(defaultLabel);
            emitAssertionThrow(build, "bad route index");
        }

        build.visitMaxs(0, 0);
        build.visitEnd();

        cw.visitEnd();
        return cw.toByteArray();
    }

    private static void pushInt(MethodVisitor mv, int v) {
        if (v >= -1 && v <= 5) {
            mv.visitInsn(Opcodes.ICONST_0 + v);
        } else if (v >= Byte.MIN_VALUE && v <= Byte.MAX_VALUE) {
            mv.visitIntInsn(Opcodes.BIPUSH, v);
        } else if (v >= Short.MIN_VALUE && v <= Short.MAX_VALUE) {
            mv.visitIntInsn(Opcodes.SIPUSH, v);
        } else {
            mv.visitLdcInsn(Integer.valueOf(v));
        }
    }

    private static void emitAssertionThrow(MethodVisitor mv, String message) {
        mv.visitTypeInsn(Opcodes.NEW, "java/lang/AssertionError");
        mv.visitInsn(Opcodes.DUP);
        mv.visitLdcInsn(message);
        mv.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/AssertionError",
                "<init>", "(Ljava/lang/Object;)V", false);
        mv.visitInsn(Opcodes.ATHROW);
    }

    // ------------------------------------------------------------------------
    // Data carriers
    // ------------------------------------------------------------------------

    /// Visible for unit tests.
    public enum ConstructorKind { NO_ARG, ROUTE_CONTEXT, NONE }

    /// Visible for unit tests.
    public static final class Entry {
        public final String pattern;
        public final String targetInternal;
        public final ConstructorKind kind;

        public Entry(String pattern, String targetInternal, ConstructorKind kind) {
            this.pattern = pattern;
            this.targetInternal = targetInternal;
            this.kind = kind;
        }
    }

    /// Test hook: returns the accepted entries in deterministic order (pattern
    /// sort). Cleared on every `#start`.
    public Map<String, Entry> getAccepted() {
        return new LinkedHashMap<String, Entry>(accepted);
    }

    /// Test hook: clear state between runs in unit tests that don't go through
    /// the Mojo orchestrator.
    public void resetForTesting() {
        accepted.clear();
    }
}
